### ISSUE TITLE
Airpay (RSP) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1003]
- context/timestamp can't be same for all the APIs
- message_id should be the same for message pair

**/collector_recon**

- buyer app finder fee is Rs 15/- and still deduction_by_collector is 0
- settlement_reason_code can't be 01 (Settled)

**/receiver_recon**

- order_recon_status is missing

**/on_collector_recon**

- ttl should be defined as mentioned in the API contract

#### /recon_status and /on_recon_status are missing

@jayesh-airpay

**Comment by RupalSingla** [comment]
/collector_recon

* context/ttl should be "P3D"

/settle

* settlements.timestamp": "" is empty

/receiver_recon

buyer_app_finder_fee_amount": "15",  is given in receiver recon API but in collector recon this is 0.

/on_receiver_recon

Timestamp in receiver_recon should be less than timstamp in on_collector recon, you  have given 

timestamp": "2023-08-19T14:10:14.711Z for on_receiver recon and 

timestamp: "2023-08-18T18:40:56.300Z" for on_collector recon

@jayesh-airpay 
@

**Comment by jayesh-airpay** [comment]
++ @Rohan ***@***.***>


________________________________

**Comment by jayesh-airpay** [comment]
Hi Team,

We have resubmitted the logs. Please find below the pull request.
https://github.com/ONDC-Official/verification-logs/pull/1192

Regards,
Rohan Pugaonkar
________________________________

**Comment by bluecypher** [comment]
- placeholder values should not be used for timestamp in /on_settle and settlement_reason_code in /collector_recon

@jayesh-airpay

**Comment by bluecypher** [comment]
Logs cleared for v1.0.0, pending above change being enabled

@jayesh-airpay

**Comment by amultamse** [comment]
@bluecypher We did not understand the query raised here. Could you please explain in more detail?
