### ISSUE TITLE
Delhivery (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1033]
on_issue
- context.version should be 1.0.0
- status should not be part of the respondent_actions object

on_issue_status
- context.version should be 1.0.0
- complainant_actions trail should not be provided by the respondent
- status should not be part of the respondent_actions object
- respondentEmail, is a wrong attribute
- respondentContact attribute name as been changed

Clarifications
- Given that complaints raised would be for orders from a buyer on a buyer app, the entire action trail showcased should be provided in the action trail including ones done by retail seller app as well 

@utkarsh-v

**Comment by utkarsh-v** [comment]
@Rishabh-ondc pls review.
PR : https://github.com/ONDC-Official/v1.1.0-logs/pull/547/files

**Comment by Rishabh-ondc** [comment]
on_issue
- context.ttl is not required

on_issue_status
- resolution_support and resolution object attributes are different from the specs. Please refer to the API contract for the same

Clarifications
- Include complaint close API call as well in the logs

@utkarsh-v

**Comment by utkarsh-v** [comment]
@Rishabh-ondc pls review
https://github.com/ONDC-Official/v1.1.0-logs/pull/573/files

**Comment by Rishabh-ondc** [comment]
on_issue_status
- resolution_support.contact.name is an invalid attribute, please check the API contract

Clarifications
- Optional attributes such as chat_link and refund_amount need not be shared if empty

@utkarsh-v

**Comment by utkarsh-v** [comment]
@Rishabh-ondc 
pls review:
https://github.com/ONDC-Official/v1.1.0-logs/pull/590/files

**Comment by Rishabh-ondc** [comment]
Logs cleared

@utkarsh-v
