### ISSUE TITLE
ZRPL (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1037]
Flow 1
on_issue
- context.ttl should not be there
- issue.created_at has changed

on_issue_status
- issue.created_at has changed
- issue.updated_at has changed
- issue.updated_at is different from respondent_actions.updated_at

on_issue_status_unsolicited
- respondent_actions.updated_at and issue.updated_at should be the same
- respondent_info.type should be TRANSACTION-COUNTERPARTY-NP
- Avoid using placeholder value for respondent_info.resolution.chat_link 
- respondent_info.resolution.gros.gro_type should be TRANSACTION_COUNTERPARTY-NP-GRO

Clarifications
- Include close complaint call as well  

Flow 2
on_issue
- same as above

on_issue_status
- same as above

on_issue_status_unsolicited
- same as above

Clarifications 
- same as above

@SudarshanSirsi

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue
- issue.updated_at should be less than equal to context.timestamp

Flow 2 
on_issue
- issue.updated_at should be less than equal to context.timestamp

@SudarshanSirsi

**Comment by Rishabh-ondc** [comment]
Flow 1
04_on_issue_status
- domain code in respondent_actions.org.name has changed

Flow 2
- same as above

@SudarshanSirsi

**Comment by SudarshanSirsi** [comment]
Please review the logs submitted in the PR 
https://github.com/ONDC-Official/v1.1.0-logs/pull/684#issue-1972995200
@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
Logs cleared

@SudarshanSirsi
