### ISSUE TITLE
XpressBees (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1038]
on_issue
- context.ttl should not be sent

on_issue_status
- context.ttl should not be sent

@ashwinkumarkuntla

**Comment by ashwinkumarkuntla** [comment]
- Resolved above IGM issues and resubmitted logs, Kindly review it.

@bluecypher @Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
Logs cleared

@ashwinkumarkuntla
