### ISSUE TITLE
Shipdelight (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1039]
on_issue
- context.ttl should not be there
- context.timestamp has not changed
- respondent_info.updated_at for CASCADED and PROCESSING (LSP) has not cahnged\
- issue.updated_at has not changed

on_issue_status
- context.city is missing
- repondent_info.contact and person and changing between PROCESSING action and RESOLVED action, please check

Clarifications
- Hope issue_status call is not being waited for providing a resolution
- Avoid using placeholder values for various attributes
- Escalation need not be illustrated as of now

@sri-shipdelight

**Comment by sri-shipdelight** [comment]
@Rishabh-ondc  Feedback has been incorporated. Kindly review - #1088

**Comment by Rishabh-ondc** [comment]
on_issue_status
- resolution as well as the resolved action should be provided together and not over separate calls
- resolution description simply says no action, please elaborate on why the action_triggered is no-action

@sri-shipdelight

**Comment by Rishabh-ondc** [comment]
Logs cleared

@sri-shipdelight
