### ISSUE TITLE
Dailybee (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1041]
on_issue
- context.ttl should not be there

on_issue_status
- context.ttl should not be there

on_issue_status_closed
- context.ttl should not be there

Clarifications
- Please share for cascaded flows for logistics related (fulfillment) complaints. In case of on-network network logistics, follow scenarios defined. For off-network logistics, share two logs, one for ITEM category and FULFILLMent category.
- The unsolicited call for resolving complaints, should be sent immediately when a resolution is provided, currently provided after a minute or so

@a-satyateja

**Comment by a-satyateja** [comment]
Updated logs as per suggestions. 
@Rishabh-ondc , please check this PR -> https://github.com/ONDC-Official/verification-logs/pull/1087

**Comment by Rishabh-ondc** [comment]
Offnetwork Flow 1
on_issue_log
- respondent_actions.updated_by.org.name should have "subscriber_id::domain_code"
- Provide actual/ near actual values for respondent_actions.contact.phone and email

on_issue_status_log
- same as above

on_issue_status_resolved_log
- context.message_id is the same as on_issue, should change
- Provide actual/ near actual values for gros.contact.phone and email

Offnetwork Flow 2
- same as above


Onnetwork Flow 1
on_issue
- respondent_actions.updated_by.org.name should have "subscriber_id::domain_code"
- Provide actual/ near actual values for respondent_actions.contact.phone and email

issue-open
- context.version should be 1.0.0
- context.ttl should be there
- respondent_actions.updated_by.org.name should have "subscriber_id::domain_code" (in this case logistics domain for cascaded action)
- Provide actual/ near actual values for respondent_actions.contact.phone and email

on_issue_status-1
- context.message_id is the same as on_issue, should change
- issue.updated_at should not change if there is no update done by the seller app

issue_status (logistics)
- context.version should be 1.0.0
- context.ttl should be there

on_issue_status-resolved(logistics)
- is this a payload for an unsolicited call? message id is different than the respective issue_status call 

on_issue_status-2-resolved
- issue.updated_at should not change

issue-close (logistics)
- context.version should be 1.0.0
- context.ttl should be there
- issue.updated_at has changed

Onnetwork Flow
- same as above

on_issue_status 2 resolved
- if the resolution is provided by the seller app, the resolution_provider object should also noting the details of the seller app who is now becoming the resolution provider

@a-satyateja

**Comment by a-satyateja** [comment]
@Rishabh-ondc 

We have addressed the above comments, 
Please check the new logs here: https://github.com/ONDC-Official/verification-logs/pull/1117

**Comment by Rishabh-ondc** [comment]
Off network - Flow-item
on_issue-unsolicited
- contact.phone and person.name is changing across actions taken by seller app. Please check.

Off network - Flow-fulfillment
- same as above

On network - Flow-1
issue (open) logistics
- issue.updated_at has not changed
- domain code for NP (in updated_by.org) when cascading should of logistics

On newtork - Flow 2
issue (open) logistics
- issue.updated_at has not changed
- domain code for NP (in updated_by.org) when cascading should of logistics

on_issue_status-unsolicited
- If the resolution is now being provided seller app, the resolution provider will also change to the details of the seller app

Clarifications
- unsolicited on_issue_status calls in the cascaded flows should have a different message_id from the logistics call

@a-satyateja

**Comment by a-satyateja** [comment]
Hi @Rishabh-ondc , 
Updated the logs as per the comments above. 
Kindly verify, https://github.com/ONDC-Official/verification-logs/pull/1131

**Comment by Rishabh-ondc** [comment]
Off network - Item flow
on_issue
- context.timestamp is less than issue.context.timestamp

on_issue_status
- context.timestamp is less than issue_status.context.timestamp

Off network - Fulfillment flow
on_issue_status
- context.timestamp is less than issue_status.context.timestamp


On network - Flow 1
- is the same transaction_id being used for retail as well as logistics transactions?

issue_status (logistics)
- context.message_id is same as issue_status.context.message_id

On network - Flow 2
- same as above

@a-satyateja

**Comment by Rishabh-ondc** [comment]
On network - Flow 1
issue(logistics)-open
- context.timestamp is less than on_issue.context.timestamp
- respondent_actions.updated_at for CASCADED is less than PROCESSING

On network - Flow 2
- logs shared are the same as Flow 1

@a-satyateja

**Comment by a-satyateja** [comment]
@Rishabh-ondc 
Addressed the comments. 
PR-> https://github.com/ONDC-Official/verification-logs/pull/1179

**Comment by Rishabh-ondc** [comment]
Logs cleared

@a-satyateja
