### ISSUE TITLE
Xpressbazaar (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1046]
**/receiver_recon**

- settlement_reference should be updated in payment object
- created_at timestamp can't be the same as /receiver_recon timestamp

**/on_receiver_recon**

- callback should be sent within the ttl
- collected amount and settlement amount are same, even though buyer app finder fee is 15.3; the counterparty_recon_status must be an overpaid scenario.
- order_recon_status should be 02 (Final)

**Comment by bluecypher** [comment]
**receiver_recon**

- deduction by collector can't be 0 when buyer app finder fee is not 0
- settlement_timestamp and order/updated_at timestamp can't be equal to the /receiver_recon timestamp; amount is settled before

**/on_receiver_recon**

- counterparty_recon_status can't be 03 (Underpaid) for successful reconciliation flow

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@bluecypher, 
For this settlement_timestamp and order/updated_at timestamp can't be equal to the /receiver_recon timestamp; amount is settled before, I took reference from razorpay logs, please give me the clarification on this.

**Comment by NJ-Nitank** [comment]
@bluecypher, Revised logs have been submitted, Plz check, 
https://github.com/ONDC-Official/verification-logs/pull/1061

**Comment by NJ-Nitank** [comment]
@bluecypher, Any update on this?

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
Thanks @bluecypher
