### ISSUE TITLE
Shadowfax (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1049]
on_issue
- respondent_actions.updated_at has six digits for milliseconds, it should only be 3 digits
- issue.updated_at has not changed

on_issue_status
- context.message_id has changed
- respondent_actions.updated_at has six digits for milliseconds, it should only be 3 digits
- issue.updated_at and respondent_actions.updated_at is different

Clarifications
- Hope issue_status call is not being waited for providing a resolution, unsolicited responses can be shared for the same
- Please use real/ near real values for contact.phone and person.name

@mallikharjun-p

**Comment by mallikharjun-p** [comment]
@Rishabh-ondc I have updated the logs

regarding

Hope issue_status call is not being waited for providing a resolution, unsolicited responses can be shared for the same -> yes

 Please use real/ near real values for contact.phone and person.name -> we discussed about this earlier, we do not have the phone number and name, since we are doing only Hyperlocal

**Comment by mallikharjun-p** [comment]
@Rishabh-ondc Please check again updated logs

**Comment by Rishabh-ondc** [comment]
Flow 1
- logs for two separate complaint flows have been provided, please check

@mallikharjun-p

**Comment by mallikharjun-p** [comment]
@

> Flow 1
> 
> * logs for two separate complaint flows have been provided, please check
> 
> @mallikharjun-p

is there any issue because of this ? @Rishabh-ondc

**Comment by mallikharjun-p** [comment]
@Rishabh-ondc updated the IGM logs please check

**Comment by mallikharjun-p** [comment]
@Rishabh-ondc Please check the logs

**Comment by mallikharjun-p** [comment]
@Rishabh-ondc Can you please check the logs

**Comment by Rishabh-ondc** [comment]
Logs cleared 

@mallikharjun-p
