### ISSUE TITLE
Digiit (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1067]
on_issue
- context.core_version should be 1.0.0
- issue.created_at has changed
- issue.created_at updated_at and respondent_actions.updated_at timestamps are not as per the format to be used
- issue.updated_at should be same as the respondent_actions.updated_at of last action in the trail

on_issue_status
- context.core_version should be 1.0.0
- issue.created_at has changed
- respondent_actions.updated_at timestamps are not as per the format to be used

on_issue resolved 
- context.core_version should be 1.0.0
- context.message_id is the same, unsolicited calls should have different message_id
- resolved action should be provided in the on_issue_status API call and should come with the resolution object and resolution provider object
- issue.created_at updated_at and respondent_actions.updated_at timestamps are not as per the format to be used

on_issue_status resolved
- context.core_version should be 1.0.0

Clarifications
- Include complaint close API call as well
- Illustrate two flows, one for ITEM category and one for FULFILLMENT category. If on-network logistics is procured, illustrate two flows for FULFILLMENT category as mentioned in the test case scenarios document

@vignesh-arvind

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue
- context.action should be "on_issue"
- context.ttl is not required
- Follow appropriate timestamp format
- respondent_actions.updated_at seems in a different time zone, please check

on_issue_status
- Same payload provided as on_issue

on_issue resolved
- same as provided in the earlier previous comments

on_issue_status Resolved
- context.ttl is not required
- context.message_id same as on_issue resolved
- respondent_actions.updated_at and issue.updated_at should be same

Flow 2
on_issue-IN-PROGRESS
- context.version provided is 1.1.0
- Follow appropriate timestamp format
- respondent_actions.updated_at seems in a different time zone, please check

issue CASCADED TO LSP
- context.message_id is the same as issue call
- Follow appropriate timestamp format
- respondent_actions.updated_by.org.name should have domain code as nic2004:60232 for logistics

on_issue LSP IN-PROGRESS
- context.bap_id is that of the retail buyer app
- context.version provided is 1.1.0
- Follow appropriate timestamp format
- respondent_actions.updated_at seems in a different time zone, please check
- respondent_actions.short_desc not provided
- respondent_actions.updated_by.org should have domain code as nic2004:60232 for logistics

on_issue_status IN-PROGRESS
- similar as above
- context.timestamp is less than timestamp for on_issue 

on_issue LSP RESOLVED
- same as provided in the earlier previous comments

Clarification
- no resolution object provided
- complaint close call should be cascaded to logistics provider as well

Flow 3
- similar as above

@vignesh-arvind

**Comment by RupalSingla** [comment]
FLOW 2 

/on_issue_status RESOLVED

* created_at cannot be greater than updated_at in any API

@vignesh-arvind

**Comment by Rishabh-ondc** [comment]
on_issue
- context.message_id has changed
- issue.created_at has changed
- respondent_actions.updated_at should be less than equal to issue.updated_at

issue
- context.domain should be nic2004:60232
- issue.complainant_info.contact.email has changed
- issue.updated_at has not changed
- respondent_actions.updated_by.org.name should contain domain code nice2004:60232 for CASCADED action

on_issue LSP Processing
- context.message_id has changed
- issue.created_at has changed
- respondent_actions.updated_at should be less than equal to issue.updated_at

on_Issue_status retail processing and on_issue_status lsp processing
- same payload provided; not clear when/ why they are being sent

on_issue resolved LSP
- this should not be a separate API call. Resolution action should be provided along with resolution and resolution provider in the on_issue_status API call

on_issue resolved
- this should not be a separate API call. Resolution action should be provided along with resolution and resolution provider in the on_issue_status API call
- respondent action trail incomplete, not capturing all the actions taken so far

on_issue_status resolved
- respondent action trail incomplete

issue closed
- API call should also be cascaded from retail seller app to logistics seller app

Clarification
- Flow 2 should be illustrated with LSP as the resolution provider

@vignesh-arvind

**Comment by Rishabh-ondc** [comment]
Flow 1
8. issue_status
- same context.message_id as 7. issue_status context.message_id
- same context.timestamp as 7. issue_status context.timestamp

6. on_issue_status RETAIL PROCESSING
- context.timestamp is lesser than 5. on_issue_status LSP PROCESSING, please check
- context.version should be 1.0.0
- issue.updated_at has changed

10. on_issue_status RETAIL RESOLVED
- issue.updated_at has changed

12. issue_closed
- context.message_id is same
- same context.message_id as 11. issue_status context.message_id
- same context.timestamp as 11. issue_status context.timestamp

@vignesh-arvind

**Comment by vignesh-arvind** [comment]
@Rishabh-ondc   need a clarification on the below comment 

6. on_issue_status RETAIL PROCESSING

- resolution_support.gros should also capture details of the GRO details of the seller app as well in both cases


why resolution support.gros is required in PROCESSING state?  only after the RESOLUTION state it is provided.

**Comment by Rishabh-ondc** [comment]
@vignesh-arvind Yes, mistagged the payload name. The feedback is for on_issue_status RETAIL RESOLVED.

**Comment by vignesh-arvind** [comment]
@Rishabh-ondc  Thanks Rishab

**Comment by Rishabh-ondc** [comment]
Logs cleared

@vignesh-arvind
