### ISSUE TITLE
Bitsila (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1068]
Flow 1 
on_issue
- issue.updated_at should be less than or equal to context.timestamp
- context.action should be "on_issue"
- context.ttl is not required

on_issue_status
- issue.updated_at should be less than or equal to context.timestamp
- context.action should be "on_issue_status"
- context.ttl is not required

Flow 2
on_issue
- issue.updated_at should be less than or equal to context.timestamp
- issue.updated_at should be same as the latest respondent_actions.updated_at
- context.ttl is not required

on_issue_status
- context.action should be "on_issue_status"
- context.ttl is not required

Clarifications
- Hope the issue_status call is not being waited for the resolution action, it can be unsolicited call

@dgowda604

**Comment by dgowda604** [comment]
Yes Rishabh 
Yes issue_status call is not being waited

**Comment by dgowda604** [comment]
@Rishabh-ondc please check this PR ->  https://github.com/ONDC-Official/verification-logs/pull/1074
Submitted logs based on the above comments

**Comment by Rishabh-ondc** [comment]
Flow 1 
- Please include log for complaint close issue API call

Flow 2 
- Please include log for complaint close issue API call

Clarifications
- Resolutions should ideally be provided thorough unsolicited /on_issue_status call
- Complaints related to delivered quantity shouldn't be raised until order is delivered; sellers should fulfill the order first. refund should not be provided otherwise

@dgowda604

**Comment by dgowda604** [comment]
@Rishabh-ondc added logs for the same -> https://github.com/ONDC-Official/verification-logs/pull/1082

Clarifications -> Yes all these are only applicable on pre-prod, so that our testing would be more easier.

**Comment by Rishabh-ondc** [comment]
Logs cleared

**Comment by Rishabh-ondc** [comment]
Reopening for further review

Delay_in_delivery
on_issue
- issue.updated_at should be less than or equal to context.timestamp and it should be same as the last action's respondent_actions.updated
- issue.created_at has changed

on_issue_status
- the timestamp of this call is after the on_issue_to_lsp call but the trail provided does not capture lsp's actions, please check

on_issue_status_refunded
- issue.updated_at has changed with no updates being done by the seller app
- gro information of the seller app has not been provided in the gros object

Clarifications
- order.id has changed over issue and issue_to_lsp, just check if that was intended or missed
- Please share logs for issue_close call to the lsp as well
- Please share logs for fulfillment category complaint where seller app also provides resolution not cascading the lsp's provided resolution

item_mismatch
on_issue
- issue.updated_at should be less than or equal to context.timestamp and it should be same as the last action's respondent_actions.updated
- issue.created_at has changed

on_issue_status
- only resolved action trail is shared in the respondent_actions
- respondent_actions.updated_at for "RESOLVED" seems of old timestamp

@dgowda604

**Comment by dgowda604** [comment]
@Rishabh-ondc updated the logs accordingly, please do check this PR for the same -> https://github.com/ONDC-Official/verification-logs/pull/1230

**Comment by Rishabh-ondc** [comment]
Logs cleared

@dgowda604
