### ISSUE TITLE
Dailybee (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1105]
- submit logs with buyer app finder fee amount as non-zero

**/receiver_recon**

- settlement_counterparty should be seller-app in payment/@ondc/org/settlement_details/

**/on_receiver_recon**

- /message/orderbook/orders/0/order_recon_status should be "02" (Final)

@a-satyateja

**Comment by a-satyateja** [comment]
@bluecypher 

We have updated the logs as per suggestions. 
Please check: https://github.com/ONDC-Official/verification-logs/pull/1117

**Comment by RupalSingla** [comment]
Flow1 you need to send at least 5 orders in the orderbook 

@a-satyateja

**Comment by a-satyateja** [comment]
@RupalSingla 

Updated the RSF Logs as per comments:
PR-> https://github.com/ONDC-Official/verification-logs/pull/1179

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0.

@a-satyateja
