### ISSUE TITLE
Kiko (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1110]
Flow 1 
on_issue
- context.core_version should be "1.0.0"
- context.timestamp should be greater or equal to issue.updated_at
- context.ttl is not required
- issue.created_at has changed
- issue.updated_at should be same respondent_action.updated_at should be the same

unsolicited_on_issue_status
- context.core_version should be "1.0.0"
- context.ttl is not required
- issue.created_at has changed
- issue.updated_at should be same respondent_action.updated_at should be the same

on_issue_status
- same as above

Flow 2
- same as above

@vickyKiko

**Comment by Rishabh-ondc** [comment]
Flow 1
issue
- How is respondent_actions being populated in the issue call from the buyer app?

Flow 2
issue
- How is respondent_actions being populated in the issue call from the buyer app?

Clarifications
- The refund_amount mentioned in both flows resolution is exactly the same, with different order_ids, please check

@vickyKiko

**Comment by vickyKiko** [comment]
@Rishabh-ondc 
Clarifications
The refund_amount mentioned in both flows resolution is exactly the same, with different order_ids, please check

Answer - Yes, The item ordered was the same for both order IDs hence refund amount calculated is the same.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@vickyKiko
