### ISSUE TITLE
Shopalyst (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1111]
**/receiver_recon**

- settlement_reference_no in /orders mismatches with settlement_reference in "@ondc/org/settlement_details"
- successful reconciliation by the receiver for 5 or more transactions should be provided as per flow 1

**/on_receiver_recon**

- settlement_reference_no and transaction_id mismatch in /receiver_recon and /on_receiver_recon
- why orderbook for successful settlement provided for only one of the orders?

@kishorgandham

**Comment by kishorgandham** [comment]
@bluecypher fixes incorporated in this pull request
https://github.com/ONDC-Official/verification-logs/pull/1125
Kindly merge and verify

**Comment by kishorgandham** [comment]
@bluecypher @Rishabh-ondc kindly merge the PR https://github.com/ONDC-Official/verification-logs/pull/1178 and review

**Comment by kishorgandham** [comment]
@bluecypher any update on this?

**Comment by bluecypher** [comment]
**/on_receiver_recon**

- ttl to send /on_receiver_recon is 2 days; if the callback takes longer than that, it will be considered as deemed settled.
- orders/transaction_id can't change


@kishorgandham

**Comment by kishorgandham** [comment]
@bluecypher fixed per your last comment
Please merge and review:
https://github.com/ONDC-Official/verification-logs/pull/1250

**Comment by kishorgandham** [comment]
@bluecypher any update on our last submission?

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@kishorgandham
