### ISSUE TITLE
TMBill (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1140]
Flow 1
on_issue_processing
- issue.created_at shouldn't change
- complainant_actions trail should not be provided in the response calls by the respondents
- issue.status is not required in response calls from respondents 
- context.tll is not required

on_issue_status
- need-more-info isn't part of the MVP flows as of now, need not be illustrated

on_issue_status resolved
- issue.updated_at has not changed
- wrong timestamp format used for respondent._actions.updated_at
- complainant_actions trail should not be provided in the response calls by the respondents
- issue.status is not required in response calls from respondents 

Flow 2
- same as above
- escalation flows not are there not part of the MVP flows and need not be illustrated

@sid-tmbill

**Comment by sid-tmbill** [comment]
@Rishabh-ondc PR is Submitted for the above mentioned changes https://github.com/ONDC-Official/v1.1.0-logs/pull/568

**Comment by Rishabh-ondc** [comment]
on_issue_processing
- issue.updated_at has not changed
- respondent_actions.updated_by.org.name should be in the format - "subscriber_id::domain_code"

on_issue_status_resolved
- context.message_id should be unique for unsolicited calls; it is currently the same as on_issue call
- context.timestamp should be greater than or equal to respondent_actions.updated_at
- issue.updated_at should be the same as respondent_actions.updated_at
- respondent_actions.updated_by.org.name should be in the format - "subscriber_id::domain_code"
- respondent_info.organization.org.name should be in the format - "subscriber_id::domain_code"

Clarification
- only one log is shared, please share two logs, one for ITEM complaint and one for FULFILLMENT complaint

@sid-tmbill

**Comment by sid-tmbill** [comment]
@Rishabh-ondc PR is Submitted for the above-mentioned changes https://github.com/ONDC-Official/v1.1.0-logs/pull/582

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_processing
- issue.updated_at should be same as latest action's timestamp of respondent_actions.updated_at
- context.timestamp should be greater than equal to issue.updated_at timestamp

on_issue_status
- context.message_id has changed
- issue.updated_at has changed between on_issue and on_issue_status

on_issue_status_resolved
- resolution object not provided

Flow 2
- same as above

@sid-tmbill

**Comment by sid-tmbill** [comment]
Hi @Rishabh-ondc the PR is submitted that will fix this issue. 
PR : https://github.com/ONDC-Official/v1.1.0-logs/pull/594

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_processing
- issue.updated_at is lesser than issue.context, please check

on_issue_status_resolved
- the API call is made 15 minutes after the resolution timestamp, please check, is there any specific flow envisioned?

Flow 2
on_issue_status_resolved
- the API call is made 10 minutes after the resolution timestamp, please check, is there any specific flow envisioned?

issue_close
- updated payload not provided, please check

@sid-tmbill

**Comment by sid-tmbill** [comment]
Hi @Rishabh-ondc the PR is submitted that will fix this issue.
PR : https://github.com/ONDC-Official/v1.1.0-logs/pull/604

**Comment by Rishabh-ondc** [comment]
Logs cleared

@sid-tmbill
