### ISSUE TITLE
CSC (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1141]
Flow 1
issue
- contact.email should not be sent if null
- order.state and fulfillment_state seem mismatched. order state cannot be completed if fulfillment state is pending
- complainant_actions.updated_by.person and contact is of a representative of the buyer app and not the buyer
- there is a significant gap between complainant_actions.updated_at and issue.created_at (and updated_at); any particular reason?

issue_status
- context.core_version should be 1.0.0

Flow 2
issue
- contact.email should not be sent if null
- order.state and fulfillment_state seem mismatched. order state cannot be completed if fulfillment state is pending
- complainant_actions.updated_by.person and contact is of a representative of the buyer app and not the buyer
- issue.created_at and updated_at should be greater than equal to complainant_actions.updated_at

issue_status
- context.core_version should be 1.0.0

@Ashish0120

**Comment by insphere-ashish** [comment]
@Rishabh-ondc logs have been submitted again with above mentioned changes on https://github.com/ONDC-Official/verification-logs/pull/1154

**Comment by Rishabh-ondc** [comment]
>there is a significant gap between complainant_actions.updated_at and issue.created_at (and updated_at); any particular reason?

The gap still persists. Any specific reason/ work flow?


@Ashish0120 @insphere-ashish

**Comment by insphere-ashish** [comment]
@Rishabh-ondc the first complainant action updated_at time is when the complaint was raised by the buyer in the internal system.,. the complaint although created(logged via internal system) was not yet sent to seller and was in the system for review and is sent as an Issue using ondc IGM system by the Grievance Support Admin  if is found requires the resolution from the seller.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@insphere-ashish
