### ISSUE TITLE
Shikhar Seller App - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1157]
Clarifications
- Please illustrate logs for FULFILLMENT category complaint as well
- empty objects (selected_odrs) need not be sent if optional

@ucansubodh1

**Comment by Sushrut-269** [comment]
@Rishabh-ondc Fulfillment category complaint is already submitted yesterday, can we have a consolidated list of scenarios in one list so that we can avoid these multiple iteration. 

Thanks,
Sushrut

**Comment by Rishabh-ondc** [comment]
Logs cleared 

@ucansubodh1

**Comment by Sushrut-269** [comment]
@Rishabh-ondc thanks for update
