### ISSUE TITLE
NoBroker (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1167]
Flow 1
issue
- context.core_version should be 1.0.0
- issuetType is incorrect attribute; should be "issue_type"
- both item and fulfillment details should be shared for ORDER category complaints; item details not shared
- timings provided for estimated response and resolution time seems reversed, please check
- updated_by.name is invalid schema; updated_by.org.name should be provided; should be in the format "subscriber_id::domain_code"
- all timestamps should be in the UTC format
- issue.updated_at should be the same as complainant_actions.updated_at

issue_status
- context.core_version should be 1.0.0

issue_close
- all attributes in the issue call need not shared, only complainant_actions trail, issue.created_at, updated_at, status and rating is to be shared
- complainant_actions.updated_by for close has incomplete object
- updated_by.name is invalid schema; updated_by.org.name should be provided; should be in the format "subscriber_id::domain_code"
- all timestamps should be in the UTC format
- issue.updated_at should be the same as complainant_actions.updated_at

Flow 2 
- same as above

Clarifications
- empty attributes need not be sent if optional

@Rajkumar1994sof

**Comment by Rajkumar1994sof** [comment]
https://github.com/ONDC-Official/verification-logs/pull/1173

@Rishabh-ondc fixed

**Comment by Rishabh-ondc** [comment]
Flow 1
issue
- rating need not be sent in complaint opening /issue call
- empty attributes need not be sent if optional (merchant_order_id, selected_odrs_info, finalized_odr, resolution_provider, resolution, additional_info_required)
- contact.phone provided is of 12 digits, please check
- complainant_actions.updated_by.contact.phone provided is of 9 digits, please check

issue_close
- context.message_id is the same as issue call
-  all attributes in the issue call need not be shared in the complaint closing call; only complainant_actions trail, issue.created_at, updated_at, status and rating is to be shared
- complaint_actions.updated_by.contact and person is missing for close action

Flow 2
issue
- contact.phone provided is of 12 digits, please check
- complainant_actions.updated_by.contact.phone provided is of 9 digits, please check

issue_close
- context.message_id is the same as issue call
-  all attributes in the issue call need not be shared in the complaint closing call; only complainant_actions trail, issue.created_at, updated_at, status and rating is to be shared
- complaint_actions.updated_by.contact and person is missing for close action

@Rajkumar1994sof

**Comment by Rajkumar1994sof** [comment]
@Rishabh-ondc have raise PR again

**Comment by Rajkumar1994sof** [comment]
https://github.com/ONDC-Official/verification-logs/pull/1208

**Comment by Rishabh-ondc** [comment]
Flow 1
issue
- issue.source.type provided is incorrect, should be consumer
- updated_by.name is invalid schema; updated_by.org.name should be provided; should be in the format "subscriber_id::domain_code"

issue_close
- same as above

@Rajkumar1994sof

**Comment by Rishabh-ondc** [comment]
issue
- order_details.provider_id should be mapped with order.provider.id 

issue_status
- context.action for issue_status should be "issue_status"

issue_close
- issue.id is missing

@Rajkumar1994sof

**Comment by Rishabh-ondc** [comment]
issue
- source.type should be CONSUMER
- complainant_actions.contact is incorrect schema
- complainant_actions.person

issue_close 
- issue.id is missing
- complainant_actions.contact is incorrect schema
- complainant_actions.person

@Rajkumar1994sof

**Comment by Rajkumar1994sof** [comment]
https://github.com/ONDC-Official/verification-logs/pull/1311 @Rishabh-ondc please merge and review this

**Comment by Rishabh-ondc** [comment]
Logs cleared

@Rajkumar1994sof
