### ISSUE TITLE
CSC BAP (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1191]
5 successful transactions must be processed as part of flow 1

**/receiver_recon**

- /context/ttl must be equal to P2D
- /message/orderbook/orders/0/state must be equal to constant (Completed)
- context/transaction_id and payment/params/transaction_id can't be same
- /message/orderbook/orders/0/payment/status must be equal to constant (PAID)
- /message/orderbook/orders/0/payment/@ondc/org/settlement_details/0/settlement_timestamp must match format "date-time"
- /message/orderbook/orders/0/settlement_reference_no mismatches with settlement_reference in "@ondc/org/settlement_details"
- settlement_timestamp can't be future dated
- inaccurate calculation of settlement_amount and deduction by collector
- created_at, updated_at timestamps are incorrect

@Ashish0120

**Comment by bluecypher** [comment]
- updated_at timestamp can't be earlier than settlement_timestamp

@Ashish0120

**Comment by insphere-ashish** [comment]
- settlement details was manually imported 

a new pull request has been raised https://github.com/ONDC-Official/verification-logs/pull/1233

**Comment by bluecypher** [comment]
- settlement_timestamp can't be earlier than created_at timestamp

@insphere-ashish

**Comment by insphere-ashish** [comment]
Of course, as it should be.. by mistake it got changed for the other flow
fix has been pushed 
https://github.com/ONDC-Official/verification-logs/pull/1234

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@insphere-ashish
