### ISSUE TITLE
Buynxt (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1197]
- Invalid context/domain; should be ONDC:NTS10

**/receiver_recon**

- context/transaction_id can't be the same as payment/params/transaction_id
- "settlement_reference" in "@ondc/org/settlement_details" mismtaches with "settlement_reference_no" in /orders
- created_at/updated_at can't be same in an orderbook
- settlement_timestamp can't be the same as context/timestamp

**/on_receiver_recon**

- context/timestamp can't be earlier than /receiver_recon timestamp
- order_recon_status must be 02 (Final)
- settlement amount is not correct; counterparty recon status can't be 01 in that case

@pranav-buynxt

**Comment by bluecypher** [comment]
- core_version should be "1.0.0" in /on_receiver_recon


@pranav-buynxt

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@pranav-buynxt

**Comment by pranav-buynxt** [comment]
Subject: Updated Payloads for Review: Flow 2 /on_confirm and /on_status

Hi Sandeep,
As per our discussion today, we have addressed the two points you raised:

1. **How can estimated pickup and delivery time ranges be provided even before the order is accepted?**
2. **Considering that the 'time_to_ship' provided in /on_search is 3 hours, how can the estimated pickup time range be only 1 hour?**

We have fixed these issues and attached the updated payloads for your review: `on_confirm` and `on_status (order-accepted)`.

In the updated flow:
**- The pickup and delivery times are not sent until the order is accepted.
- As we are sending a ready-to-ship range of 3 hours and a total delivery range of 4 hours in `on_search`, the new pickup range is 3 hours and the delivery range is 1 hour.**

We appreciate your time and understanding.


[on_confirm.json](https://github.com/user-attachments/files/16312403/on_confirm.json)
[on_status(order-accepted).json](https://github.com/user-attachments/files/16312404/on_status.order-accepted.json)

@sandeepshahi
