### ISSUE TITLE
Mystore (GC) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1202]
select
- items.category_ids need not be sent
- category_id mismatch from on_search; on_search has "C1", select has "c1"
- Denominations had not been shared previously. Please share the payloads for previous select/ on_select as well
- fulfillment id mismatch between on_search and select
- stops.contact.email has invalid email shared; it is the attribute used to deliver the gift cards

confirm
- fulfillments.end object is invalid schema, please refer to the API contract
- fulfillments.status attribute not used as of now
- quote.price.value should be string

Clarifications
- Customization is enabled by the seller and it wasn't shared by buyer app. While it is optional, please check it that is a miss or is intentional
- Please share logs for the remaining scenarios as well

@mystore-in

**Comment by mystore-in** [comment]
logs resubmitted for flow 1 

1. fulfillments.status attribute not used as of now this is not there in previous logs

**Comment by mystore-in** [comment]
Hi Rishabh, for on_update thing currently we are using OTP based verification system so there is proper verification of email so there is no such problem to seller also to send the gift card

**Comment by Rishabh-ondc** [comment]
Flow 2
select
- call made before search call, please check

confirm
- Maintain consistency of the billing object between init and confirm call

update
- Schema issues in fulfillments object
- contact information should only be added in the tags in update call, the contact information in stops object should not be updated

@mystore-in

**Comment by Rishabh-ondc** [comment]
Flow 2
confirm
- billing object schema changed

updated
- fulfillments.stops.person.name has changed, just check

@mystore-in

**Comment by mystore-in** [comment]
Hi rishabh sharing you json for confirm and init for gift card as billing object issue is fixed now
confirm payload
http://jsonblob.com/1171020175314378752

init payload
http://jsonblob.com/1171020429124296704

**Comment by Rishabh-ondc** [comment]
Logs cleared

@mystore-in
