### ISSUE TITLE
Ola logistics BPP (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1246]
on_issue
- respondent_action.updated_by.org.name should be in the format "subcriber_id::domain_code"
- issue.updated_at should be greater than equal to respondent_actions.updated_at

on_issue_status
- issue.created_at has changed
- issue.updated_at should not change if there is no change in the action trail

on_issue_status_resolved
- respondent_action.updated_by.org.name should be in the format "subcriber_id::domain_code"
- issue.created_at has changed
- respondent_info.organization.org.name should be of the format "subcriber_id::domain_code"

Clarifications
- optional attribute "chat_link" need not be shared if empty

@mherle

**Comment by Rishabh-ondc** [comment]
on_issue
- context.version should be 1.0.0 for IGM APIs
- respondent_action.updated_by.org.name should be in the format "subcriber_id::domain_code"

on_issue_status
- respondent_actions.updated_at for PROCESSING action has changed between on_issue and on_issue_status

on_issue_status_resolved
- context.message_id should be unique for an unsolicited call
- respondent_actions.updated_at for PROCESSING and RESOLVED are the same
- issue.updated_at has not been updated
- respondent_info.organization.org.name should be of the format "subcriber_id::domain_code"
- resolution.refund_amount should be string

@mherle

**Comment by mherle** [comment]
Noted. Pushing a fix.

On the version, had a discussion with @BLR-0118 . IGM payload version having a different version than that of the orderflow will make the version compatibility a big issue when we need to support multiple core versions of orderflow. 

@BLR-0118 how should this be tracked ? Definitely not in this GitHub issue

**Comment by mherle** [comment]
@Rishabh-ondc All the issues are resolved in this [PR 655](https://github.com/ONDC-Official/v1.1.0-logs/pull/655)

**Comment by mherle** [comment]
@RupalSingla / @Rishabh-ondc  

There is [Issue 667 in v1.1.0-logs](https://github.com/ONDC-Official/v1.1.0-logs/issues/667) as well as [Issue 1246 in verification logs](https://github.com/ONDC-Official/verification-logs/issues/1246). 
Which one should I update now ?

Can one of you close the other as duplicate ? I need only one active issue to record in the ORC sheet.

**Comment by mherle** [comment]
@RupalSingla / @Rishabh-ondc  

Addressed in [PR 675](https://github.com/ONDC-Official/v1.1.0-logs/pull/675). Pls check

**Comment by Rishabh-ondc** [comment]
Closing this thread because of duplication.
