### ISSUE TITLE
Digiledge BPP (RSF) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/verification-logs#1254]
For prepaid order, Digiledge would be a receiver (being a seller app); bpp_id should be of Digiledge
- 5 successful orders must be present as part of flow 1

@shabirahamed

**Comment by bluecypher** [comment]
## Correction Flow

**/on_receiver_recon**

- context/domain can't be empty
- context/timestamp can't be earlier than /receiver_recon timestamp


@shabirahamed, resubmit logs for correction flow

**Comment by bluecypher** [comment]
counterparty_recon_status can't be 01 in correction flow

@shabirahamed

**Comment by bluecypher** [comment]
Logs approved for RSF v1.0.0.

@shabirahamed
