### ISSUE TITLE
Fynd (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1264]
Flow 1 
on_issue
- context.timestamp has not changed

on_issue_status
- issue.updated_at and created_at are same

on_issue_status(solicit_post_resolution)
- same payload as on_issue_status(unsolicited), please check

Flow 2
- same as above

on_issue_status (unsolicit)
- context.timestamp should be greater than or equal to message.issue.updated_at

Clarifications
- optional attributes such as chat_link need not be shared if empty

@tusharmoraye

**Comment by Rishabh-ondc** [comment]
on_issue_status(solicit_post_resolution)
- issue.updated_at has chnged
- issue.resolution_provider.respondent_info.resolution_support.gros._id is an invalid attribute

@tusharmoraye

**Comment by tusharmoraye** [comment]
@Rishabh-ondc we will fix it.

**Comment by Rishabh-ondc** [comment]
Logs cleared
