### ISSUE TITLE
Rapidor B2B (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1280]
Item
issue
- location object should be used in context instead of country and city aligning the context object with the B2B implementation
- context.timestamp should be greater than or equal to issue.created_at/ updated_at

on_issue
- issue.created_at has changed
- context.ttl not required

on_issue_status
- resondent_actions.contact has changed between PROCESSING and RESOLVED, please check
- gro_type should be TRANSACTION COUNTERPARTY NP GRO
- context.ttl not required

Clarifications
- order_details.state should have have the enums same as the order status in the order transaction, please check

@rapidor

**Comment by sanushilshad** [comment]
@Rishabh-ondc 
Has resubmitted the logs after fixing the above issues.

**Comment by Rishabh-ondc** [comment]
Fulfillment
on_issue_status
- contact and person object in respondent_actions has changed between on_issue and on_issue_status for PROCESSING action, please check

@rapidor @sanushilshad

**Comment by sanushilshad** [comment]
@Rishabh-ondc 
https://github.com/ONDC-Official/verification-logs/pull/1343

**Comment by Rishabh-ondc** [comment]
Logs cleared

@sanushilshad
