### ISSUE TITLE
iThink_Logistics(RSP) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/verification-logs#1289]
FLOW-1
The order book should contain a minimum of five orders.

FLOW-2
Correction flow is missing .

@shubhamdepasser

**Comment by shubhamdepasser** [comment]
Do you require a minimum of five orders in the 'receive_recon' process. 
@RupalSingla

**Comment by RupalSingla** [comment]
@shubhamdepasser yes, minimum of 5 orders are required

**Comment by shubhamdepasser** [comment]
@RupalSingla Done. I have uploaded logs for five orders. Please check and share your valuable feedback.

**Comment by bluecypher** [comment]
Logs approved for RSF v1.0.0

@shubhamdepasser
