### ISSUE TITLE
IndiaPost (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#1313]
on_issue
- respondent_actions.updated_by.contact attributes provided are empty

on_issue_status
- issue_id, incorrect attribute provided is outside the issue object
- issue.created_at provided is null
- issue.updated_at is missing

on_issue_status_resolved
- context.version should be 1.0.0
- context.ttl not required
- issue.id missing
- order_id incorrect attribute
- resolution_suppport.gro object is incorrect structure

@SrujanMungara

**Comment by Rishabh-ondc** [comment]
on_issue_status
- issue.created_at and updated_at is missing

Clarification
- Provide log for issue close API call as well

@SrujanMungara

**Comment by SrujanMungara** [comment]
@Rishabh-ondc 


issue.created_at and updated_at is already provided.

Please check. 

submitted below the log for information





{
  "context": {
    "action": "on_issue_status",
    "bap_id": "pp-ondc.dlyb.in",
    "bap_uri": "https://pp-ondc.dlyb.in/",
    "bpp_id": "gateway.cept.gov.in",
    "bpp_uri": "https://gateway.cept.gov.in/ondc/",
    "city": "std:080",
    "core_version": "1.0.0",
    "country": "IND",
    "domain": "nic2004:60232",
    "message_id": "ea221f98-6b10-4e44-ba8b-43a56dc21b80",
    "timestamp": "2023-12-15T16:36:08.754Z",
    "transaction_id": "f946259e-f5e9-4478-8b39-26b21cb09a15_6528ed3727b73d292cff697a"
  },
  "message": {
    "issue": {
      "created_at": "2023-12-15T16:34:33.225Z",
      "id": "514a261e-0408-4a91-a57b-54be1234e72d",
      "issue_actions": {
        "respondent_actions": [
          {
            "cascaded_level": 1,
            "respondent_action": "PROCESSING",
            "short_desc": "Complaint is being processed",
            "updated_at": "2023-12-15T16:34:34.485Z",
            "updated_by": {
              "contact": {
                "email": "satya@dailybee.in",
                "phone": "8310103202"
              },
              "org": {
                "name": "pp-ondc.dlyb.in::nic2004:52110"
              },
              "person": {
                "name": "Satya Teja"
              }
            }
          },
          {
            "cascaded_level": 2,
            "respondent_action": "CASCADED",
            "short_desc": "Complaint cascaded",
            "updated_at": "2023-12-15T16:34:34.566Z",
            "updated_by": {
              "contact": {
                "email": "satya@dailybee.in",
                "phone": "8310103202"
              },
              "org": {
                "name": "pp-ondc.dlyb.in::nic2004:60232"
              },
              "person": {
                "name": "Satya Teja"
              }
            }
          },
          {
            "cascaded_level": 2,
            "respondent_action": "PROCESSING",
            "short_desc": "Complaint is being processed",
            "updated_at": "2023-12-15T16:34:41.413Z",
            "updated_by": {
              "contact": {
                "email": "ondcgrievances@indiapost.gov.in",
                "phone": "18002666868"
              },
              "org": {
                "name": "gateway.cept.gov.in::nic2004:60232"
              },
              "person": {
                "name": "IndiaPost"
              }
            }
          }
        ]
      },
      "updated_at": "2023-12-15T16:34:41.413Z"
    }
  }
}

**Comment by Rishabh-ondc** [comment]
Mistagged the payload name. Please check on_issue_status_resolved.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@SrujanMungara
