### ISSUE TITLE
Vistar RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/verification-logs#1488]
on_receiver_recon.json :
 - "message.orderbook.orders" must contain at least 5 items
FAILED
receiver_recon.json :
 - "message.orderbook.orders[0].[provider.name.name](http://provider.name.name/)" is not allowed to be empty
 - "message.orderbook.orders[0].provider.name.code" is not allowed to be empty
 - "message.orderbook.orders[0].provider.address" is not allowed to be empty
 - "message.orderbook.orders[0].payment.@ondc/org/settlement_details[0].beneficiary_address" is required
 - "message.orderbook.orders[0].receiver_app_uri" is not allowed
 - "message.orderbook.orders" must contain at least 5 items

@Saifurrahmanemon

**Comment by Saifurrahmanemon** [comment]
@RupalSingla Please check the PR for the following issue - [PR](https://github.com/ONDC-Official/verification-logs/pull/1490)

**Comment by RupalSingla** [comment]
As per the requirement  Correction flow with 5 orders in orderbook are needed 

@Saifurrahmanemon

**Comment by Saifurrahmanemon** [comment]
@RupalSingla correction flow - [PR](https://github.com/ONDC-Official/verification-logs/pull/1506)
