### ISSUE TITLE
8quad IGM - compliance check

### ISSUE THREAD

**Issue by amitsinha07** [ONDC-Official/verification-logs#1695]
Comman issues

1. issue_status call is missing 
2. on_issue _status call is missing
[NOTE: Please submit all payload in json file not in txt"]

FLOW 1

- **Issue Errors**:
  - `/message/issue/complainant_info/contact/phone` must not have more than 11 characters.
  - `/message/issue/complainant_info/contact/email` must be a string.
  - `/message/issue/source/type` must match one of the allowed values: `CONSUMER`, `SELLER`, or `INTERFACING-NP`.
  - The phone number in the `/issue` API is not within the valid range.

- **On Issue Errors**:
  - `/message/issue/issue_actions/respondent_actions/0/updated_by/contact/email` must be in a valid email format.
  
  @8QuadTech

**Comment by 8QuadTech** [comment]
Hi @amitsinha07 ,
1.) It is mentioned in Flow 1 that on_issue_status call can be unsolicitated.
![image](https://github.com/user-attachments/assets/59649341-1763-4e3a-bb92-67e038fc27d1)]
2.) There is an on_issue_status file in the folder. Is any other on_issue_status file required apart form this?

**Comment by amitsinha07** [comment]
Hii @8QuadTech 
Yes on_issue_status call can be unsoliciated but you also have to submit on_issue_status soliciated. Please take reference from other NP's logs fro IGM

**Comment by amitsinha07** [comment]
issue_close 
      - "schemaErr3": "/message/issue/rating must be equal to one of the allowed values (THUMBS-UP,THUMBS-DOWN)"
      
 @8QuadTech

**Comment by RupalSingla** [comment]
@8QuadTech  Log approved
