### ISSUE TITLE
GOFRUGAL - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#244]
Retail Logs:
1. /search - isn't compliant with API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)
2. /on_search - transaction_id & message_id should be the same as the corresponding values in /search;
3. /on_search - time.schedule.frequency of 2 hrs means the store accepts orders for 2 hours every day of week?
4. /on_select - remove all keys with null values
5. /on_init - payment withholding amount is not as per contract;; settlement details should be sent as per contract;
6. /on_confirm - order state is "Created" (means not auto-accept?). Also Provider.descriptor.name & code are not as per contract. Fulfillment state code should be set to the base state of "Pending";
7. /on_status - fulfillment state descriptor code is invalid; why is the order value different from what's in /confirm? Why is order state still "Created"?
8. No support & update APIs?

**Comment by BLR-0118** [comment]
Logistics logs:
1. /search - following are not part of contract - tags (ready to ship), payment (withholding amount). Also, what does weight of 0 gram mean?
2. /init - tags (ready to ship), fulfillment not part of contract; also, why is provider location id null?
3. /update - why so many null keys?

**Comment by BLR-0118** [comment]
@SherinShafa27

**Comment by BLR-0118** [comment]
Retail logs:
1. /on_search - 
a. can't have the same timestamp as /search (same in /on_init & /init , /on_track & /track also);
b. circle.radius.value should be string as per API contract;
c. Kit Kat is packaged food, hence category_id should be "Packaged Foods" and the appropriate struct should be filled up;
2. /on_select - what's the purpose of providing all these extra keys?
3. /on_init - what's the purpose of having all these control characters in the address? This will create a problem with signature verification (if this is only in the logs, then OK);
4. /on_confirm - withholding amount is string;
5. /on_track - 
a. fulfillment tracking is false in /on_confirm, why is status active here?
b. url should be an actual tracking url that can be rendered by a buyer app, not an UUID;
6. /on_status -
a. timestamp is earlier than /status?
@SherinShafa27 - let's have a call on Monday to go thru some of these issues?

**Comment by BLR-0118** [comment]
Also:
7. /on_update (also applies to /on_select & other APIs having a quote) - 
a. valid title types are Delivery Charge, RTO Charge, Reverse QC Charge, Tax (in swagger spec);
b. also add the item id for reverse QC, etc.

**Comment by BLR-0118** [comment]
Logistics logs:
1. /search - 
a. collection amount only required for CoD payments;
b. what's the purpose of having extra keys for payment, ready to ship?
2. /confirm - quote.price shows 66 but payment.params.price shows 568. Why?
3. /update - not compliant with API contract (this should be used only to set "ready to ship" or any change in weight or dimensions due to return / cancel of retail order;
4. No status API?
@SherinShafa27

**Comment by akil4n** [comment]
@BLR-0118 , for this 
`/on_init - what's the purpose of having all these control characters in the address? This will create a problem with signature verification (if this is only in the logs, then OK);`

supriyo, checked this. the buyer app is sending this in the billing address this has to be fixed by Buyerapp. your comments on this

**Comment by BLR-0118** [comment]
@akil4n checked this & you're right. Will have it rectified.

**Comment by akil4n** [comment]
@BLR-0118 Supriyo, `"count"` field needs to be `number` or `string` ?. in current prod n-1 we are using it as number. but in contract i can see its mentioned as `"string"` and some places referred as `"number"`
![image](https://user-images.githubusercontent.com/53361563/202361623-459bb25d-10c0-4ff0-a1f2-5d073d80d8b1.png)

**Comment by BLR-0118** [comment]
for now, let's follow this. will fix in the next revision of the contract.
@akil4n

**Comment by SherinShafa27** [comment]
@BLR-0118 Retail logs
 Fixed 1.a,b .c as we discussed sending as grocery as of now
2.Fixed
3.Buyer app should handle it
4.Fixed
5.We will throw NACK for track for selfship orders
6.As discussed,its unsolicited callbacks
7.fixed

**Comment by SherinShafa27** [comment]
@BLR-0118 for logistics logs fixed as per the comments. cc : @akil4n

**Comment by BLR-0118** [comment]
Retail Logs:
1. /on_select, /on_init, /on_confirm - tax should be at line item level;

**Comment by BLR-0118** [comment]
@akil4n

**Comment by SherinShafa27** [comment]
fixed and updated logs @BLR-0118

**Comment by BLR-0118** [comment]
Can you pls enable the same change (tax at line item level) in /on_status & /on_update as well? No need to resubmit logs. Pls let me know when done
@SherinShafa27 @akil4n

**Comment by akil4n** [comment]
@BLR-0118 fixed this tax at item level for on_update and on_status callbacks
