### ISSUE TITLE
Delhivery - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#285]
Logs with nstore:
1. /on_search:
- timestamp format is wrong in all APIs;
- timestamp doesn't seem to be UTC;
- short_desc & long_desc is required for provider, item;
2. /on_init:
- payment params such as withholding amount, return window, finder fee, etc not applicable for logistics; applies to other APIs such as on_status as well;
3. on_track:
- on_confirm doesn't specify tracking attr so how to find out if order is trackable or not?

**Comment by BLR-0118** [comment]
@utkarsh-v

**Comment by utkarsh-v** [comment]
1. Timstamp format has been fixed in all apis.
2. short/long des added in on_search.
3. extras keys removed from on_init,on_status etc.
4. tracking attr added in on_confirm.

@BLR-0118 Resolved all your points kindly review again and provide your approval.
   PR: https://github.com/ONDC-Official/verification-logs/pull/286

**Comment by BLR-0118** [comment]
Logs with nstore:
1. /on_search - short_desc, long_desc reqd for bpp/providers.descriptor;
2. /on_confirm - provider.locations.id is reqd; items.descriptor is not reqd here; 
3. /on_status - seems like ready_to_ship (rts) not yet triggered. If so, how can fulfillment start time be provided (check 4 below)?
4. /on_update - if rts triggered, fulfillment state should change from "Pending";
@utkarsh-v

**Comment by utkarsh-v** [comment]
We have fixed and updated the logs for points 1,3,4.

For 2nd point, as per logistic contract "provider.locations.id" is mandatory only if shipment needs to be dropped at logistic location but we are not supporting this ..we will pick the shipment from pickup location. that's why we are not sending this in on_search as well.

@BLR-0118  Please review.

**Comment by BLR-0118** [comment]
1. /on_search & /on_update - how is the context timestamp before timestamp for /search & /update?
2. /on_status_rto - 
a. how is city "*" here but there's an actual city code for /on_status?
b. fulfillment state code of "Order-is-cancelled" is invalid;
c. following keys are invalid: "payments", "@ondc/org/ondc-withholding_amount", "@ondc/org/ondc-return_window", "@ondc/org/buyer_app_finder_fee_amount", "@ondc/org/ondc-settlement_window", "@ondc/org/buyer_app_finder_fee_type",;
3.

**Comment by BLR-0118** [comment]
@utkarsh-v

**Comment by utkarsh-v** [comment]
Here is the response:
1. Might be diff request/response..update the correct logs.
2. changed "Order-is-cancelled" to cancelled and city thing also updated with logs.

@BLR-0118 please review.

**Comment by BLR-0118** [comment]
Logs with nStore:
1. /on_cancel - fulfillments.type of "Pre-paid" is invalid (should be "Prepaid");
2. /on_status_rto - check how payments & settlement details can be filled up [here](https://docs.google.com/document/d/1X4VyBAGc02tHgyPnqAIH5JW5BvCeHgoCOU6mGPi52iU/edit)
3. /on_update -fulfillments.type - same issue as 1;

**Comment by BLR-0118** [comment]
@utkarsh-v

**Comment by utkarsh-v** [comment]
1st and 3rd are fixed and updated the logs. for 2nd point, we have added the keys but sellers needs to implement this as well.

@BLR-0118 please review and provide your approval.

**Comment by shivbpandey** [comment]
@BLR-0118 - kindly review it.

**Comment by BLR-0118** [comment]
1. Every request seems to be getting a response in exactly 2 secs (check timestamp diff between search & on_search, init & on_init, confirm & on_confirm). This can't be correct. Pls ensure the current system timestamp is provided for your response;
2. /on_init - how did payment status change to paid? Also, invalid key - "@ondc/org/ondc-settlement_window";
3. /on_confirm - invalid keys:
a. payment.created_at/updated_at
b. settlement_details.(bank_name, branch_name, beneficiary_name)
4. /on_cancel - why is reason code 005 triggering an RTO flow? (since AWB # is being provided)
5. /on_status - what is the status change being shown here (since all states are same as in confirm)
6. /on_status_rto - RTO will be triggered through /on_cancel (if the appropriate reason code is entered), not thru on_status;

**Comment by BLR-0118** [comment]
@utkarsh-v @shivbpandey

**Comment by utkarsh-v** [comment]
@BLR-0118 Below are the reply

1. We are using system timestamp this might be because we replayed previous events for testing.
2. payment.status is order payment status right? it will be paid for prepaid order if seller is initiating request after they got the order in their system.
3. payment.created_at/updated_at will remove and share the logs but for settlement_details.(bank_name, branch_name, beneficiary_name) We have added as per [doc](https://docs.google.com/document/d/1X4VyBAGc02tHgyPnqAIH5JW5BvCeHgoCOU6mGPi52iU/edit) shared by you in previous comments
4. It's not triggering RTO Flow we just cancelled the order as order was not picked up.
5. Yeah, It's after the confirm if they check via status via.
6. We are triggering via on_cancel. on_status_rto file is just to share logs for RTO shipment real time updates.
7. will add and share the logs as we can see this is new requirement as well.

**Comment by BLR-0118** [comment]
1. needs to be fixed;
2. prepaid payment will be in buyer app before /confirm. Why is this in on_init?
3. Ok, this was for retail enabling..will need to add for logistics (will get back);
4. why is awb# provided then?
5. So, no status change shown in this /on_status?
6. How will this be different from /on_status?
7. a. Understanding from different logistics providers is that shipping label is generated by merchant & attached to package and then sent to logistics buyer for scanning during pickup. Can you pls confirm what Delhivery does?
b. I think this is the full shipping label. Pls confirm what Delihivery scans?
c. base64 encoded image may be heavy, what about an image url?

**Comment by BLR-0118** [comment]
@utkarsh-v

**Comment by BLR-0118** [comment]
I was hearing from one of the participants that Delhivery search response comes back after 8-9 secs. Can you pls verify this?
@utkarsh-v

**Comment by utkarsh-v** [comment]
1. Logs Added https://github.com/ONDC-Official/verification-logs/pull/330.
2. some of the seller searching for logistic once they received the order in their system.for those cases buyer has already done the payment. seller is just creating/searching order for logistic after they sent retail on_confirm.
3. Ok
4. Ok will send only in-case of RTO started (Logs Added) https://github.com/ONDC-Official/verification-logs/pull/330
5. In that particular scenario yes.
6. yes it is same. we just shared logs with you to verify from your side if shipment starts RTO then additional RTO fields in on_status are fine or not.
7. a)Yeah same process we are following. We will share the shipping label along with other fields in on_update once they send ready_to_ship flag yes. c) Ok we will send pdf download link (Will add logs by tmrw)
8. We are using our internal apis and in staging it might have taken time, will be fine in prod env( 2-3 sec ). attached SLA for prod internal apis
![image](https://user-images.githubusercontent.com/96607351/203320041-df65aff3-4d04-4da2-80c1-a20185df41b5.png)
![image](https://user-images.githubusercontent.com/96607351/203319950-a31847a3-989c-460c-9d82-d53a3ce217e1.png)


@BLR-0118 please review.

FYI @Anilkumar8 @shivbpandey

**Comment by utkarsh-v** [comment]
We have added logs for 7th point (Shipping label logs).https://github.com/ONDC-Official/verification-logs/pull/334/files

@BLR-0118 Please review

**Comment by utkarsh-v** [comment]
@BLR-0118 please review.

**Comment by BLR-0118** [comment]
1. /on_init - payment.collected_by was "BAP" in /init, not seen here?
2. Check if 1 above is in /on_status?

**Comment by BLR-0118** [comment]
@utkarsh-v

**Comment by utkarsh-v** [comment]
@BLR-0118 Please review: https://github.com/ONDC-Official/verification-logs/pull/346

**Comment by SashankYalluri3** [comment]
@BLR-0118  - Please review

**Comment by BLR-0118** [comment]
1. Timestamp for request/response as noted from the logs:
a. /search - 05:14:37.810Z, /on_search - 05:14:43.529Z
b. /init - 05:15:34.604Z, /on_init - 05:15:35.832Z
c. /confirm - 05:15:37.336Z, /on_confirm - 05:15:41.813Z

- Check the timestamps for /on_search, /on_init, /on_confirm - how's this possible?
- Why is confirm response taking 4+ secs?

**Comment by BLR-0118** [comment]
@utkarsh-v @SashankYalluri3

**Comment by BLR-0118** [comment]
tech logs are approved

**Comment by shivbpandey** [comment]
+CS Prabhakar ***@***.***>
Thanks
Shiv
"Innovate, Lead and Set Examples"
