### ISSUE TITLE
Shopalyst - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#302]
1. /on_search - Context.timestamp same as in /search. Also applies to all other callbacks;
2. /on_select - following keys in quote.breakup.item aren't in the contract:
                            "@ondc/org/returnable": false,
                            "@ondc/org/cancellable": false,
                            "@ondc/org/available_on_cod": false
 What's the purpose of including these keys?
3. /on_select - fulfillment category of "3 day delivery" is not in spec;
4.  /on_init - why is seller app inserting this:
                "type": "ON-ORDER",
                "collected_by": "BAP",
                "@ondc/org/collected_by_status": "Agree",
5. /on_confirm - why is seller app inserting this:
                "type": "ON-ORDER",
                "status": "PAID",
No mention of collected_by in this case?
6. /on_track - when fulfillment tracking is false, why is tracking status active?
7. /on_support - message is empty. It needs to return contact details as per API contract;
8. No cancel / update APIs?

**Comment by BLR-0118** [comment]
@kishorgandham

**Comment by kishorgandham** [comment]
Fixed implemented and new logs added via https://github.com/ONDC-Official/verification-logs/pull/313

@BLR-0118

**Comment by BLR-0118** [comment]
Logs with wowskinscience:
1. /on_status - shows collected_by but /on_init & /on_confirm doesn't. why?
2. /on_status - finder fee type & amount is blank?
Request if you can resubmit logs for only the above with a buyer app from Plotch / Mystore / Airpay

**Comment by BLR-0118** [comment]
@kishorgandham

**Comment by kishorgandham** [comment]
@BLR-0118 please review updated logs in this pull request https://github.com/ONDC-Official/verification-logs/pull/336
As per your feedback, we tested with mystore instead of the reference buyer app

**Comment by BLR-0118** [comment]
Log - jajee with mystore:
1. Item id in /select is not in /on_search making it difficult to correlate.
Can you pls share 1 complete end-to-end flow log with buyer app from pre-prod?

**Comment by BLR-0118** [comment]
@kishorgandham

**Comment by kishorgandham** [comment]
@BLR-0118 I re-testes and submitted the logs here https://github.com/ONDC-Official/verification-logs/pull/342

**Comment by BLR-0118** [comment]
Logs with mystore:
1. /on_search - some of the items don't have category_id. Why?
Logs with Kotak:
1. /on_cancel - should have the same cancellation_reason_id as /cancel;
No /support, /update APIs?

**Comment by BLR-0118** [comment]
@kishorgandham

**Comment by kishorgandham** [comment]
@BLR-0118 missing category id is with bad data in our system. 
We re-tested the flow with Sleepyowl seller and airpay/reference buyer apps
https://github.com/ONDC-Official/verification-logs/pull/344
Please review

**Comment by BLR-0118** [comment]
1. No track, update APIs? (even though tracking was true in /on_confirm and returns through update APIs will happen in case for faulty / expired products even though they may be non-returnable);
2. Pls also check your compliance with the checklist [here](https://github.com/ONDC-Official/verification-logs/blob/main/Compliance%20Checklist%20for%20Prod.md)

**Comment by BLR-0118** [comment]
@kishorgandham

**Comment by kishorgandham** [comment]
@BLR-0118 kindly review 
https://github.com/ONDC-Official/verification-logs/pull/363
Order flow (till delivery), partial cancellation and full order cancellation are tested separately with different buyer apps and checked into different folders.

**Comment by BLR-0118** [comment]
logs verified & closed
