### ISSUE TITLE
Ushop - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#307]
1. /on_search - category_id should be "Packaged Commodities" or from this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
2. /on_select -
a. how is timestamp less than /select?
b. fulfillment tat of 4d isn't for "Immediate Delivery". Use "Standard Delivery" instead;
3. fulfillment.tracking is false in /on_init but true in /on_confirm. Why? Typically, this will be true only for "Immediate Delivery" orders;
4. /on_confirm - no order state or fulfillment state?
5. /on_cancel - cancelled_by is not in API contract;
6. /on_status - 
a. fulfillment state is invalid. Pls check /on_status in API contract for valid fulfillment state codes;
b. order state of "Created" doesn't match fulfillment state of delivered;
7. /on_track - status of active means url has to be provided;
8. /on_update - return status & updated quote should be provided;

**Comment by BLR-0118** [comment]
@shri5445

**Comment by ensservices** [comment]
Hello @BLR-0118 
I have Submitted logs links: https://github.com/ONDC-Official/verification-logs/pull/318 please check

**Comment by BLR-0118** [comment]
1. /on_search - items.symbol is required;
2. Since the logs aren't for an end-to-end flow as each request/response seems independent (e.g. search/on_search is returning catalog items which aren't in select/on_select, etc.), it's very difficult to correlate. Pls submit logs for end-to-end flow.

**Comment by BLR-0118** [comment]
@shri5445

**Comment by ensservices** [comment]
@BLR-0118 
I have submitted the logs link https://github.com/ONDC-Official/verification-logs/pull/326 plz check

**Comment by BLR-0118** [comment]
1. /on_select - 
a. how's the /select & /on_select timestamp earlier than /search & /on_search?
b. all "value" should be string (also applies to /on_init, /on_confirm);
2. /on_confirm - how's the timestamp earlier than /confirm?
3. /on_status - 
a. timestamp can't be earlier than /status;
b. items.fulfillment_id can't be null;
c. withholding_amount & return_window should be string;
4. /on_support - timestamp can't be earlier than /support;
5. /on_track timestamp is 5 days after /track;
6. /on_cancel - timestamp can't be earlier than /cancel;
7. /on_update - timestamp can't be earlier than /update;

**Comment by BLR-0118** [comment]
@shri5445

**Comment by ensservices** [comment]
@BLR-0118 
I have submitted the logs plz review the link https://github.com/ONDC-Official/verification-logs/pull/337

**Comment by BLR-0118** [comment]
1. /init & /on_init have same timestamp;
2. /on_status - fulfillments type "Completed" is not valid;

**Comment by BLR-0118** [comment]
@ensservices @shri5445

**Comment by ensservices** [comment]
@BLR-0118 
https://github.com/ONDC-Official/verification-logs/pull/339
please review

**Comment by BLR-0118** [comment]
1. /on_status - fulfillment state of "Serviceable" is not valid. You need to use a post-order fulfillment state.

**Comment by BLR-0118** [comment]
@ensservices @shri5445

**Comment by shri5445** [comment]
@BLR-0118  I have submitted status logs. please review the link https://github.com/ONDC-Official/verification-logs/pull/345

**Comment by BLR-0118** [comment]
1. Discrepancy between order state & fulfillment state. Fulfillment state of order delivered doesn't match order state of accepted;
2. Pls document your compliance with this [checklist](https://github.com/ONDC-Official/verification-logs/blob/main/Compliance%20Checklist%20for%20Prod.md)

**Comment by BLR-0118** [comment]
@shri5445

**Comment by shri5445** [comment]
@BLR-0118 I have submitted the status log. please review the link https://github.com/ONDC-Official/verification-logs/pull/352

**Comment by BLR-0118** [comment]
1. /on_status - if payment type is POST-FULFILLMENT (i.e. COD), shouldn't the status be PAID and the associated payment txn id provided if order is delivered?

**Comment by BLR-0118** [comment]
@shri5445

**Comment by ensservices** [comment]
@BLR-0118 status logs. please review this link https://github.com/ONDC-Official/verification-logs/pull/358

**Comment by BLR-0118** [comment]
logs verified & cleared
