### ISSUE TITLE
VLCC - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#331]
1. /on_search - 
a. items.symbol is required;
b. how to interpret fulfillment_id of "1". Static values are reqd as shown in API contract;
2. /on_select -
a. all "value" should be string;
b. item & fulfillment link is missing (fulfillment_id in items);
c. what's the purpose of quantity & price in items?
3. /on_init -
a. payment block is invalid:
        "payment": {
          "type": "ON-ORDER",
          "@ondc/org/buyer_app_finder_fee_type": "Percent",
          "@ondc/org/buyer_app_finder_fee_amount": 0,
          "@ondc/org/withholding_amount": 0,
          "@ondc/org/return_window": 0,
- why is collected_by "BAP" & type "ON-ORDER" (i.e. prepaid collection by BAP) being proposed by sellerapp here?
- why is buyer app finder fee 0?
- buyer app finder fee amount & withholding amt are string;
4. /on_confirm -
a. No default fulfillment state?
b. same issues as in 2 a & b above;
5. /on_status -
a. fulfillment type & state are invalid;
6. No /cancel, /update APIs?

**Comment by BLR-0118** [comment]
1. /on_search - for one of the items, value > maximum_value;
2. /on_init timestamp is earlier than /init. How?
3. /on_confirm - timestamp issue as 2; no default fulfillment state code;
4. /on_status - uses different order id from what was used in /confirm, difficult to verify;
5. /on_track - how can status be active without any URL?
6. /on_update - uses different order id from what was used in /confirm, difficult to verify;

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by BLR-0118** [comment]
1. /on_init:
- payment: finder fee amount can't be 0;
- payment type "ON-ORDER", collected_by "BAP" can't be proposed by BPP;
- in case of pre-paid payment collection by BAP, you should just return the settlement details in /on_confirm;
2. /on_confirm - why is the timestamp difference between /on_confirm & /confirm almost 5 secs?
3. /on_cancel timestamp is earlier than /cancel. Why?
4. /on_status - invalid fulfillment state code;
5. why do confirm, support, status & the corresponding callbacks have same message id?
6. /on_update - not clear how refund amount could be 350 when the entire item worth 650 is being returned.

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by BLR-0118** [comment]
1. /on_search -
- some items have fulfillment_id "1" & others "Fulfillment1". How to interprete this?
2. /on_select -
- quote has same item id as in /select but items.id is something different. What does this mean?
3. /on_init -
- provider.locations.id in /init is different from provider_location.id here. Why?
4. /on_confirm -
- payment.status - enums aren't case insensitive. Pls use values as per spec;
- provider.locations.id is different from what's in /on_init and different from /confirm;
5. /update is for return but /on_update is for cancel and /on_status shows return approved. How?

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls check the vlcc logs https://github.com/ONDC-Official/verification-logs/pull/391

**Comment by BLR-0118** [comment]
1. /on_select -
- breakup for delivery charges should have item id same as fulfillment id;
- also set fulfillment.state.descriptor.code to same value as name;
2. /on_init -
- Context.timestamp is earlier than that for /init??
- why is payment.collected_by="BAP" being proposed here when it's not in /init?
3. /confirm and /on_confirm - how is Context.timestamp for /confirm earlier than for /init?
4. /on_update - 
- order id has a space in /update & /on_update and is invalid. How does it match with the order created earlier?
- updated order value is 650 but original order value was 479. How??

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls review the VLCC Logs: https://github.com/ONDC-Official/verification-logs/pull/398

**Comment by BLR-0118** [comment]
1. /on_search - what does fulfilment_id "1" mean?
2. /on_init - 
- provider_location.id is wrong;
- why is seller app proposing payment.collected_by "BAP" and payment.type "ON-ORDER" for BAP?
3. /on_update -
- return approved but the order quote hasn't changed. Means no refund to buyer? Why does /update show a refund in the settlement trail then?
4. /on_status -
- timestamp is "2022-12-27T11:19:59.459Z" which is before timestamp for /on_update at "2022-12-27T11:20:45.345Z"
- Yet, /on_status shows return approved status for item. How?

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls review logs PR Link:   https://github.com/ONDC-Official/verification-logs/pull/417

**Comment by BLR-0118** [comment]
1. /on_search:
- fulfillment_id "1" needs to be linked to a type (see bpp/fulfillments in /on_search in the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit))
2. /on_init:
- payment.collected_by should be "BPP" if seller app is doing prepaid collection;
- quote should have item_id for fulfillment charges (check revision 1.0.24 in API contract);
- if the buyer selected COD payment, why is the seller app overriding it?
3. /on_confirm:
- Context.timestamp is invalid;
- how did the payment type & collected_by change between /on_init & /on_confirm?
- quote should have item_id for fulfillment charges (check revision 1.0.24 in API contract);
- no default fulfillment state;
4. /on_status:
- order state of completed doesn't match fulfillment state of pending;
- order.fulfillment_id is invalid key;
- if order is completed, why is payment status not paid?

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls review the logs https://github.com/ONDC-Official/verification-logs/pull/421

**Comment by BLR-0118** [comment]
1. /on_init:
- items.returnable & cancellable are not valid here as per API contract;
- some of the keys in billing are invalid;
- some of the keys in fulfillment.end.location are invalid;
2. /on_confirm:
- several keys in payment.params should actually be in payment;
- this should be exactly as per API contract;
3. /on_update:
- should have updated quote as per API contract

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls review VLCC logs : https://github.com/ONDC-Official/verification-logs/pull/423

**Comment by bluecypher** [comment]
/on_init 
provider_location is an invalid key
Payment.settlement_window can't change in on_init
settlement_counterparty should be buyer-app

/on_confirm
Default Fulfillment state should be present in /on_confirm 
Payment type and collected_by do not match in /on_confirm and /on_init 

/cancel
Message Id cannot be same for /confirm and /cancel

/status
Message Id cannot be same for /status and /confirm


@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  pls review the VLCC logs PR link: https://github.com/ONDC-Official/verification-logs/pull/439

**Comment by bluecypher** [comment]
/on_init
items.quantity count should be integer

/on_confirm
payment.status can't be "PAID" when payment type is POST-FULFILLMENT

/update
Item is returned when the order is still in "Accepted" state

/on_update
Order.state is missing
quote.price.value is a mandatory key

@HarishMaurya6393

**Comment by bluecypher** [comment]
context.timestamp should be in valid UTC date-time format

/on_select
Timestamp should be in date-time format
Transaction Id and Message Id mismatches in /select and /on_select

/on_init
items[].quantity count should be integer

/on_status
Fulfillment id can't change in /on_status
Fulfillments state can't be "pending" when order state is "completed".

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
hello @BLR-0118  we have submitted VLCC logs pls review PR link: https://github.com/ONDC-Official/verification-logs/pull/446

**Comment by bluecypher** [comment]
/on_update

items[].id should be of type string.
order.quote is not as per the API contract.

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
hello @BLR-0118 we have submitted VLCC logs pls review PR link: https://github.com/ONDC-Official/verification-logs/pull/447

**Comment by bluecypher** [comment]
/on_update
order.quote object is not as per the API contract. 

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  we ahve submitted vlcc logs PR links https://github.com/ONDC-Official/verification-logs/pull/448

**Comment by BLR-0118** [comment]
Log review:
1. /on_select - quote should include both total & unit price per item (same should be followed for /on_init, /on_confirm);
2. /on_status with timestamp "2023-01-27T05:34:45.477Z" shows order state as completed but /on_cancel is able to cancel the order at "2023-01-27T05:39:35.022Z". How's this possible?
3. /on_update with timestamp "2023-01-27T05:34:09.239Z" shows return approved and updated order value as 0 (means entire amount refunded). Why is /on_status with a later timestamp showing the original order value of 520?

**Comment by BLR-0118** [comment]
@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
hello @BLR-0118  pls review VLCC logs https://github.com/ONDC-Official/verification-logs/pull/465

**Comment by bluecypher** [comment]
/search
GPS Lat/Long Precision should be same 

/select
fulfillments GPS Lat/Long Precision should be same 

/init
items[0].fulfillment_id is missing
fulfillments[].id is missing

/on_init
'fulfillment_id' is a required property in items[0]
fulfillments[].id is missing in /on_init
settlement_details of buyer app should be present in payment object in case of POST-FULFILLMENT 

/confirm
items[0].fulfillment_id mismatches for Item 39967064293455 in /on_select and /confirm
fulfillments[0].id is missing in /confirm
payment.params.transaction_id is generated when status is 'PAID'

/on_confirm
'fulfillment_id' is a required property in items[0]
'@ondc/org/settlement_details' is a required property in payment object
items[0].fulfillment_id is missing
fulfillments[0] start and end locations are mandatory

/cancel
cancel can't be called after item is delivered

/update
payment settlement_amount is incorrect.

/on_update
fulfillments state should be "Order-delivered" when order state is "Completed"

/on_status
state can't revert to "Accepted" after order is returned in on_update

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118   and @SandeepGF  search ,select, init not proper work from buyer app side how can i tested it proper and plz suggest me  another buyer app

**Comment by HarishMaurya6393** [comment]
Hello @BLR-0118 and @SandeepGF  we have submitted logs plz review PR links:: https://github.com/ONDC-Official/verification-logs/pull/480

**Comment by bluecypher** [comment]
/on_select
Pre-order fulfillment state code should be used in fulfillments[].state.descriptor.code

/init
items[0].fulfillment_id mismatches for Item 39967064293455 (items[].fulfillment_id) in /on_select and /init
fulfillments[].id is missing in /init
payment object is not as per the API contract

/on_init
'ttl' is a required property in $.quote
fulfillments[].id is missing in /on_init
Provider Id for fulfillments[] should be the bpp_id as per the contract
Quote object mismatches in /on_select and /on_init

/confirm
fulfillments[0].id is missing in /confirm
payment object is not as per the API contract

/on_confirm
fulfillments[0] start and end locations are mandatory

/on_status
fulfillments[0] start and end locations are mandatory
'fulfillment_id' is a required property in $.items[0]
'ON-ORDER' was expected in $.payment.type

/on_update
item can't be returned when it is still pending for fulfillment

Logs for all the Order's and fulfillment's states should be provided. 

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118 @SandeepGF  we have submitted VLCC logs plz review https://github.com/ONDC-Official/verification-logs/pull/491

**Comment by bluecypher** [comment]
logs must comply to v1.1.0 with the test case scenarios as documented
https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit

/on_search
serviceability construct to be defined
store timings to be provided
provider enable/diable label should be provided
category_id should be one of the non-deprecated

/on_select
fulfillments[].state code should be "Pending"

/init
fulfillments[0].id is missing in /init

/on_init
item.quantity is not required in quote.breakup
settlement_counterparty is expected to be 'seller-app' in @ondc/org/settlement_details

/confirm
fulfillments[0].id is missing in /confirm
payment.status should be "PAID" in case of pre-paid order(ON-ORDER)
payment.type is expected to be ON-ORDER
payment.collected_by is expected to be BAP
payment.uri is mandatory in /confirm
payment.tl_method is mandatory in /confirm
order created and updated timestamps are mandatory in /confirm
Quote Objects in /on_select and /confirm do not match

/on_confirm
order.state can't be completed in /on_confirm
end.time range is missing
Quote Object in /on_select and /on_confirm do not match
order created and updated timestamps are mandatory in /on_confirm

/update
item can't be returned in accepted state

/on_status
order state and fulfillment state are not as per the API contract 
'ON-ORDER' was expected in $.payment.type
payment settlement details missing in /on_status
@ondc/org/item_quantity count in quote breakup should be integer 
end time range is missing in fulfillments.

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
@BLR-0118  plz review Vlcc logs PR link: https://github.com/ONDC-Official/verification-logs/pull/522

**Comment by bluecypher** [comment]
@HarishMaurya6393 
Pls submit the logs as per the test case scenario document shared above.

**Comment by HarishMaurya6393** [comment]
@BLR-0118 plz review vlcc logs PR Link: https://github.com/ONDC-Official/verification-logs/pull/600

**Comment by HarishMaurya6393** [comment]
Hi @BLR-0118  pls check VLCC logs https://github.com/ONDC-Official/verification-logs/pull/638

**Comment by bluecypher** [comment]
## Flow 1

**/on_status (Accepted)**

- order.updated_at should be updated when order state is changing

**/on_status**

- order.updated_at should be updated when order is delivered (delivery time and updated_at should match)

**/update call is missing**

**/on_update (liquidated)**

- /fulfillments/start/time/timestamp (pickup time) can't change

## Flow 2

- similar issues as Flow 1

**/on_cancel**

- invalid schema of the payload

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

## Flow 5

- cancellation from buyer side is missing



@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
Hi @BLR-0118 pls check VLCC Logs:- https://github.com/ONDC-Official/verification-logs/pull/711

**Comment by abhinavv245** [comment]
## Flow 1

- item with id: 44618325983530 in /select but not present in /on_search

**/on_status**
- Message Id for all unsolicited /on_status calls should be same (temporarily)
- order.updated_at timestamp should match context.timestamp
- delivery time (/fulfillments/end/time/timestamp) should be updated as per the context.timestamp via unsolicited /on_status API when fulfillment state changes to 'Order-delivered'
- updates about the return status should be sent via /on_update API calls


**/on_update**
- Message Id for all unsolicited /on_update calls should be same (temporarily)
- return needs to be initiated by the buyer first (/update call is missing)

**/on_update (liquidated)** 
- /fulfillments/start/time/timestamp (pickup time) can't change

## Flow 2

- similar issues as Flow 1

**/on_select (non-serviceable)**
- delivery line item should be removed from quote.breakup in case of non-serviceabilty

**/on_cancel**
- invalid schema of the payload (refer to /on_cancel payload in [API contract](https://docs.google.com/document/d/1fefHfMoYIouN-QJTDJFFZm46dqHmFvwY-6ICoISJcUY/edit#heading=h.yzl8pn3ixxec))

## Flow 3, Flow 4

- similar issues as Flow 1

## Flow 5

- similar issues as Flow 1
- cancellation flow from buyer side and subsequent /on_cancel from seller side are missing

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
Hi @BLR-0118  Pls review VLCC logs:- https://github.com/ONDC-Official/verification-logs/pull/724

**Comment by abhinavv245** [comment]
## Flow 1

**/on_status**

- order.updated_at timestamp should match context.timestamp
- delivery time (/fulfillments/end/time/timestamp) should be updated as per the context.timestamp when fulfillment state changes to 'Order-delivered'
- invalid attribute /order/status 


**/on_update (liquidated)**

- pickup time (/fulfillments/start/time/timestamp) cannot change in /on_update for fulfillment state 'Order-delivered'

## Flow 2

- similar issues as Flow 1

**/on_select (non-serviceable)**

- delivery line item should be removed from quote.breakup in case of non-serviceabilty

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

**/on_status**

- unsolicited /on_status call is missing when fulfillment state changes to 'Order-delivered'

**/on_update (approved)**

- pickup time (fulfillments/start/time/timestamp) and delivery time(fulfillments/end/time/timestamp) cannot be same for fulfillment state 'Order-delivered'

**/on_update (liquidated)**

- invalid schema of the payload 

## Flow 5

- similar issues as Flow 1

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
Hi @abhinavv245  we have submitted VLCC logs pls check https://github.com/ONDC-Official/verification-logs/pull/750

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- category in serviceability construct should be one of the category ids in bpp/providers/items/category_id (on_search payload will get heavy if you enlist all the categories sold by that provider, therefore should be removed)

**/on_update**

- delivery time (/fulfillments/end/time/timestamp) cannot change in /on-update for fulfillment id: cbd118f4-5d74-438b-a405-3a39055ca181
- ReverseQC and Liquidated states cannot be simultaneous for item with id:44618533962026

## Flow 2

- similar issues as Flow 1

**/on_select (non-serviceable)**

- delivery line item should be removed from quote.breakup in case of non-serviceabilty

**/on_cancel**

- pre-shipment cancellation code should be provided (please refer [cancellation codes](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit#))

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

**/on_status (completed)**

- order.updated_at and delivery time(/fulfillments/end/time/timestamp) should be updated as per context.timestamp for fulfillment state 'Order-delivered"

## Flow 5

- similar issues as Flow 1

**/cancel**

- context.action should be 'cancel'

**/on_cancel**
-  should have sent NACK as the /cancel payload was invalid
- timestamp difference between /cancel and /on_cancel should be less than 5 sec

@HarishMaurya6393

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- reverse geocoding of 13.0722683, 77.3231792 (bpp/providers/locations/gps) shows pin code of 562123 but here it's 122015. What's the reverse geocoding logic?

**/on_status (order-picked/completed)**

- invoice must be provided in /documents for fulfillment.state = "Order-picked-up" and thereafter

**/on_update**

- Message ID for all /on_update calls should be same (temporarily)

## Flow 2

- correct on_init, on_confirm payloads should be provided

**/on_select (non serviceable)**

- area code 845417 is non serviceable when serviceability construct is PAN India

##Flow 3, Flow 4, Flow 4

- similar issues as Flow 1

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
Hi @abhinavv245  VLCC logs Submitted PR link https://github.com/ONDC-Official/verification-logs/pull/794

**Comment by abhinavv245** [comment]
## Flow 2

**/on_search**

-  type should be '12' for PAN India in /bpp/providers/tags (serviceability construct) 

## Flow 3

**/on_status**

- invoice must be provided in /documents for fulfillment.state = "Order-picked-up" and thereafter

## Please check for similar issues in other flows as well

@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
Hi @BLR-0118 and @abhinavv245  we have submitted VLCC logs  pls review PR link :https://github.com/ONDC-Official/verification-logs/pull/806

**Comment by abhinavv245** [comment]
# Flow 2

**/on_cancel**

- cancellation_reason_id should be a valid cancellation id (unsolicited seller app initiated)

please resubmit logs for flow 2

@HarishMaurya6393

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- Is the geocoding of store location correct? Reverse geocoding shows different pincode
- EAN code is missing for type: 1 in /items/descriptor/code (It's an optional property, should be removed if not available)

**/confirm**

- How can buyer app send fulfillment time ranges for pickup and delivery which is exactly matching with /on_confirm?

**/on_confirm**

- How are pickup and delivery time ranges calculated? Both ranges are initially the same. Despite a 7-day TAT, the delivery range covers only 6 days. The ranges are further adjusted in the /on_status calls based on actual timestamps.

**/on_update (Liquidated)**

- /quote/breakup/1/price/value must be string

## Flow 2

- Why is the same fulfillments/id getting generated for every /on_select, even for different transactions? What happens in case of multiple fulfillments?

##
- ####  Similar issues should be resolved for other flows as well.
- #### Please clean up the folder and share only the revised logs.


@HarishMaurya6393

**Comment by HarishMaurya6393** [comment]
#Flow2

Fulfillment id is same for all the transactions and its offline and we can identify using the transactions is. In case of multiple fulfillment two different fulfillment id will be generated

**Comment by HarishMaurya6393** [comment]
Hi @BLR-0118  and @abhinavv245  we have submitted VLCC logs kindly check PR link here:- https://github.com/ONDC-Official/verification-logs/pull/835

**Comment by bluecypher** [comment]
**on_search**
- Inaccurate geocoding of store location (gps and address). Why is this issue not resolved yet?
- net_quantity_or_measure_of_commodity_in_pkg should contain quantity and uom
- item's short_desc and long_desc can't be empty

**on_confirm**
- pickup and delivery time should be realistic (should not take 7 days to deliver the product from Gurugram to Noida)

@HarishMaurya6393

**Comment by NJ-Nitank** [comment]
@bluecypher, We have submitted the logs again, Please review them once.

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- /message/catalog/bpp/providers/0/items/2 must have required property '@ondc/org/statutory_reqs_packaged_commodities'
- /message/catalog/bpp/providers/0/items/6 must have required property '@ondc/org/statutory_reqs_packaged_commodities'

**/on_confirm**

- store gps location /fulfillments[0]/start/location/gps can't change (should remain same as in /on_search)

**/on_status (Order-picked-up)**

- estimated time ranges should not change in /on_status
- Invoice should be provided in "documents" (instead of document)

**/on_status (Order-Delivered)**

- Invoice should be provided in "documents" (instead of document)
- email mismatches in /billing in /confirm and /on_status_delivered
- order/updated_at timestamp can't be earlier than the delivery time

**/on_update (Liquidated)**

- /quote must have required property 'ttl'
- /quote/breakup/0/price/value must be string


#### - All the issues are repeated
#### - Please rectify similar issues in other flows as well

@HarishMaurya6393 @ShippuYadav

**Comment by ShippuYadav** [comment]
@bluecypher Hi Sandeep, Please find the correct logs:

https://github.com/ONDC-Official/verification-logs/pull/869

**Comment by bluecypher** [comment]
How can buyer app send pickup and drop time ranges in /confirm which is exactly matching with /on_confirm?

@ShippuYadav

**Comment by ShippuYadav** [comment]
Hello @bluecypher, By mistake, I have submitted the wrong confirm log. Please find the correct one with this PR 
https://github.com/ONDC-Official/verification-logs/pull/883
Thanks.

**Comment by bluecypher** [comment]
@BLR-0118, the VLCC seller app logs (v1.1.0) seem fine. Pls proceed with your review.
