### ISSUE TITLE
Addble - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#343]
logs with mystore:
1. /on_search - 
a. images for bpp/descriptor, bpp/providers mandatory;
b. invalid value for key - "category_id": "Packaged";
2. timestamp of /select & /on_select, /init & /on_init, /confirm & /on_confirm same;
3. /on_select -
a. tax is at item level, item_id should be provided as per contract;
b. convenience charge is at fulfillment level, item_id should be same as fulfillment_id;
4. No APIs for /support, /update?

**Comment by BLR-0118** [comment]
Logs with Blowhorn:
1. /search - weight value is not string;
2. /init - value is invalid "@ondc/org/settlement_window": "PT2D" (should be "P2D");
3. /confirm - default order & fulfillment state to be provided;
4. APIs for /cancel, /status required;

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by yaikhomba** [comment]
@BLR-0118 - retail/status & retail/update are supported and were uploaded as part of testing with ref buyer & Delhivery. Please review
/suport - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Retail/support.json](url)
/on_support - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Retail/on_support.json](url)

/update - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Retail/update.json](url)
/on_update - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Retail/on_update.json](url)

**Comment by yaikhomba** [comment]
@BLR-0118 logistic/cancel & logistic/status are also supported. Please review below

/cancel - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Logistic/cancel.json](url)
/on_cancel - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Logistic/on_cancel.json](url)

/status - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Logistic/status.json](url)
/on_status - [https://github.com/ONDC-Official/verification-logs/blob/main/logs/Addble/RefBuyerApp_Addble_Delhivery/Logistic/on_status.json](url)

/status -

**Comment by BLR-0118** [comment]
1. /on_init - delivery charge has to come in /on_select itself;
2. /confirm - why is there a difference between quote.price and payment.params.amt?
3. No /on_support, /on_update, /on_track APIs?

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by yaikhomba** [comment]
@BLR-0118 - Please see below for your question 2)
`2. /confirm - why is there a difference between quote.price and payment.params.amt?`
Have retested and confirmed that this issue is not from our end. Mystore is not considering the complete quote sent in /on_select. Only "item" & "delivery" from quote breakup are considered.  

![image](https://user-images.githubusercontent.com/16014399/206874983-76f8ac0d-2d34-4ce8-bded-fd146add2dbb.png)

Here's the /on_select payload

`{
	"context": {
		"domain": "nic2004:52110",
		"country": "IND",
		"city": "std:080",
		"core_version": "1.0.0",
		"action": "on_select",
		"bap_id": "beta.mystore.in",
		"bap_uri": "https://beta.mystore.in/ondc/1.0/",
		"bpp_id": "preprod-ondc.addble.com",
		"bpp_uri": "https://preprod-ondc.addble.com",
		"transaction_id": "17936369-f29c-45e3-bfe3-605cef6daa0b",
		"message_id": "015c618c-80bf-4a13-b3d6-60155b65f476",
		"timestamp": "2022-12-10T20:40:42.782Z",
		"ttl": "PT30S"
	},
	"message": {
		"order": {
			"provider": {
				"id": "EOKJBqid0zecXCvyQBCR",
				"descriptor": {
					"name": "Syngentaa"
				},
				"locations": [
					{
						"id": "EOKJBqid0zecXCvyQBCR"
					}
				]
			},
			"items": [
				{
					"fulfillment_id": "bac457a3-36f3-4913-a8bf-186e137abc26",
					"id": "vcprTtA2z8GVno1w5RU1"
				}
			],
			"fulfillments": [
				{
					"id": "bac457a3-36f3-4913-a8bf-186e137abc26",
					"state": {
						"descriptor": {
							"name": "Serviceable"
						}
					},
					"provider_id": "Blowhorn",
					"@ondc/org/provider_name": "Blowhorn",
					"tracking": false,
					"@ondc/org/category": "Standard Delivery",
					"@ondc/org/TAT": "PT24H"
				}
			],
			"quote": {
				"price": {
					"currency": "INR",
					"value": "150.48"
				},
				"breakup": [
					{
						"@ondc/org/item_id": "vcprTtA2z8GVno1w5RU1",
						"@ondc/org/title_type": "tax",
						"title": "Tax",
						"price": {
							"currency": "INR",
							"value": "0"
						}
					},
					{
						"@ondc/org/item_id": "vcprTtA2z8GVno1w5RU1",
						"@ondc/org/item_quantity": {
							"count": 1
						},
						"@ondc/org/title_type": "item",
						"title": "CARROT Seeds",
						"price": {
							"currency": "INR",
							"value": "148"
						},
						"item": {
							"price": {
								"currency": "INR",
								"value": "148"
							}
						}
					},
					{
						"title": "Seller fee @ 1%",
						"@ondc/org/item_id": "bac457a3-36f3-4913-a8bf-186e137abc26",
						"@ondc/org/title_type": "convenience charge",
						"price": {
							"currency": "INR",
							"value": "1.48"
						}
					},
					{
						"title": "Delivery charges",
						"@ondc/org/title_type": "delivery",
						"price": {
							"currency": "INR",
							"value": "1.0"
						}
					}
				],
				"ttl": "P1D"
			}
		}
	}
}`

**Comment by BLR-0118** [comment]
Logs with Plotch:
1. /on_search -
- locations.address should be a proper address
- no serviceability construct?
2. /on_status -
- these keys for fulfillment state not required:
- 							"short_desc": "Pending",
							"long_desc": "Pending"
3. /on_track -
- how can there be an active tracking URL when fulfillments.tracking is false in /on_confirm?
4. /on_update -
- has extra keys such as rateable, payment struct which aren't required
5. No /on_cancel API?

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by BLR-0118** [comment]
1. Very hard to verify without the logs for complete end-to-end flow e.g. in this case, logs are available for /search & /on_search but not for select/init and is available for confirm;
2. Instead of having separate searches with/without serviceability, pls share logs of provider catalogs with serviceability enabled;

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by BLR-0118** [comment]
1. /on_search - proposed serviceability construct has been changed. Pls check & update;
2. /on_select - quote.price.value isn't matching the breakup prices due to differences in precision;
3. /on_status (with an earlier timestamp) than /update shows order state as accepted but /update shows as created. How?
4. /on_update - same issue as 2 above;

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by BLR-0118** [comment]
@yaikhomba due to a change in the serviceability construct, request you to incorporate in your logs & resubmit.

**Comment by BLR-0118** [comment]
1. /on_search - category "*" not supported for serviceability;

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by BLR-0118** [comment]
1. /on_search:
- serviceability: value for "unit" should be "country_code" instead of "country";
- also, support existing categories in value for "category" (for backward compatibility);
No need to resubmit logs, let me know when this is done.

**Comment by BLR-0118** [comment]
@yaikhomba

**Comment by BLR-0118** [comment]
logs verified & cleared
