### ISSUE TITLE
Snapdeal - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#349]
1. /on_search -
a. has same timestamp as /search;
b. bpp/fulfillments, categories not as per API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit#);
c. available & max count for quantity is per buyer, not the total inventory;
d. listed value isn't in API contract; also, can't be > maximum_value;
2. item id in /select is not in /on_search;
3. /on_init - 
a. order state is set to created in /confirm, not here;
b. how did the total order value quote.price change from 848 in /on_select to 2210 in /on_init?
5. /on_confirm -
a. fulfillment start time range is generally provided after ready to ship is triggered (i.e. fulfillment state moves beyond pending);
b. why is payment.params.amount showing 2213 when quote.price is 2210;
6. /on_status - 
a. fulfillment state - is for code, not name;
7. /on_status_postCancel shows quote.price as 0 which isn't correct;
8. No /update, /support APIs?

**Comment by BLR-0118** [comment]
@ShikharSD

**Comment by BLR-0118** [comment]
1. /on_search - 
- timestamp should be in UTC, following RFC3339 format (check timestamp of /search);
- Home & Decor parent category isn't Fashion; also, this may not be required and we haven't included in API contract:
          "categories": [
            {
              "id": "Home & Decor",
              "parent_category_id": "Fashion",
              "descriptor": {
                "code": "books-labelissue-nextlabel",
                "symbol": "https://n3.sdlcdn.com/imgs/a/b/c/sdtv/Logo.png",
                "images": [
                  "https://n3.sdlcdn.com/imgs/a/b/c/sdtv/Logo.png"
                ]
              }
            }
          ],
2. /on_select - 
- should also have fulfillment TAT;
- no taxes or delivery charges?
3. /on_init -
- should also have beneficiary name
4. not clear what's the difference between on_status and on_status_postcancel
5. No /support or /update APIs?

**Comment by BLR-0118** [comment]
@yashcraft

**Comment by yashcraft** [comment]
@BLR-0118
1.  the timestamp in /search is sent by mystore not us. Will remove parent category field
2. Will add the fulfillment TAT. Will check on taxes and delivery
3. /on_init who should be the beneficiary there?
4. Copy paste error, will add post_cancel status where there wont be any quote and fulfillment objects
5. Mystore does not make calls for /support or update so unable to test. we have those APIs implemented

**Comment by BLR-0118** [comment]
1. Your timestamp in /on_search & other callbacks is in the wrong format and also not in UTC (since there's almost 5 1/2 hr difference between your & mystore timestamps). Check the /search timestamp for the correct format.
Pls fix other issues & resubmit logs asap
@yashcraft

**Comment by BLR-0118** [comment]
1. /on_init -
- quote.price.value is different from /on_select and doesn't match summation of quote.breakup.price.value
2. /on_confirm -
- order.created_at and updated_at is very different from Context.timestamp
3. /on_status -
- timestamp format for created_at, updated_at, time.range.start and end are invalid (should be same format as Context.timestamp)
4. No APIs for /on_update, /on_support?

**Comment by BLR-0118** [comment]
@yashcraft

**Comment by BLR-0118** [comment]
1. /on_search - for bpp/descriptor, following keys are also reqd (as per API contract) - symbol, short_desc, long_desc, images;
2. /on_init - why is the seller app suggesting that "BAP" should collect payment? Suggest you remove the payment block from here. It is in /on_confirm and that will be ok;
3. /on_confirm - beneficiary_name key in payment block shouldn't be empty;
4. /on_status - start.location should also have gps and descriptor.images (as per API contract);

**Comment by BLR-0118** [comment]
@yashcraft

**Comment by BLR-0118** [comment]
logs cleared for Prod
