### ISSUE TITLE
NearShop - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#350]
1. Pls provide logs in the correct format, in the correct branch and with one of the buyer apps that will be in Production (ONDC buyer app logs will not be acceptable for compliance check);

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by BLR-0118** [comment]
1. /on_search -
- has same timestamp as /search
- several mandatory keys missing e.g. bpp/descriptor.short_desc
- FSSAI no is invalid
- category_id is invalid for the item
- what does item.fulfillment_id of "1" mean?
2. /on_select -
- price of item in catalog is different from what's shown in quote here
3. /on_init -
- payment struct is invalid
4. /on_confirm -
- price here is different from /on_init
- no fulfillment state?
5. /on_status -
- no fulfillment state
- document.url is empty
6. /on_track -
- what does active tracking url woth fulfillment.tracking of "false" in /on_confirm mean?
7. /on_cancel -
- payload not compliant with API contract
8. No /on_update, /on_support APIs?

In future, please submit logs using the exact process mentioned [here](https://github.com/ONDC-Official/verification-logs) otherwise won't be reviewed.

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by BLR-0118** [comment]
1. /on_search -
- provider location id doesn't match item location id. what does this mean?
- bpp/fulfillments has static values defined for fulfillments but the item.fulfillment_id doesn't match the fulfillment id here. what does this mean?
2. /on_select -
- fulfillment.id doesn't match item.fulfillment_id;
- catalog declared price has been broken up into item & tax components which is incorrect; tax components (if any) should be on top of the declared price;
- value precision should be cut so that the breakup prices add up to the total order value;
3. /on_init -
- quote breakup here is different from /on_select and doesn't match the declared price in /on_search;
4. /on_confirm -
- order id here is different from order id in /confirm;
- payload seems invalid as "state" key is duplicated;
- no order quote here??
5. /on_status - 
- payload is invalid as several mandatory keys like order quote missing;
6. /on_cancel -
- payload is invalid, action shows "search" and "on_search"??
7. No APIs for /update, /support?

**Comment by BLR-0118** [comment]
@RonitKumarSinha - pls submit logs in readable format in future.

**Comment by BLR-0118** [comment]
1. /on_search:
- item.exp is invalid key;
- what does this fulfillment id mean? ("fulfillment_id": "44f1a436-8eb8-5bb7-93e7-39e2324efcb7")
2. /on_select:
- item price shown in /on_search is broken into item & tax line items. This is not allowed as for this category, the item price shown in catalog is already tax inclusive;
3. /on_init:
- several invalid keys in payment struct;
4. /on_confirm:
- no default fulfillment state;
5. /on_cancel:
- order.state is duplicated;
6. /on_status: no fulfillment state;
7. /update & /on_update are using different order id making it difficult to verify.

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by BLR-0118** [comment]
1. /on_select:
- provider.locations is not valid as per API contract;
- provider_location is not valid as per API contract;
2. /init:
- items.quantity.count changing to 2 (from 1 in /select) is not valid as per API contract;
3. /on_init:
- billing.tax_number is for the buyer, hence, should be provided by buyer app;
- seller app can't specify that payment.collected_by is "BAP";
4. /confirm:
- quote.price.value is 210 but payment.params shows 260. Why?
5. /on_confirm:
- default fulfillment state code ("Pending") is missing;
- buyer app finder fee should match what was sent in /search;
6. /update:
- request was initiated after order was cancelled, yet the update state shows order as accepted. how?
7. /on_update:
- /update shows order state as accepted but here the order state is created. how?
- fulfillment state should be one of the post-order states, not pre-order state;
- quote should show the updated value of order;
- payment type & collected by is changed from what was in /on_confirm;

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by bluecypher** [comment]
/on_search
available count can't be greater than max count

/on_init
Billing details can't change in on_init

/on_confirm
Fulfillments state (/on_confirm) can't be null

/cancel
Transaction Id for /select onwards APIs should be same
Order Id in /cancel and /on_confirm do not match

/status
Transaction Id for /select onwards APIs should be same

/on_status
Transaction Id mismatch
Fulfillment State Code in /on_status is not as per the API Contract
Timestamp for status and on_status can't be same
BAP ID and URI can't change in on_status


@RonitKumarSinha

**Comment by sumit5219** [comment]
@bluecypher 
/on_confirm
Fulfillments state (/on_confirm) can't be null

the state is "Pending"

/cancel & /status is of Buyer App issue, we are Seller app.

/on_init
Billing details can't change in on_init, we din't find any mis match could you confirm please?

**Comment by sumit5219** [comment]
@bluecypher Please review  https://github.com/ONDC-Official/verification-logs/pull/435 for above issue fixes.
Files updated are for search, select, init, confirm, cancel.

**Comment by sumit5219** [comment]
@bluecypher Please review https://github.com/ONDC-Official/verification-logs/pull/436

File changes are done for search, select, init, confirm, cancel, status

**Comment by bluecypher** [comment]
update, track, status, and support APIs can't be validated due to different transaction_id

Items.price should not be provided in /on_select onwards 

/on_init
provider's location id should be provided in provider_location.id instead of provider.locations[].id

@RonitKumarSinha @sumit5219

**Comment by sumit5219** [comment]
@bluecypher Please review https://github.com/ONDC-Official/verification-logs/pull/442 

For on_cancel a separate order is created (payload_for_cancel file has its on_confirm payload.) as india stack buyer app invokes update api call again.

**Comment by bluecypher** [comment]
/on_confirm
order.created_at and order.updated_at timestamps are mandatory.

@RonitKumarSinha

**Comment by sumit5219** [comment]
@bluecypher 
Please review https://github.com/ONDC-Official/verification-logs/pull/452 

Fixed:
/on_confirm
order.created_at and order.updated_at timestamps are mandatory.

For on_cancel a separate order is created (payload_for_cancel file has its on_confirm payload.) as india stack buyer app invokes update api call again.

**Comment by bluecypher** [comment]
/on_select
items.quantity.selected is invalid key.
quote.breakup price value should be of individual count.

/on_confirm
order timestamp is updated when there is a change in order state.

/on_update
tags.status should be "Cancelled".

@sumit5219 @RonitKumarSinha

**Comment by sumit5219** [comment]
@bluecypher 

/on_confirm:
As per contract document :
Supriyo Ghosh
14:17 22 Jan
yes & seller app will update the "updated_at" in on_confirm

**Comment by bluecypher** [comment]
/on_select
'50' is not of type 'number' in $.quote.breakup[0].item.quantity.maximum.count
'50' is not of type 'number' in $.quote.breakup[0].item.quantity.available.count

/init
Wrong payload uploaded

/on_init
3 is not of type 'string' in $.payment.@ondc/org/buyer_app_finder_fee_amount

/on_confirm
provider.locations[].id mismatch

/cancel
Transaction Id mismatch

/on_cancel
Wrong payload uploaded

@RonitKumarSinha @sumit5219

**Comment by sumit5219** [comment]
@bluecypher Please review https://github.com/ONDC-Official/verification-logs/pull/461

**Comment by bluecypher** [comment]
/update
payment settlement_details can't be empty

/on_update
quote.breakup unit price missing
Billing object is not required
Fulfillments not required for "part cancel" 

/on_cancel (Different order and txn)
Payment and billing object not required
Fulfillments[] not required if cancellation reason is not triggering RTO. 

@sumit5219 @RonitKumarSinha

**Comment by sumit5219** [comment]
@bluecypher Please review - https://github.com/ONDC-Official/verification-logs/pull/467

**Comment by BLR-0118** [comment]
1. /on_search - serviceability construct & store timings to be explicitly defined as per v1.1.0 of API contract;
2. /on_select - why is provider descriptor provided?
3. /on_cancel - payload & quote is wrong as this is for full order, not part order. Also, this is for a different order id than what's created in /confirm, hence, difficult to correlate;
4. invoice url not in /on_status even after order accepted;
5. Logs have to comply with v1.1.0 of contract which was published yesterday;
6. Need payloads for the following scenarios in addition to the above:
- handling non-serviceability of items in /on_select;
- handling out of stock (full, part) in /on_select;
- complete order flow that tracks all order & fulfillment states;

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by bluecypher** [comment]
/on_search
message.catalog.bpp/providers[0].items[0].@ondc/org/mandatory_reqs_veggies_fruits.net_quantity should be of type string
either one of store timings (fixed or split) should be present

/select
Item Id 184ac88f-0c41-419d-be32-994879631e18 does not exist in /on_search

/on_init
item unit price is missing in quote.breakup
fulfillments[].state is not required in /on_init

/confirm
Billing object mismatches in /init and /confirm
payment.status should be "PAID" in case of pre-paid order(ON-ORDER)
payment.type is expected to be ON-ORDER
payment.collected_by is expected to be BAP
order.updated_at timestamp should be the same as order.created_at timestamp

/on_confirm
Billing object mismatches in /init and /on_confirm
fulfillments[0] start and end locations are mandatory
Quote Object in /on_select and /on_confirm do not match
addOns[],offers[] are invalid keys

Scenarios to be covered:
handling non-serviceability and item out-of-stock in /on_select and /on_init
complete order flow to track all order and fulfillment states

@RonitKumarSinha

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- /message/catalog/bpp/providers must have required property 'tags' (serviceability construct should be defined at bpp/providers level)
- /message/catalog/bpp/providers/0/time/label must be equal to one of the allowed values (enable,disable), instead of enabled
- /message/catalog/bpp/providers/0/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
- /message/catalog/bpp/providers/0/fulfillments/0/contact/phone must NOT have more than 11 characters
- /message/catalog/bpp/providers/0/items/@ondc/org/contact_details_consumer_care should be in the format "name,email,contact no"

**/on_init**

- Buyer app finder fee can't change in /on_init
- payment object has many invalid keys as per the API contract

**/on_confirm**

- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'tracking'
- /fulfillments/0 must have required property 'start'

**/on_status (unsolicited)**

- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'start'
- /fulfillments/0/end must have required property 'time'
- order.updated_at should be updated (due to change in order or fulfillment state)
- payment status can't be NOT-PAID when order is completed

**/on_update**

- must have required property 'payment'
- must have required property 'fulfillments'
- /quote/breakup/0 must have required property 'price' (item's total price)

## Flow 2

**/on_select (non-serviceable)**

- fulfillments/state/descriptor/code should be Non-serviceable

## Flow 4

- **on_select call for item unavailability is not present**

## Flow 5

- **Not as per the test case scenario (One of the selected items should be out-of-stock as per Flow 5)**

**on_status (after cancel)**

- cancellation reason id in tags is missing
- fulfillments state code should be set as Cancelled


@RonitKumarSinha

**Comment by bluecypher** [comment]
## Flow 1

**/on_confirm**

- order.updated_at timestamp should be updated as per the context.timestamp

**/on_status unsolicited**

- fulfillment start (pickup) and end (delivery) timestamps are mandatory when fulfillment state is Order-delivered
- order.updated_at should be updated when order is delivered
- fulfillments/start/location/address is not required
- /documents should be present (for invoice)

**/on_update**

- order.updated_at timestamp should match context.timestamp and can't be in future

## Flow 2

- similar issues as Flow 1

**on_select (non-serviceable)**

- delivery charges should be 0 when location is non-serviceable

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

**/on_select**

- selected quantity should be fulfilled for item 184ac88f-0c41-419d-be32-994879631e18 when inventory is available.

## Flow 5

- similar issues as Flow 1

**/on_select**

- unit price of item 184ac88f-0c41-419d-be32-994879631e18 should be present in quote.breakup[1].item.price


@RonitKumarSinha

**Comment by bluecypher** [comment]
## Flow 1

**/on_status (unsolicited)**

- pickup time (fulfillments/start/time/timestamp) and delivery time (fulfillments/end/time/timestamp) can't be same

**/on_update**

- liquidated item should be present in quote.breakup with quantity and it's total price as 0

## Flow 3

- similar issues as Flow 1


@RonitKumarSinha

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- provider enable timestamp should match the context.timestamp
- net_quantity in @ondc/org/mandatory_reqs_veggies_fruits should include unit of measurement along with the quantity.

**/on_status unsolicited**

- delivery time (/fulfillments/end/time/timestamp) should match context.timestamp and can't be future dated
- message_id should be different

## Flow 2, 3

- similar issues as Flow 1

## Flow 4

**/on_update**

- quote should not be updated when item is liquidated

## Flow 5

- similar issues as Flow 1


@RonitKumarSinha

**Comment by abhinavv245** [comment]
## Flow 1

**/on_status** (unsolicited)
- pickup(fulfillments/start/time/timestamp) time cannot be after the order has been delivered.


**/on_update**
- quote.breakup[1].price (item total price)should be 0 in case of liquidated item and unit price should not be 0

## Flow 2

- similar issues as Flow 1

## Flow 3

- similar issues as Flow 1

**/on_update**
- order.updated_at should match the context.timestamp

## Flow 4

- similar issues as Flow 1

**/on_update**
- liquidated line item with item id '184ac88f-0c41-419d-be32-994879631e18' missing in quote.breakup

## Flow 5

- similar issues as Flow 1

**/on_select**
- total price of out of stock item should be 0 and item unit price should not be 0

@RonitKumarSinha

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**
- context/timestamp difference between /on_search and /search should be smaller than 5 sec

**/on_confirm**
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)

**/on_status**
- payment.params must have transaction_id when fulfillment state is 'Order-delivered'

## Flow 2

**/on_select**
- for the same delivery address, fulfillment state should not be serviceable
- In case of non-serviceable, there should be no delivery charge in quote;

@RonitKumarSinha

**Comment by BLR-0118** [comment]
@RonitKumarSinha

**Comment by sumityabx** [comment]
Hi @BLR-0118 

**Flow 1:**
/on_search:
fulfillment id same as provider id. What's the logic & how will this work for multi-fulfillment orders? - **For multiple fullfilements our app makes sure to make it unique with appending "-001", "-002" etc if fulfillments are more than 1**

gps coords should be min 6 decimal precision; - **Fixed, Fix is done at store gps data stored at DB level. App reads those values from DB**

schedule.holidays can't be in the past; - **Fixed, Implemented to end only future holidays list.**

/on_confirm:
Why's are fulfillment.start location (id, name) different from what's in /on_search? - **Fixed**

Not clear whether all the fulfillment & order states are being correctly sent. Pls include logs for all such state transitions; - **sure**

/update:
not clear how ttl for approval is P7D and reverse qc is P3D. How're these set? - Unable to relate this statement with current logs, Can you clarify more here?

**Flow 2:**
Non-serviceable use case should be integrated into the main flow, not shown separately (using diff txn ids); - **sure**

/on_cancel: reason code used is invalid; **Fixed as per doc if seller is cancelling it uses only seller cancel reason code.**

**Comment by sumit5219** [comment]
Hi @BLR-0118 

**Flow 1:**
/on_search:
fulfillment id same as provider id. What's the logic & how will this work for multi-fulfillment orders? - **For multiple fullfilements our app makes sure to make it unique with appending "-001", "-002" etc if fulfillments are more than 1**

gps coords should be min 6 decimal precision; - **Fixed, Fix is done at store gps data stored at DB level. App reads those values from DB**

schedule.holidays can't be in the past; - **Fixed, Implemented to end only future holidays list.**

/on_confirm:
Why's are fulfillment.start location (id, name) different from what's in /on_search? - **Fixed**

Not clear whether all the fulfillment & order states are being correctly sent. Pls include logs for all such state transitions; - **sure**

/update:
not clear how ttl for approval is P7D and reverse qc is P3D. How're these set? - **Unable to relate this statement with current logs, Can you clarify more here?**

**Flow 2:**
Non-serviceable use case should be integrated into the main flow, not shown separately (using diff txn ids); - **sure**

/on_cancel: reason code used is invalid; **Fixed as per doc if seller is cancelling it uses only seller cancel reason code.**

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- reverse geocoding gps coords 13.105621,77.570382 shows pin code different from what's shown in logs;
2. curious how the transaction_id from /select onward is different from txn id for any of the /search? Or is this a different transaction for which search logs have not been shared?
3. /on_confirm:
- invoice should be added after order is shipped;

Flow 2
====
1. curious how the pin code (13.021574, 77.5927590000001) is both non-serviceable & serviceable (shown in both use cases);

**Comment by BLR-0118** [comment]
Pls resubmit logs for flow 1 & flow 2
@RonitKumarSinha

**Comment by sumit5219** [comment]
Hi @BLR-0118 

**Flow 1**

/on_search:
reverse geocoding gps coords 13.105621,77.570382 shows pin code different from what's shown in logs; - **store gps is corrected in DB and set properly by our mobile app - fixed**

curious how the transaction_id from /select onward is different from txn id for any of the /search? Or is this a different transaction for which search logs have not been shared? - **These were different, have provided the same tx id search req too now - fixed**

/on_confirm:
invoice should be added after order is shipped; - **Fixed**

**Flow 2**
curious how the pin code (13.021574, 77.5927590000001) is both non-serviceable & serviceable (shown in both use cases); **- as the location was nearer so serviceablity settings for store was not set properly post non servicable check(Issue while testing). Settings are corrected and tested with other location without changing the servicable area. - Fixed**

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0

**Comment by BLR-0118** [comment]
@sumit5219
