### ISSUE TITLE
kitchens-at - Compliance Check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#368]
1. Pls submit logs for request & callback, in end-to-end flow, so it's easier for us to verify e.g. /search & /on_search, etc.
2. Need APIs for /update & /on_update, /cancel & /on_cancel

**Comment by BLR-0118** [comment]
@manikantalh

**Comment by BLR-0118** [comment]
logs for verification should use a buyer app in Prod or to be in Prod soon (not the ONDC buyer app)

**Comment by BLR-0118** [comment]
@manikantalh

**Comment by BLR-0118** [comment]
1. /on_search -
- timestamp same as /search
- FSSAI no is invalid
- aren't F&B items non-returnable & non-cancellable?
2. /on_select -
- what does items.price here mean?
3. /on_confirm -
- no fulfillment state?
4. /on_status -
- fulfillment state code is invalid
5. /on_cancel -
- what's the justification for the updated quote here?
6. /on_update -
- items.tags.status is invalid

**Comment by BLR-0118** [comment]
@manikantalh

**Comment by manikantalh** [comment]
@BLR-0118 
1.on_search

- timestamp error is cleared in all response API calls i.e. on_search,on_select,on_init etc...
- FSSAI number issue cleared
- Because we wanted to test cancel and update only for those two order we made cancellable and returnable TRUE. All items are non-cancellable and non-returnable 
2.on_select: removed price object in items
3.on_confirm added fulfillment status object
4.on_status Update the code according enum
5.on_cancel we have added fulfillment and quote object since it was mentioned in API contract, now we have removed both fulfillment and quote object from on_cancel
6.on_update Updated the status according enum

**Comment by BLR-0118** [comment]
1. Pls submit logs for a complete end-to-end flow, without which it's not possible to verify e.g. in /select, an item is selected which isn't in /on_search, so hard to verify whether the prices, etc. are correctly reflected in the quote.

**Comment by BLR-0118** [comment]
@manikantalh

**Comment by BLR-0118** [comment]
1. /on_search - item shows as veg but description shows "chicken" for all?
2. /on_select -
- packaging & delivery charge is at fulfillment level, item_id should show fulfillment_id;
- item_id for tax should show the product item_id;
- breakup for "item" should show both total & unit price;
3. /on_init - payment has everything except collected_by
4. /on_cancel happened before /on_status, yet order state shows "Accepted" in /on_status. How?
5. /update is for a different order & transaction id than what's confirmed in the forward flow. Hence, difficult to verify.

**Comment by BLR-0118** [comment]
@manikantalh

**Comment by BLR-0118** [comment]
1. /on_search:
- fssai license no of "212" is invalid;
- no ttl at provider level for catalog;
2. /on_update:
- on_cancel should show the updated value for the order so the buyer app can do a diff between the original order value & new order value and determine the amount of refund

**Comment by BLR-0118** [comment]
Pls submit updated logs only for the above issues
@kitchensat

**Comment by bluecypher** [comment]
context.timestamp values are not accurate upto milliseconds


No /cancel and /status APIs to check

**Comment by kitchensat** [comment]
> context.timestamp values are not accurate upto milliseconds
> do we have to limit milliseconds to 3 digit or 6 digit
> No /cancel and /status APIs to check
> as of now no option in meesho preprod to call status and full cancel

**Comment by bluecypher** [comment]
/on_search
provider.locations time range is not in correct format. (should be 1100 and 2300) 
Return window should be provided when item is returnable

/on_select
quote.ttl=2S when context.ttl=30S?

/on_init
provider.locations is not required, details are already provided in provider_location property.

@kitchensat

**Comment by bluecypher** [comment]
/on_confirm
order.created_at cannot be modified by BPP
order.updated_at timestamp is updated as the order state is changed.

@kitchensat

**Comment by BLR-0118** [comment]
1. /on_init - fulfillment.start isn't in the contract;
2. /on_confirm - fulfillment.start shouldn't have address as per contract;
Pls confirm your compliance with [this](https://github.com/ONDC-Official/verification-logs/blob/main/Compliance%20Checklist%20for%20Prod.md) here;

**Comment by BLR-0118** [comment]
@kitchensat

**Comment by BLR-0118** [comment]
logs cleared
