### ISSUE TITLE
Airpay - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#379]
1. /search -
- transaction_id and message_id should be different
- ttl should be "PT30S" as defined in API contract

2. /select -
- transaction_id should be different from /search which should have unique transaction_id and all other APIs should have the same transaction_id for a user transaction

3. /init -
- key @ondc/org/linked_order is invalid for retail. This is only used for logistics

4. /support -
- ref_id should be transaction_id, not order.id

5. /update -
- payment struct will be sent after cancel is approved by seller

6. No /cancel, /track API?

**Comment by BLR-0118** [comment]
@jayesh-airpay

**Comment by amultamse** [comment]
@BLR-0118  We will work on your comments and resubmit.

**Comment by chaitairpay** [comment]
@BLR-0118 As we are NOT caching results now, we have unique transactionid for end results. When we will start caching results, that time too we will have new transactionId. We will not use existing transactionID, we created for OLD search result.
We need same transactionId so that we can trace transactionId from start to end. So can we skip point 2 ?

**Comment by BLR-0118** [comment]
What happens if multiple buyers use the same cached results to do end-to-end transactions? Won't it be difficult to provide traceability in this case?

**Comment by chaitairpay** [comment]
For each search we will create unique transactionID, So even though we are fetching results from cache, we will use diffrent transactionID.

**Comment by BLR-0118** [comment]
1. /search - pls use separate ids for transaction_id & message_id (is being followed in select onwards);
2. /init - fulfillment.provider_id should actually be fulfillment.id;

**Comment by BLR-0118** [comment]
@amultamse

**Comment by amultamse** [comment]
We have pushed logs. File name is on_status-after-part-cancel.json it should be considered as on_status-after-part-return.json.
Could not rename it.
In part cancel https://github.com/amultamse/verification-logs/blob/main/logs/airpay/jajee_11012022/part-return-flow/on_status-after-part-cancel.json

**Comment by BLR-0118** [comment]
@amultamse

**Comment by BLR-0118** [comment]
Logs verified & cleared

**Comment by chaitairpay** [comment]
Thank you very much @BLR-0118
