### ISSUE TITLE
Protean - RSP compliance check

### ISSUE THREAD

**Issue by AbhiSIITR** [ONDC-Official/verification-logs#431]
1. Transaction_id & Message_id mismatch in every API (or pair of APIs), this was raised earlier too
2. /collector_recon
- payment type should be ON-ORDER instead of ON_ORDER
- settlement type enum should be in lower case (suggestive)
- settlement status is ready in On-Order payment, we need to understand this status
3. /on_settle 
- error code should not be sent if there is no value
4. /receiver_recon
- payer details should not be in camelcase
- correction object should not be sent in /receiver_recon, it is to be added in case of an error in reconciliation
- orders.transaction id and collector_recon context.transaction id are same 
- diff_amount and message should not be sent, it is to be initiated by Receiver in case of an error in reconciliation
5. /on_collector_recon
- order transaction id and collector_recon context transaction id are same

**Comment by AbhiSIITR** [comment]
@NirmalR-protean

**Comment by NirmalR-protean** [comment]
@AbhiSIITR Thanks for the review comments! We have made the corrections as suggested and have raised PR #464 for the same.

**Comment by bluecypher** [comment]
/collector_recon
orders[].transaction_id is an invalid key

/settle
context.transaction_id mismatches in /collector_recon and /settle
settlements[].prev_settlement_reference_no is invalid key in /settle
settlements[].state is invalid key

/receiver_recon
settlement_timestamp can't change in settlement_details (payment_object)
context.transaction_id and orders[].transaction_id can't be same


/on_receiver_recon
orders[].id can't change
orders[].recon_status is invalid key (orders[].order_recon_status is already provided)
context.transaction_id and orders[].transaction_id can't be same
orders[] timestamps can't change 

/on_collector_recon
orderbook.order[] is invalid(should be orderbook.orders[])
context.transaction_id and orders[].transaction_id can't be same
orders[] timestamps can't change in on_collector_recon

/recon_status
transaction_id should be the transaction id used in collector_recon (payment.params.transaction_id)

/on_recon_status
orderbook.order[] is invalid (should be orderbook.orders[])
invalid orders[].transaction id

@NirmalR-protean

**Comment by NirmalR-protean** [comment]
@bluecypher Thanks for the review comments! We have made the corrections as suggested and have raised PR #479 for the same.


**/collector_recon**
orders[].transaction_id is an invalid key - Fixed

**/settle**
settlements[].prev_settlement_reference_no is invalid key in /settle - As discussed this is not an issue
settlements[].state is invalid key - State is pending hence not an issue

**/receiver_recon**
settlement_timestamp can't change in settlement_details (payment_object) - Fixed
context.transaction_id and orders[].transaction_id can't be same - As discussed, they were not the same

**/on_receiver_recon**
orders[].id can't change - Fixed 
orders[].recon_status is invalid key (orders[].order_recon_status is already provided) - Fixed
context.transaction_id and orders[].transaction_id can't be same - As discussed, they were not the same
orders[] timestamps can't change - Fixed

**/on_collector_recon**
orderbook.order[] is invalid(should be orderbook.orders[]) - Fixed
context.transaction_id and orders[].transaction_id can't be same - As discussed, they need to be same
orders[] timestamps can't change in on_collector_recon - Fixed

**/recon_status**
transaction_id should be the transaction id used in collector_recon (payment.params.transaction_id) - As discussed, this is not an issue

**/on_recon_status**
orderbook.order[] is invalid (should be orderbook.orders[]) - Fixed
invalid orders[].transaction id - As discussed, this is not an issue

**Comment by AbhiSIITR** [comment]
Logs approved

**Comment by AbhiSIITR** [comment]
Logs approved
