### ISSUE TITLE
ONDC-Reference-Buyer-App : Compliance Check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#460]
**BAP Issues**
/init
items[].add_ons and items[].offers are invalid keys
fulfillments[].id is missing

/confirm
order- created_at and updated_at timestamps are missing

**BPP Issues:**
/on_search
available count can't be greater than maximum count

/on_select
fulfillments TAT should be in Days if (>24H)

/on_status
billing object mismatches in /init and /on_status

/on_update
quote.breakup is mandatory

@wemakshaychavan

**Comment by bluecypher** [comment]
/select
gps precision issue

/confirm
item[].fulfillment_id is missing
Fulfillments[]: addons[] and offers[] are invalid keys

/update
payment settlement_details are missing

@wemakshaychavan

**Comment by BLR-0118** [comment]
1. /search, /select - gps lat/lng precision should be the same;
2. /init - since payment is pre-paid (collected by buyer app), payment.type="ON-ORDER" and collected_by="BAP";
3. No /cancel API?
Many different order ids are used for the logs, hence difficult to understand whether refund calculation in /update is accurate. Pls share logs for 1 end-to-end scenario so it's easy to verify.

**Comment by BLR-0118** [comment]
@wemakshaychavan

**Comment by BLR-0118** [comment]
1. /init - following keys are invalid:
"@ondc/org/ondc-withholding_amount": 0, (should be "@ondc/org/withholding_amount")
"@ondc/org/ondc-return_window": 0 (should be "@ondc/org/return_window"),
"@ondc/org/ondc-settlement_basis": "Collection" (should be "@ondc/org/settlement_basis"),
"@ondc/org/ondc-settlement_window": "P2D" (should be "@ondc/org/settlement_window")

Logs cleared for Production subject to the above changes being made.

**Comment by bluecypher** [comment]
/on_search
merchant should be explicitly enabled or disabled

/on_select
provider.locations[].id is missing

/init
payment object is not a part of /init as per the API contract
tag and street are not valid keys in billing object

/confirm
order.updated_at timestamp should be the same as order.created_at timestamp
fulillments[].customer is invalid key

/update - with return
order is returned when fulfillment state is still pending

/cancel
cancel API can't be called on partially cancelled/returned order

Scenarios to be covered:
Response to Non-serviceability and out of stock in /on_select and /on_init.

@wemakshaychavan

**Comment by BLR-0118** [comment]
1. /init:
- door is deprecated, should be removed;
- are we providing clear instructions to buyers to enter their address fields such as name, building, locality correctly?
- billing.created_at & updated_at timestamps should be the same as Context.timestamp;

2. /confirm:
- payment.uri needs the URL for payment gateway;
- billing.created_at & updated_at should have same timestamp as in /init;
- door is deprecated, should be removed;
- are we providing clear instructions to buyers to enter their address fields such as name, building, locality correctly?

3. /update:
- can't verify if refund amt is computed correctly as "on update- return - with refund amount.json" shows 2 qty of an item with return initiated status when order was placed for only 1 qty??

4. Need to understand how serviceability, store timings are being handled?
5. Need to understand how exception scenarios (/on_select ii & iii in API contract) are being handled?
6. Are error codes being interpreted & appropriate error message displayed?

**Comment by BLR-0118** [comment]
@wemakshaychavan

**Comment by BLR-0118** [comment]
@wemakshaychavan

**Comment by BLR-0118** [comment]
logs approved subject to above changes being made
