### ISSUE TITLE
Globallinker - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#485]
1. /on_search:
- category_id should be mapped from [here](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0) as mentioned in the contract and appropriate attribute keys to be provided;
- serviceability construct has to be explicitly defined
- store timings & holidays (if any)to be explicitly defined
- merchant should be explicitly enabled or disabled
2. /on_select:
- items array should only have the mapping of item id & fulfillment id as per the contract;
- breakup[].item_quantity.count should be integer;
3. /on_init:
- breakup[].item_quantity.count should be integer;
4. /on_confirm:
- payment.status was paid in /confirm but became "not paid" in /on_confirm. How?

**Comment by BLR-0118** [comment]
5. /on_status:
- payment."@ondc/org/settlement_details"[].settlement_counterparty was "seller-app" in /on_confirm but is "buyer-app" in /on_status. How?
6. Also need some logs to show:
- unsolicited /on_status call to update status of order & fulfillment;
- on_select response showing non-serviceable and out-of-stock conditions;

**Comment by BLR-0118** [comment]
@Ravikiran10061992

**Comment by BLR-0118** [comment]
1. /on_search:
- bpp/providers.locations.address.street needs to be text, not image;
- serviceability category should match items.category_id (same as in this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0))
2. /on_init:
- provider_location.id is "glondcmall_location" while in /on_search & /select it was "idealgrocerystore_location";
- item.price (for unit price) shouldn't be here;
3. /on_confirm:
- order.updated_at should be updated to Context.timestamp whenever the order object is updated (in this case, the default fulfillment state of "Pending" gets added);
4. /on_status:
- payment.uri & tl_method should be the same as what's passed by the buyer app in /confirm (as collection is prepaid by buyer app);
5. unsolicited_on_status:
- if fulfillment state code is "out for delivery", start.timestamp (when picked up) should be provided;
6. unsolicited_on_status_delivered:
- if fulfillment state code is "delivered", end.timestamp (when delivered) should be provided;
7. for 5 & 6, the order state is missing, needs to be added;
8. pt 6 above with timestamp "2023-02-17T05:57:53.254Z" shows fulfillment state code as delivered but unsolicited_on_update with later timestamp shows fulfillment state as pending. This is incorrect;
9. unsolicited_on_update:
- currently, only liquidated state is supported;
- after return state changes to liquidated, the quote should reflect it (i.e. item_quantity becomes 0 & order value is updated);

**Comment by BLR-0118** [comment]
@Ravikiran10061992

**Comment by BLR-0118** [comment]
1. /on_select: "@ondc/org/item_id" for title_type "misc" is invalid as this is at the fulfillment level & there's no fulfillment "F1";

2. /on_init - no "@ondc/org/item_id" for title_type "misc";

3. /on_confirm - breakup.price is wrong, shows the unit price as total price; the structure should be exactly similar to what's in /on_select & /on_init;

4. /on_status - same issue as 3, billing.created_at & billing.updated_at missing, order.created_at & order.updated_at missing, order.documents for invoice missing, item_id missing for title_type "misc";

5. unsolicited_on_status - same issues as 4 + item_id missing for title_type "misc" and "delivery";

6. unsolicited_on_status_Delivered - same issues as 5 + fulfillment.state.descriptor.code of "Delivered" is invalid;

7. on_update - fulfillment.state.descriptor.code invalid (see 6 above), item_id missing for title_type "misc";

**Comment by BLR-0118** [comment]
@Ravikiran10061992

**Comment by bluecypher** [comment]
### Flow 1
**/on_confirm**
billing created and updated timestamps can't change
order.updated_at timestamp changes only when order.state is updated
fulfillments[] start and end time range are mandatory in /on_confirm

**/on_status**
'fulfillment_id' is a required property in items[]
'tracking' is a required property in fulfillments[0]
order created and updated timestamps should be precise upto milliseconds
order.updated_at timestamps should be updated as per the order state
fulfillments[] start and end time range are mandatory
start.contact is missing in fulfillments[]

**/on_status (unsolicited)**
time range should be on fulfillments[].start and fulfillments[].end level 

**/on_status Unsolicited (Order-delivered)**
billing updated_at timestamp can't change
invoice url should be shared in order.documents

**/on_update**
items.quantity.count should be integer
items.quantity.count can't be 0 for item "5775572_6445826_9605625"

### Flow 4 and 5

**/on_select**
if available count of item is 0 in quote.breakup, then why the item is selected in /select (In stock) ?

@Ravikiran10061992

**Comment by bluecypher** [comment]
### Flow 1

**/init**
why change in fulfillments[].end.location in /select and /init

**/on_select**
fulfillments[] TAT can't be smaller than time to ship in /on_search

**/on_confirm**
start.location.descriptor.name in /on_confirm and /on_search are different;

### Flow 4

**/on_select (cannot fulfill entire quantity)**
if available count of item (5775572_6445865_9605687) is 1, then why is it not being fulfilled?
error.message is not mandatory

### Flow 5

**/on_select**
In case of out of stock, available and maximum count of item should be 0.

Flow 2 and 3 should be reuploaded. 

@Ravikiran10061992

**Comment by BLR-0118** [comment]
Logs are incomplete without logs for flows 2 & 3?

**Comment by BLR-0118** [comment]
@Ravikiran10061992

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_confirm: any reason why rateable is false for provider, fulfillment?
2. unsolicited /on_update: pls use the same message_id (as /update) for this specific case for now (same with unsolicited /on_update in flow 3, flow 4, etc.);

Flow 2
====
1. unsolicited /on_cancel: there is no key for order.timestamp in the protocol. Pls remove;

Pls also verify your compliance with & document here [this](https://github.com/ONDC-Official/verification-logs/blob/main/Compliance%20Checklist%20for%20Prod.md).

Pls update here when the above corrections and documentation of your compliance verification is done. No need to resubmit logs.

**Comment by BLR-0118** [comment]
@Ravikiran10061992

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
