### ISSUE TITLE
Shadowfax - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#503]
1. /on_confirm - fulfillment.state.descriptor.code is invalid;
2. /on_status - pls share payload for unsolicited /on_status up to order completion (at least including Order.picked-up, Order-delivered;
3. /on_status_rto - order state is invalid, should be "Cancelled";
Also, does Shadowfax only do immediate delivery? What about SDD/NDD? If you also support SDD/NDD, please also share /update & /on_update for triggering "ready to ship";

**Comment by BLR-0118** [comment]
@anny06

**Comment by anny06** [comment]
1. Please provide expected values for fulfillment.state.descriptor.code?
2. have added the requested logs https://github.com/ONDC-Official/verification-logs/pull/504
3. Have fixed the order status in above PR,

Yes we are doing only Immediate delivery for now.

**Comment by BLR-0118** [comment]
kitchens-at logs:
1. Pls check the logistics API contract for enums for fulfillment state codes (it's in the footnote tagged to the same key);
2. /on_status_delivered - order state "Delivered" is invalid, should be "Completed";
3. /on_status - fulfillment state can't be "Searching-for-Agent" when order state is "Created". Order has to be accepted before agent can be searched;
4. Need to support /search with category "Standard Delivery" where you should return all immediate delivery options;

**Comment by BLR-0118** [comment]
@anny06

**Comment by anny06** [comment]
1. Kindly share the enums, I am referring [this](https://docs.google.com/document/d/10GpEuKZE2g96DFJT3HKq6wIEMhPC-kkMZhXNn2jHHXc/edit#heading=h.ihfhpah2ol09) enums for this are not there
2. Updated in https://github.com/ONDC-Official/verification-logs/pull/505
3. Updated in above PR
4. Yes, this is working

**Comment by bluecypher** [comment]
### kitchens@ logs:

**/on_search**
items[].fulfillment_id should be one of the bpp/fulfillments[].id
incorrect key categories[].time.lable (should be label) 

**/init**
payment object is not as per the API contract

**/on_init**
payment object is not as per the API contract

**/confirm**
items.quantity.count should be integer
@ondc/org/linked_order schema not as per the API contract

**/on_confirm**
same txn should be shared for validation
fulfillment.state.descriptor.code should be "Pending"
billing object is missing (should be same as /init)
awb_no should be a string (& mandatory only in case of P2H2P fulfillments)
start and end time range should be precise upto milliseconds
order created and updated timestamps are missing (order.updated_at should change as per the order state)

**/on_status**
provider,items, quote objects missing
billing object should be same as in /init

**/on_status_ofd**
txn id should be same for unsolicited calls
provider.id is missing
order.id can't be same as txn_id
fulfillments[] start and end time.timestamp should be in the time range  
billing object should be same as in /init

### +Eunimart logs:

**/on_cancel**
cancellation_reason_id in tags is missing

**/update**
update in shipment status is not applicable in case of immediate delivery


@anny06

**Comment by anny06** [comment]
@bluecypher in /on_status billing should be lSP's billing details right?
Why should it be same as /init?

**Comment by anny06** [comment]
`start and end time range should be precise upto milliseconds` they are in milliseconds only,
`payment object is not as per the API contract ` kindly explain what's missing here

**Comment by anny06** [comment]
@bluecypher  above comments have been addressed in https://github.com/ONDC-Official/verification-logs/pull/515 kindly check

**Comment by BLR-0118** [comment]
1. /on_confirm - why did the order.created_at timestamp change? It should be the same as what's in /confirm;
2. Do you have provision for deferred ready-to-ship, i.e. passed through /update?
3. /on_search - do you have only 1 option for immediate delivery (2 hr TAT)? If you have multiple options, item-level TAT is also required in /on_search;
4. /on_search - for "SFXImmediateDelivery", parent_item_id="" is also required as per contract;

**Comment by BLR-0118** [comment]
@anny06

**Comment by anny17** [comment]
@BLR-0118 
1. I'm reverting with the order's create time at our end, changing it to return the same as received in /confirm
2. No, as we are only doing Immediate delivery, we are expecting the ready-to-ship in confirm only
3. Yes, we only have 1 option for Immediate delivery
4. Okay, will add this.

**Comment by anny06** [comment]
@BLR-0118

I'm reverting with the order's create time at our end, changing it to return the same as received in /confirm
No, as we are only doing Immediate delivery, we are expecting the ready-to-ship in confirm only
Yes, we only have 1 option for Immediate delivery
Okay, will add this.

**Comment by BLR-0118** [comment]
Also, participants using immediate delivery for on-network logistics are sending the pickup code in fulfillment.start.instructions.short_desc in /confirm. Hope you'll be honoring this.
@anny06

**Comment by anny06** [comment]
Yes @BLR-0118

**Comment by BLR-0118** [comment]
Logs with kitchens-at:
1. /on_search:
- parent_item_id="" should be provided for "SFXImmediateDelivery";
- Shadowfax also needs to support search for category "Standard Delivery" which returns only the "Immediate Delivery" option in your case as this is used by all logistics buyers;
2. /init - billing.tax_number is GST no (15 digits), here it shows 12 digit no;
3. /update & /on_update - Shadowfax should support "ready to ship" in both /confirm & /update;
4. /on_support - phone no should be 10 digits;

**Comment by BLR-0118** [comment]
@anny06 @kitchensat

**Comment by anny06** [comment]
Hi @BLR-0118 
If how can we send the start and end time ranges in on_confirm if `ready_to_ship` was not sent in the /confirm API??

**Comment by kitchensat** [comment]
> 3\. confirm

we are sending ready_to_ship as yes in confirm payload. can u check

**Comment by anny17** [comment]
Please check the latest log with https://github.com/ONDC-Official/verification-logs/pull/533

**Comment by BLR-0118** [comment]
Logs with kitchens-at
==============
1. why is there a 1 hr difference between timestamps for /search & /on_search? Also, between /confirm & /on_confirm;
2. in /on_search, the price for "SFXImmediateDelivery" is 45. Why does this change to 105 in /on_init?
3. /on_status_delivered - shows fulfillment.start.timestamp (actual time of pickup) & fulfillment.end.time.timestamp (actual time of delivery) as future dated (i.e. ahead of Context.timestamp). How?
4. order timestamp (order.updated_at) needs to be updated in /on_confirm, /on_status, /on_cancel, /on_update APIs;
5. PCC should be sent by logistics buyer in fulfillment.start.instructions.short_desc in /confirm and Shadowfax needs to honour it;
6. Shadowfax needs to support search with category_id of "Standard Delivery" that returns all immediate delivery options;

**Comment by BLR-0118** [comment]
@anny06

**Comment by BLR-0118** [comment]
@kitchensat - pls check pt 5 above

**Comment by anny17** [comment]
1. fixed
2. fixed
3. fixed
4. this field is not there in v1.1.0 doc for  /on_status, /on_cancel
5. Already handled
6. Yes we are supporting Standard Delivery in search, and returning with Immediate delivery option.

Kindly check PR https://github.com/ONDC-Official/verification-logs/pull/537

**Comment by BLR-0118** [comment]
1. /on_confirm - order.updated_at should change to Context.timestamp (for /on_confirm) as the default fulfillment state code added;
2. /on_status - same issue as 1;
3. /on_status_ofd - how did the billing.created_at & updated_at timestamp, billing.tax_number change from /init (even though the transaction_id is the same)?
4. /on_status_delivered - same issue as 3;

**Comment by BLR-0118** [comment]
@anny06

**Comment by anny17** [comment]
Kindly check https://github.com/ONDC-Official/verification-logs/pull/539

**Comment by BLR-0118** [comment]
logs cleared for 1.1.0
