### ISSUE TITLE
PLOTCH-RSP - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#507]
context.key is an invalid attribute 
context.timestamp should be precise upto milliseconds

**/collector_recon**
invoice_no can't be empty
settlement_reason_code can't be 01 (settled) in /collector_recon
payment.status is missing

**/settle**
payee_account_type value is incorrect (should be a valid enum)

**/on_settle**
message_id and txn_id mismatch in /settle and /on_settle

**/receiver_recon**
settlement_timestamp is missing in settlement_details
orders[].updated_at timestamp should be updated
order_recon_status is missing
settlement_status in @ondc/org/settlement_details should be "PAID" as recon_status is 1

**on_receiver_recon**
order_recon_status can't be 01 (provisional)
context message_id and txn_id mismatch in receiver_recon and on_receiver_recon 

no /recon_status to validate

@vikramacharya

**Comment by vikramacharya** [comment]
All feedbacks implemented here https://github.com/ONDC-Official/verification-logs/pull/538 
@BLR-0118

**Comment by bluecypher** [comment]
**/collector_recon**

- context txn id and msg id can't be same
- @ondc/org/buyer_app_finder_fee_type is in percent, value of @ondc/org/buyer_app_finder_fee_amount should be in percent instead of absolute amount
- attributes in @ondc/org/settlement_details should not have null values
- settlement_amount should be integer
- invalid value of settlement_timestamp
- created_at and updated_at timestamps should have orderbook creation date-time value

**/settle**

- settlements[].timestamp should be in ISO8601 format

**/receiver_recon**

- settlement_timestamp and orders[].updated_at should be the timestamp of /on_settle
- invalid value of settlement_type
- settlement_status in @ondc/org/settlement_details should be PAID when recon_status is 01

**/on_receiver_recon**

- incorrect enum value for counterparty_recon_status
- order_recon_status should be 02 (Final)

**/on_collector_recon**

- context txn id and msg id can't be same


@vikramacharya

**Comment by vikramacharya** [comment]
@bluecypher : all feedback corrected. 
https://github.com/ONDC-Official/verification-logs/pull/546

**Comment by bluecypher** [comment]
**Logs Approved** ( conditional sign-off )

**Comment by bluecypher** [comment]
context/domain must be ONDC:NTS10

**/collector_recon**

- context/ttl must be P3D as defined in the contract
- settlement trail must be maintained with diff amount in "@ondc/org/settlement_details"
- invalid issue_subtype in /correction; use the enums as defined [here](https://docs.google.com/spreadsheets/d/1bxVNDzsYLsVPRGwkFZdDCnxA_ueFM1Lu/edit#gid=605622896)
- order/created_at can't be the same as context/timestamp; should be the timestamp when orderbook was created

**/settle**

- payment_type does not align with settlement_type (upi) received in /collector_recon

**/on_receiver_recon**

- /message/orderbook/orders/order_recon_status must be equal 02


@vikramacharya

**Comment by vikramacharya** [comment]
@bluecypher any update here? Logs were submitted Oct'12

**Comment by bluecypher** [comment]
Logs cleared for RSP v1.0.0

@vikramacharya
