### ISSUE TITLE
CHAIPOINT - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#516]
Logs should be shared as per the [test case scenarios](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit)

**/on_search**
context.key is an invalid attribute
invalid keys bpp_providers, bpp_descriptor,bpp_fulfillments should be (bpp/providers,bpp/descriptor and bpp/fulfillments)
'symbol' is a required property in $.message.catalog.bpp/descriptor
'images' is a required property in $.message.catalog.bpp/providers[].descriptor
street, city, and state are required property in bpp/providers[].locations[].address
'maximum_value' is a required property in message.catalog.bpp/providers[].items[].price
F&B is a deprecated category_id. Follow the [enhanced taxonomy](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
veg and non_veg are required property in tags (isVegetarian is invalid key)
'@ondc/org/fssai_license_no' is a required property in message.catalog.bpp/providers[]
'@ondc/org/return_window' is a required property in message.catalog.bpp/providers[0].items[0]
'symbol' is a required property in message.catalog.bpp/providers[0].items[0].descriptor
'@ondc/org/contact_details_consumer_care' is a required property in $.message.catalog.bpp/providers[]
'fulfillment_id' is a required property in $.message.catalog.bpp/providers[0].items[]
'@ondc/org/cancellable' is a required property in $.message.catalog.bpp/providers[].items[]
'@ondc/org/available_on_cod' is a required property in $.message.catalog.bpp/providers[].items[]
'@ondc/org/time_to_ship' is a required property in $.message.catalog.bpp/providers[].items[]
quantity.available.count should be smaller or equals to quantity.maximum.count
serviceability construct is not defined
merchant enable/disable is not defined

**/on_select**
multiple keys are not as per the API contract
'count' is a required property in items[].quantity
'@ondc/org/title_type' is a required property in $.quote.breakup[]
'ttl' is a required property in $.quote
'state' is a required property in fulfillments[]
Quote breakup Payment title "Round Off" is not as per the API Contract
Quote breakup Payment title "Delivery Charges" comes under the title type "delivery"
Fulfillment TAT must be present for fulfillment ID: 76

**/init**
Timestamp for /on_select api cannot be greater than or equal to /init api

**/on_init**
billing object mismatches in /init and /on_init

**/confirm**
Timestamp for /on_init api cannot be greater than or equal to /confirm api
Billing object mismatches in /init and /confirm
payment.status should be "PAID" in case of pre-paid order(ON-ORDER)
payment.type is expected to be ON-ORDER
payment.collected_by is expected to be BAP
Quote Objects in /on_select and /confirm do not match

**/on_confirm**
'fulfillment_id' is a required property in $.items[0]
'@ondc/org/title_type' is a required property in $.quote.breakup[]
'email' is a required property in $.billing
'phone' is a required property in $.billing
'state' is a required property in $.fulfillments[0]
'tracking' is a required property in $.fulfillments[0]
'@ondc/org/settlement_details' is a required property in $.payment
Order Id mismatches in /confirm and /on_confirm
order.created_at timestamp mismatches in /confirm and /on_confirm
order.updated_at timestamp mismatches in /confirm and /on_confirm
items[0].fulfillment_id mismatches for Item 831 in /on_select and /on_confirm
Billing object mismatches in /init and /on_confirm
fulfillment id 449830011677418077130000001 does not exist in /on_select
Quote Object in /on_select and /on_confirm do not match
order created and updated timestamps are mandatory in /on_confirm

**/on_track**
Message Id for /track and /on_track api should be same

**/status**
Order ids in /confirm and /status do not match

**/on_status**
'fulfillment_id' is a required property in $.items[0]
billing object mismatches in /init and /on_status
'payment' is a required property in $
Order id in /on_confirm and /on_status do not match

@kushagraj24

**Comment by kushagraj24** [comment]
Hi Team,
We've uploaded new logs with the changes kindly go through it and approve.

**Comment by paragcp** [comment]
@BLR-0118 Can we get our new logs verified.

**Comment by bluecypher** [comment]
### Logs should be shared as per the [test case scenarios](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit) with following changes:

**/on_search**

- /message/catalog/bpp/providers/ must have required property 'time'
- /message/catalog/bpp/providers/ must have required property 'fulfillments'
- /message/catalog/bpp/providers/ must have required property 'tags' (for serviceability construct)
- /message/catalog/bpp/providers/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
- /message/catalog/bpp/providers/locations/0 must have required property 'time'
- /message/catalog/bpp/providers/locations/0/address must have required property 'state'
- /message/catalog/bpp/providers/items/0 must have required property '@ondc/org/contact_details_consumer_care'
- /message/catalog/bpp/providers/items/0/category_id must be equal to one of the allowed values (refer [enhanced sub category](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0))
- /message/catalog/bpp/providers/items/ must have required property '@ondc/org/contact_details_consumer_care'
- /message/catalog/bpp/providers/items/@ondc/org/time_to_ship is not in iso8601 duration format (should be PT45M)
- /message/catalog/bpp/providers/items/ quantity.available.count should be smaller or equals to the quantity.maximum.count

**/on_select**

- /items/parent_item_id is an invalid key
- /provider/tags is an invalid key
- /items/ should have only id and fulfillment_id attributes
- /quote must have required property 'ttl'
- /quote/breakup/0 must have required property '@ondc/org/title_type'
- /quote/breakup/0 must have required property '@ondc/org/item_id'
- /quote/breakup/1 must have required property '@ondc/org/title_type'
- /quote/breakup/1 must have required property '@ondc/org/item_id'
- /quote/breakup/2 must have required property '@ondc/org/item_id'
- /quote/breakup/3 must have required property '@ondc/org/item_id'
- /quote/breakup/4 must have required property '@ondc/org/item_id'
- /quote/breakup/4/@ondc/org/title_type must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)
- /quote/breakup/5 must have required property '@ondc/org/item_id'
- /quote/breakup/5/@ondc/org/title_type must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)
- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property '@ondc/org/category'

**/on_init**

- must have required property 'payment'
- must have required property 'provider_location'
- /order/id is not created in /on_init
- /items/0 must have required property 'fulfillment_id'
- /items/1 must have required property 'fulfillment_id'
- /items/2 must have required property 'id'
- /items/2 must have required property 'fulfillment_id'
- /items/2 must have required property 'quantity'
- Item Id 52678 does not exist in /on_select
- Item Id 52677 does not exist in /on_select
- Billing object mismatches in /init and /on_init (tax number should be removed)
- Quoted Price 796.94 does not match with Net Breakup Price 37.94 in /on_init
- Payment Object can't be null in /on_init

**/on_confirm**

- must have required property 'created_at'
- must have required property 'updated_at'
- /items/0 must have required property 'fulfillment_id'
- /items/1 must have required property 'fulfillment_id'
- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'state'
- /fulfillments/0 must have required property 'start'
- Order Id mismatches in /confirm and /on_confirm

**/on_status**

- must have required property 'payment'
- must have required property 'created_at'
- must have required property 'updated_at'
- billing object should remain the same as in /init
- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'state'
- /fulfillments/0 must have required property 'tracking'
- /fulfillments/0 must have required property 'start'
- /fulfillments/0 must have required property 'end'

@kushagraj24

**Comment by bluecypher** [comment]
@kushagraj24 

All the flows should be covered as mentioned in the [test case scenarios](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit).

**Comment by kushagraj24** [comment]
@bluecypher The logs are as per test case scenarios. We don't have return option so there's no return case.

**Comment by paragcp** [comment]
@bluecypher Being F&B seller,we dont get the food item returned,so we dont support any of the return flows.Hence not submitted logs to those test cases.

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- /bpp/providers/time/timestamp should be equal to the context.timestamp
- /bpp/providers/category_id is an invalid key
- /items/@ondc/org/contact_details_consumer_care should be in the format "name,email,contact no"
- serviceability construct (/bpp/providers/tags) for category_id Beverages (MTO) is not defined

**/on_select**

- context.timestamp difference b/w /select and /on_select can't be more than 30s as per the context.ttl (should be less than 5s)
- /quote/breakup/item/quantity/maximum/count must be string
- /quote/breakup/item/quantity/available/count must be string
- charges in quote are not as per the API contract (tax should be consolidated for an item)
- /quote/breakup/@ondc/org/title_type must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)

**/on_init**

- /payment must have required property '@ondc/org/settlement_details'
- /order/items/id can't change in /on_init
- /billing/tax_number is invalid (doesn't exist in /init)
- /quote/breakup/item/quantity is not required in /on_init

**/on_confirm**

- /fulfillments/0/state/descriptor/code "Created" is an invalid state (should be "Pending")
- /fulfillments/0/start/location must have required property 'descriptor'
- /fulfillments/0/start/location must have required property 'gps'
- /payment/@ondc/org/settlement_details/0 must have required property 'settlement_type'
- order.created_at timestamp mismatches in /confirm and /on_confirm

**/on_status**

- /fulfillments/0 must have required property 'state'
- /fulfillments/0/start/location must have required property 'descriptor'
- /fulfillments/0/start/location must have required property 'gps'
- /fulfillments/0/end must have required property 'time'
- /quote must have required property 'ttl'
- /quote/breakup should be the same as in /on_confirm

## Flow 2

- similar issues as Flow 1

**search & /on_search**

- context/core_version should be 1.1.0

**/confirm & /on_confirm**

- flow should be sent for the same transaction
- inconsistencies in context.timestamp


@kushagraj24  @paragcp

**Comment by paragcp** [comment]
@bluecypher Pls merge the below PR
https://github.com/ONDC-Official/verification-logs/pull/637

**Comment by abhinavv245** [comment]
## Flow 1


**/on_select**

- /quote/breakup/@ondc/org/item_quantity/count must be integer
- Quote breakup Payment title "Round off" is not as per the API Contract


**/on_confirm**
- /items/quantity/count must be integer
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)

**/on_status**

- Order should be fulfilled and updates should be sent through unsolicited /on_status Api

## Flow 2

- Similar issues as Flow 1

**on_confirm**

- order.created_at timestamp cannot change in /on_confirm

@kushagraj24 @paragcp

**Comment by bluecypher** [comment]
@kushagraj24 @paragcp all the flows should be implemented including the return flows. Even for F&B, the flows must consist of refund scenarios.

**Comment by bluecypher** [comment]
@kushagraj24 @paragcp, please submit all the 5 flows as mentioned in the test case scenario document.

**Comment by paragcp** [comment]
@bluecypher As already discussed,we support 3 flows of this,we dont support last 2 flows.We have marked the items as non cancellable and not returnable and on update the items will be return_rejected by the seller.

**Comment by paragcp** [comment]
@bluecypher the issues are removed now.Kindly approve.

**Comment by paragcp** [comment]
@bluecypher kindly update us on this.

**Comment by bluecypher** [comment]
@paragcp, the issues still exist. As already mentioned, the logs will be reassessed once all the flows, as documented in the test case scenarios, are implemented as it is.

**Comment by paragcp** [comment]
@bluecypher Can you pls verify the logs?

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- serviceability construct /bpp/providers/tags should be defined as per the API contract

**/on_select**

- Item's unit and total price mismatch for id: 1046
- quote.price.value does not match with the price breakup

**/on_confirm**

- /items/quantity/count must be integer

**/on_status**

- order.created_at should not change in /on_status
- pickup(/fulfillments/start/time/timestamp) and delivery(/fulfillments/end/time/timestamp) time missing for fulfillment state 'Order-delivered'
- fulfillment id '1' does not match with the fulfillment id provided in /on_select 

**/on_update**

- /order must have required properties 'payment', 'created_at', 'updated_at'
- /fulfillments must have required property '@ondc/org/provider_name'
- pickup(/fulfillments/start/time/timestamp) and delivery(/fulfillments/end/time/timestamp) time cannot be same
- /quote must have required property 'ttl'

## Flow 2

- similar issues as Flow 1


**/on_select (non-serviceable)**

- /select call for this /on_select missing
- Why are there inconsistencies in the breakup of serviceable and non-serviceable /on_select apis? 

**/on_cancel**

- invalid cancellation_reason_id (please refer for [order cancellation codes](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit#))

## Flow 3

- similar issues as Flow 1

**/on_select**

- context/timestamp difference between /on_select and /select should be smaller than 5 sec
- Message Id for /select and /on_select api should be same

**/on_update**

- extra line item with id:1061 and count:0 not required

## Flow 4

- similar issues as Flow 1

**/on_status**

- Order id in /confirm and /on_status do not match

**/on_update**

- item price will be 0 for liquidated item as count is 0 (item price = count*unit price)

## Flow 5

- similar issues as Flow 1

@paragcp

**Comment by paragcp** [comment]
@abhinavv245 I hope these are only issues found and when we fix them we should be good to go,right?

**Comment by paragcp** [comment]
@abhinavv245 the below mentioned fields in the comments is not present in the contract 1.1.0 of on_update response (liquidate flow)
1. order must have required properties 'payment', 'created_at', 'updated_at'
2. /fulfillments must have required property '@ondc/org/provider_name'
3. /quote must have required property 'ttl'

Kindly look into this and update us on the same.

**Comment by abhinavv245** [comment]
Hi @paragcp 
As mentioned in the notes of the contract, /on_update should return the same information as /on_status i.e. the audit trail for items (including returns, cancels processed or in-progress), the current state of order items & fulfillment, order quote and breakup, settlement trail (if available). Please go through the contract thoroughly and implement the above mentioned feedback. Kindly make sure no new issues are induced while fixing these ones.

**Comment by kushagraj24** [comment]
@abhinavv245 If we have delivery charges as 0 do we still need to send it in quote if state is serviceable?

**Comment by kushagraj24** [comment]
@abhinavv245 Any update?

**Comment by abhinavv245** [comment]
Hi @kushagraj24 , Yes we need to send it even if it is 0.

**Comment by paragcp** [comment]
@abhinavv245 @bluecypher Please merge and verify the logs.

**Comment by paragcp** [comment]
Please update.

**Comment by abhinavv245** [comment]
Hi @paragcp , we have received the logs, we will update the issue board after verification. (ETA is 2-3 days).

**Comment by abhinavv245** [comment]
## Flow 1


**/on_select**

- invalid attributes 'ondc_org_item_id' and 'ondc_org_title_type' in quote.breakup (delivery charges)
- quote.price.value does not match with the price breakup (should match decimal places)


**/on_status**

- order.updated_at should match context.timestamp (for all fulfillment or order state changes)
- delivery(/fulfillments/end/time/timestamp) time should match context.timestamp for fulfillment state 'Order-delivered'
- inconsistencies in the billing object( why was depracated attribute 'door' added in /on_status)


**/on_update**

- quote.price.value does not match with the price breakup 
- pickup(/fulfillments/start/time/timestamp) and delivery(/fulfillments/end/time/timestamp) time cannot change in  /on_update

**/on_status (After update)**
- unsolicited call after /on_update is not required
- delivery time and pickup time missing
- order.updated_at should match the context.timestamp of the last /on_update call (liquidated)

## Flow 2


**/on_select**

- Why are there inconsistencies in the breakup of serviceable and non-serviceable /on_select apis? (tax, misc not present in non-serviceable)

**/on_status (after cancel)**

- unsolicited /on_status after /on_cancel not required
- order.updated_at should be updated as per context.timestamp on /on_cancel

## Flow 3, Flow 4, Flow 5

- similar issues as Flow 1

@paragcp @kushagraj24

**Comment by paragcp** [comment]
@abhinavv245 
Please find the comments below and clarify.
1. Why are there inconsistencies in the breakup of serviceable and non-serviceable /on_select apis? (tax, misc not present in non-serviceable)

**Comment**: tax, misc are not present in the contract itself of non-serviceable.

2. inconsistencies in the billing object( why was deprecated attribute 'door' added in /on_status)
**Comment**: As per the contract 'door' is to be deprecated and not deprecated yet. If 'door' is removed from the on_status call it will be removed from other calls too and I hope that should be acceptable.

Though we are following the contract but the raised issues are not clearly mentioned in the contract doc.We will work on the above issues but it would be better if we can have all the issues in a single log submission to avoid rework and rescoping of the tasks.

**Comment by abhinavv245** [comment]
Hi @paragcp 

The contract needs to be followed but the examples are for your reference and need not be copied exactly.

1. The payload you are referring to for non serviceable is just an example and not the complete payload. However if you read the footnotes on page 23, it mentions tax, misc charges should not be included only if they are 0.
2. The 'door' attribute was not present in /on_confirm, the consistency should be maintained thereafter. 

Also, if you require any further assistance, we can set up a call or feel free to reach out on Slack.

**Comment by abhinavv245** [comment]
## All Flows

**/on_status_picked**

- invoice should be provided in /documents for fulfillment state 'Order-picked-up' and thereafter

**/on_status_delivered**

- pickup time (/start/time/timestamp) can't change (should remain same as in "Order-picked-up" state) 

## Flow 2

**/on_search**
- category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id

@paragcp

**Comment by abhinavv245** [comment]
## All Flows

**/on_confirm**

- TAT is 60 minutes, however delivery range( fulfillments/end/range/start) surpasses the given TAT (what logic is being used here)

## Flow 2

**/on_select (non-serviceable)**

- delivery line item should not be present in case of non-serviceability 

# Flow 3

**/on_update (Return rejected)"**

- delivery timestamp (/end/time/timestamp) can't change  (date has changed)

## Please check for similar issues in all the flows before resubmitting

@paragcp

**Comment by paragcp** [comment]
@bluecypher /on_select we have only one fulfilment and all the selected items are mapped with that fulfilment_id=provider_id. We don't allow multiple fulfillments.

**Comment by bluecypher** [comment]
@BLR-0118, the Chaipoint seller app logs (v1.1.0) seem fine. Please proceed with your review.

**Comment by kushagraj24** [comment]
@BLR-0118 Any update on the logs?
