### ISSUE TITLE
Magicpin buyer app - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#583]
1. Context.ttl should be 30s (PT30S) for all APIs;
2. From the demo, it seems there are 2 searches (for crawling, live search). 
- Is the same transaction_id being used for a complete end-to-end transaction for a buyer (/search, /select, /init, /confirm) in live search? - Does crawling & live search use the same transaction_id?
3. /confirm:
- fulfillment.end.person.name is mandatory;
- quote.breakup: no title_type for packaging charges;
4. Any timers for pre-order APIs (/search, /select, /init, /confirm)?

**Comment by BLR-0118** [comment]
@ojasagarwal09

**Comment by tarosh3** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
Also, we discussed today about supporting status push (thru unsolicited /on_status) which will come in next version. However, supporting cancel push (unsolicited /on_cancel) is mandatory. Is this available?

**Comment by BLR-0118** [comment]
@tarosh3

**Comment by kunalgup** [comment]
The first page which we call as the discovery page is powered by magicpin using its internal apis.

**Comment by kunalgup** [comment]
By cancel push do you mean allowing the user to cancel food order? If yes, we don't intend to support that right now. Why is this mandatory?

**Comment by BLR-0118** [comment]
No, cancel push is when merchant cancels the order. This happens quite often.

**Comment by kunalgup** [comment]
we are handling cancel push from the merchant in this version itself.

**Comment by kunalgup** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
1. Pls confirm if all issues 1,2,3,4 mentioned above have been addressed;
2. request you to increase the timer to 4 sec (for /select, /init, /confirm) for now;
@kunalgup

**Comment by kunalgup** [comment]
For both 1. and 2. we have done the checks. Let me know how do we proceed with the next steps

**Comment by BLR-0118** [comment]
logs approved for v1.1.0
