### ISSUE TITLE
VirancInfotech - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#605]
## Flow 1

**/on_search**
- bpp/providers[].categories is not required.

**/on_select**
- provider.locations[] is not required

**/on_init**
- /quote must have required property 'ttl'
- /payment must have required property '@ondc/org/settlement_details'

**/on_confirm**

- instructions should have name and short_desc as key
- /fulfillments/ start and end descriptor is an invalid key
- /fulfillments/contact is an invalid key

**/on_status**

- updated_at timestamp should be updated as per the fulfillment state
- /fulfillments/start/time/timestamp should be updated as per the context.timestamp when state is Order-picked-up/Out-for-delivery/Order-delivered
- /fulfillments/end/time/timestamp should be updated as per the context.timestamp when state is Order-delivered

**/on_update**
- /items/1 must have required property 'fulfillment_id'

## Flow 2,3,4,5

- similar issues as Flow 1

@viranc1

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- empty array for schedule.holidays should be "[]";
2. /on_select:
- delivery charge line item in quote is mandatory;
3. /on_init:
- fulfillment.start.location is not required as per API contract;
3. /on_status_packed: invoice should be added when order is picked up;
4. pickup time in /on_status_picked_up is different from /on_status_out_for_delivery;

Flow 2
====
1. Why is transaction_id for /select & /select_unserviceable different?

**Comment by BLR-0118** [comment]
@viranc1

**Comment by BLR-0118** [comment]
Flow 2:
1. Still not clear why the transaction id for select & select_unserviceable are different? The flow should be exactly as per the test scenario with the same transaction id.
Pls resubmit logs for flow 2

**Comment by BLR-0118** [comment]
@viranc1

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
@viranc1
