### ISSUE TITLE
Razorpay (RSP) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#606]
context.key is an invalid key
context.city should be the same as in /collector_recon
context.timestamp should be the timestamp of initiation of the API call

**/collector_recon**

- deduction_by_collector value can't be 0 when @ondc/org/buyer_app_finder_fee_amount is 12
- settlement_reason_code can't be 01 (settled)
- settlement_status should be NOT-PAID in /collector_recon
- /payment/@ondc/org/settlement_details/settlement_amount can't be greater than payment.params.amount in /collector_recon
- invoice_no can't be same for 2 orders
- created_at and updated_at timestamps should match context.timestamp

**/settle**

- context.timestamp should be rfc3339 format (ms should be of 3 digits)

**/on_settle**

- Many invalid keys such as payer and payee information (refer API contract)

**/receiver_recon**

- settlement timestamp and orderbook updated_at timestamp should be the context.timestamp in /on_settle
- @ondc/org/settlement_details settlement_reference should be the settlement_reference_no in /on_settle
- order_recon_status should be 01 (provisional) in /receiver_recon

**/recon_status**
- context.domain can't change in /recon_status

@ankur-a

**Comment by bluecypher** [comment]
context.ttl should be as per the API contract

**/settle**

- timestamp difference between /collector_recon and /settle can't be of 4 days (check the defined TTL in API contract)

**/on_settle**

- context.timestamp can't be same for /settle and /on_settle

**/receiver_recon**

- context.timestamp can't be the same as in /settle
- order_recon_status attribute is missing

**/on_receiver_recon**

- context.timestamp can't be the same as in /receiver_recon

**/on_collector_recon**

- context.timestamp can't be the same as in /collector_recon

**/recon_status & /on_recon_status**

- similar timestamp issue as above



@ankur-a

**Comment by ankur-a** [comment]
@bluecypher please find PR with comments addressed https://github.com/ONDC-Official/verification-logs/pull/632

**Comment by bluecypher** [comment]
Logs Approved (conditional sign-off)
