### ISSUE TITLE
Delcaper - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#654]
## Flow 1

- City code mismatch in /action and /on_action
- /message/catalog/bpp/providers/items/id must be string
- /message/catalog/bpp/providers/items/parent_item_id must be string

**on_search**

- items.descriptor.short_desc should be in sync with the category_id (suitable description should be provided for the mentioned category_id)
- Invalid category_id for RTO quote in /items
- item.time.timestamp cannot be future dated (should match context.timestamp)

**on_init**

- Invalid title_type "GST" in /quote/breakup (delivery charge should be tax inclusive)

**on_confirm**

- /message/order/fulfillments/0/tracking must be boolean
- additional attributes (@ondc/org/order_ready_to_ship,fulfillment.start and fulfillment.end,cancellation_terms,tags) not required in /on_confirm 
- updated_at timestamp should be updated as per the context.timestamp

**on_status**

- /message/order/fulfillments/0/tracking must be boolean
- payment object cannot be null
- similar issues as /confirm Api

**on_update**

- shipping label is missing in /message/order/fulfillments/0/start/instructions/images
- pickup(fulfillments/start/time) and delivery time(fulfillments/end/time) should be provided if ready to ship tag is 'yes' in /confirm
- updated_at timestamp should be updated as per the context.timestamp

**Comment by vomayank** [comment]
@bluecypher compliance check Issue Has been Fixed and Raised PR For It

**Comment by abhinavv245** [comment]
**/on_confirm** 
- order.updated_at should be updated as per the context.timestamp
- additional attributes (@ondc/org/order_ready_to_ship) not required in /on_confirm
- fulfillments.start and fulfillments.end required only if '@ondc/org/order_ready_to_ship'=yes in /confirm

**/on_status**
- fulfillment type cannot change in /on_status (should be ON-ORDER)
- order.updated_at should be updated as per context.timestamp
- fulfillments.start.time.timestamp missing in case of unsolicited /on_status API when fulfillment state is 'Order-picked-up'
- fulfillments.end.time.timestamp missing in case of unsolicited /on_status API when fulfillment state is 'Order-delivered'

**/on_update**
- order.updated_at should be updated as per context.timestamp
- fulfillments.end.time.range is required when 'order_ready_to_ship'=yes

**/on_cancel**
- context.timestamp cannot be same as /cancel API

@vomayank

**Comment by vomayank** [comment]
@abhinavv245 compliance check Issue Has been Fixed and Raised PR For It and also added New Logs With Mytra Money

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- same day delivery should not take entire day for delivery (P1D)
- time.timestamp for 'Next Day Delivery' should be for the next day (date)

**/on_init**

- Delivery charge should be tax inclusive, tax line item should not be present

**/on_confirm**
- fulfillment details need not be replicated in /on_confirm (refer v1.1.0 for all the required properties)
- auto RTS should be supported in /on_confirm

**/on_update**

- time range should be provided in /on_update when RTS was initiated in /update
- additional attribute (@ondc/org/order_ready_to_ship) not required in /on_update
- order.updated_at should be updated as per context.timestamp

**/on_status**

-  additional attribute (@ondc/org/order_ready_to_ship) not required in /on_status
- order.updated_at should be updated as per context.timestamp for all unsolicited /on_status calls as fulfillment states are changed
- order picked up time should not be present when agent is assigned (only when order is picked)

## Flow 2

- similar issues as Flow 1

**/on_cancel**

- time difference between /cancel and /on_cancel apis should be less than 5 sec

@vomayank

**Comment by abhinavv245** [comment]
Hi @vomayank okay, that's fine then.

**Comment by vomayank** [comment]
@abhinavv245 I have Update the Issue As Mentioned above and raised PR For It Please review with viranc infotech.

**Comment by SauAg383** [comment]
@BLR-0118 @abhinavv245 @bluecypher Review the logs as it had been more than a week after merging.
