### ISSUE TITLE
BuyNxt - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#717]
## Flow 1

**/on_search**

- /message/catalog/bpp/providers/items/category_id must be equal to one of the non deprecated categories [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=1764580788)
- context/ttl is not required
- Timestamp must be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) UTC Format
- bpp/providers/time/timestamp must be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) UTC Format
- context/timestamp difference between /on_search and /search should be smaller than 5 sec
- frequency and times attributes should not be present in case of fixed store timings
- available count of item should be smaller or equal to the maximum count (/bpp/providers/items/quantity)

**/on_select**

- '@ondc/org/time_to_ship'(O2S) in /on_search cannot be equal to '@ondc/org/TAT'(O2D) in /on_select
- Delivery line item must be present in quote/breakup

**/on_init**

- /fulfillments/0/end/location/address must have required property 'building'
- /quote must have required property 'ttl'
- /quote/breakup/@ondc/org/item_quantity/count must be an integer
- fulfillments/end/location/gps mismatches in /init and /on_init
- /payment/@ondc/org/buyer_app_finder_fee_type should be 'percent' instead of 'Percent'
- Buyer app finder fee can't change in /on_init (should be the same as in /search)
- Billing object mismatches in /init and /on_init
  (building is missing, created_at and updated_at timestamps should be same and in the correct format)
- Quoted Price does not match with Net Breakup Price in /on_init (quote.price.value = Σ quote.breakup[].price.value)
- item's unit price (quote/breakup/item/price) is missing in quote/breakup
- quote/breakup/price is the total price of an item (count\* unit price)
- many invalid attributes in payment object ("type","collected_by","@ondc/org/withholding_amount","@ondc/org/return_window","@ondc/org/settlement_basis","@ondc/org/settlement_window"). Refer [Retail API contract v1.1.0](https://docs.google.com/document/d/1fefHfMoYIouN-QJTDJFFZm46dqHmFvwY-6ICoISJcUY/edit#heading=h.90znb27iapdt)

**/on_confirm**

- order/id must be the same as in /confirm
- order timestamps must be in the correct format (RFC339 UTC)
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)
- payment/params/transaction_id is generated after the payment is successful

**/on_status**

- all order status updates should be sent via separate unsolicited /on_status API calls
- /items/tags not required
- 'CANCELABLE' is not a valid fulfillment state
- fulfillments/start/time/timestamp (pickup time) and fulfillments/end/time/timestamp (delivery time) cannot be same when fulfillment state is 'Order-delivered'
- order.updated_at timestamp should match context.timestamp

**/on_update**

- all return flows should be sent via unsolicited /on_update API calls
- /items/tags are only required for the returned items
- fulfillments object should be as per the API contract (many details are missing)
- items can either be liquidated or returned with Reverse QC.
- quote price should be updated in case 'Return_Picked' or 'Liquidated' item.
- Liquidated line item should be present in quote/breakup with the item price 0.

## Flow 2

- similar issues as Flow 1

**/on_cancel**

- unsolcited /on_cancel should be implemented

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

**/on_select**

- Flow for 'item quantity not available' should be implemented

## Flow 5

- similar issues as Flow 1

**/on_select**

- Flow for 'item out of stock' should be implemented

@pranav-buynxt

**Comment by abhinavv245** [comment]
## Flow 1

- All timestamps should be in RFC 3339  "UTC" format
- context/timestamp difference between /on_action and /action should be smaller than 5 sec

**/on_search**
- Either one of fixed (range) or split (frequency and times) timings should be provided in /bpp/providers/locations/time
- category in serviceability construct should be one of the category ids bpp/providers/items/category_id

**/on_select**
- '@ondc/org/TAT' for 'Immediate Delivery' is 60 minutes max 

**/on_init**
- Billing object mismatches in /init and /on_init
(created_at and updated_at timestamps should be same)
- Discrepancies between the quote object in /on_select and /on_init
(Delivery charges are missing in /on_init)


**/on_confirm**
- order.created_at timestamp cannot change in /on_confirm
- Discrepancies between the quote object /on_select and /on_confirm (delivery charges missing)
- payment object mismatches in /confirm & /on_confirm
(upi_address, uri, tl_method are missing in /on_confirm)

**/on_status**
- all order status updates should be sent via separate unsolicited /on_status API calls (in separate files)
- pickup(fulfillments/start/time/timestamp) and delivery(fulfillments/end/time/timestamp) time cannot be provided when order fulfillment state is 'Pending'
- delivery line item missing in quote.breakup
- order.created_at should not change in /on_status
- /payment/params/transaction_id cannot be provided unless the order has been delivered.

**/on_update**
- all return flows should be sent via unsolicited /on_update API calls(in separate files)
- pickup time (fulfillments[0]/start/time/timestamp) and delivery (fulfillments[0]/end/time/timestamp) time should not change in /on_update 
- pickup time (fulfillments[1]/start/time/timestamp) and delivery time (fulfillments[1]/end/time/timestamp) cannot be same for Reverse QC when fulfillment state changes to Order delivered'
- delivery line item missing in quote.breakup
- quote.price should not be updated for 'Return_Approved' item

## Flow 2, Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

- Flow for 'item quantity not available' should be implemented 

## Flow 5

- similar issues as Flow 1

- Flow for 'item out of stock' should be implemented

@pranav-buynxt

**Comment by abhinavv245** [comment]
## Flow 1

- invalid payload for select (on_select payload provided)

**/on_select**

- '@ondc/org/TAT' (O2D) in /on_select cannot be equal to '@ondc/org/time_to_ship' (O2S) in /on_search 

**/on_status (all)**

- order.created_at timestamp should not change in /on_status
- quote object mismatches in /on_select and /on_status
(item price and unit price are different for item id: 246024)

**/on_update**

- created_at, updated_at, payment object missing in /order
- /fulfillments must have required property '@ondc/org/provider_name'
- quote object mismatches in /on_confirm and /on_status
(item price and unit price are different for item id: 246024)
- /quote/breakup/ must have required property 'title'
- /quote must have required property 'ttl'

**on_update (return approved)**

- In /items , fulfillment_id for item id:246024 should be updated (Reverse QC)

**on_update (return picked up and return delivered)**

- quote.price and quote.breakup should be updated
 (returned item's quantity and price should be 0)

## Flow 2, Flow 3, Flow 4, Flow 5

- similar issues as Flow 1

@pranav-buynxt

**Comment by abhinavv245** [comment]
## Flow 1, Flow 3, Flow 4

**/on_update**
- 'payment' object is missing in /on_update

## Flow 2

**/on_select (non-serviceable)**

- delivery line item should not be present in case of non-serviceability

@pranav-buynxt

**Comment by abhinavv245** [comment]
## All Flows

**/on_search**

- context/timestamp difference between /on_search and /search should be smaller than 5 sec

**/on_status (Delivered)**
- /payment/status must be equal to constant (PAID)

**/on_update**
- /payment/status must be equal to constant (PAID)

@pranav-buynxt

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- fulfillment_id should be "1" in case of Delivery in /bpp/providers/items/fulfillment_id

**/on_confirm**

- billing object must be the same as in /confirm ("door attribute is not present in /confirm")
- fulfillments[0].end.location gps mismatches in /confirm and /on_confirm
- test your logs with pre-paid order (which is currently being supported on-network)

**/on_status**

- agent and vehicle info are optional (required only in case of last-mile and kerb-side pickup respectively)

**/on_status (out-for-delivery)**

- /fulfillments/start/time/timestamp is the pickup time (should match the timestamp of Order-picked-up fulfillment state)

**/on_update**

- start and end time ranges must be in RFC3339 UTC format

## Flow 4

**/on_select**

- item quantity can't be unavailable when item: 246042 is in stock (available and maximum counts of item are more than the selected count)
##

#### all the flows should be corrected as per the above feedback (wherever applicable)



@pranav-buynxt

**Comment by bluecypher** [comment]
**/on_search**

- Reverse geocoding of store location is giving a different pincode. What logic is being used?

**/on_select**

- fulfillment_id is same as provider id. How is it handled in case of multiple fulfillments?

**/on_confirm**

- estimated pickup and delivery time ranges are missing in /fulfillments
- serviceability must be configured properly (radial distance between delivery and pickup locations exceeds the defined limit)

**/on_status**

- why did the delivery GPS coordinates change?
- Why are instructions (proof of pickup and delivery) being sent when the order is accepted?
- why is door attribute added in /fulfillments/end/location/address and /billing/address? (It wasn't present when order was confirmed)
- estimated delivery and pickup time ranges must be in "RFC3339" UTC format
- Invoice url must be present as part of documents objects (in Order-picked-up state and thereafter)

**/on_update**

- Why was the return initiated again for item:246025 after it was already picked up for return? This should be configured and handled correctly.


@pranav-buynxt

**Comment by bluecypher** [comment]
**/on_search**

- issue with geocoding of store location still not resolved (area_code not matching)

**/on_update return_picked**

- returned item's unit price should not be 0
- time ranges should be in RFC3339 UTC format

## Flow 2

**on_select (non-serviceable)**

- Isn't the fulfillment end location within the serviceability radius. If yes, how is it non-serviceable?


@pranav-buynxt

**Comment by ashu2187** [comment]
Hi Team, we have corrected and updated logs. kindly review it ASAP.

**Comment by bluecypher** [comment]
## Flow 5

**/on_select:** item's unit price can't be 0 (OOS item 357419). 

Please re-upload the logs for flow 5.

@pranav-buynxt

**Comment by bluecypher** [comment]
@BLR-0118, the BuyNxt Seller App logs seem fine, please proceed with your review.
