### ISSUE TITLE
Oogashop - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#720]
## Flow 1

- context/timestamp can't be same for /action and /on_action APIs

1. **/search**

   - search by item should be implemented for log validation process

2. **/on_search**

   - /message/catalog/bpp/providers/ttl must match format "duration"
   - /message/catalog/bpp/providers/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
   - /message/catalog/bpp/providers/items/quantity/maximum/count must be string
   - /message/catalog/bpp/providers/items/quantity/available/count must be string
   - /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'nutritional_info'
   - /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'additives_info'
   - /message/catalog/bpp/providers/fulfillments/contact/phone must NOT have more than 11 characters
   - bpp/providers/category_id is an invalid attribute
   - invalid attributes "id", "type", "@ondc/org/category", "provider_id" in bpp/providers/fulfillments
   - invalid attributes "range", "days", "schedule" in bpp/providers/time
   - Either one of fixed (range) or split (frequency and times) timings should be provided in /bpp/providers[0]/locations[0]/time
   - @ondc/org/contact_details_consumer_care should be in the format "name,email,contactno" in /bpp/providers[0]/items
   - available count of item should be smaller or equal to the maximum count (/bpp/providers[0]/items[3]/quantity)
   - available count of item should be smaller or equal to the maximum count (/bpp/providers[0]/items[38]/quantity)
   - available count of item should be smaller or equal to the maximum count (/bpp/providers[0]/items[85]/quantity)
   - category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id

3. **/on_select**

   - invalid mapping of item id and fulfillment id in /order/items (an item should be mapped to only 1 fulfillment) both items support only "Delivery" as per /on_search (/items/fulfillment_id)
   - /quote/breakup/item must have required property 'price' (unit price of item)
   - /quote/breakup/item/quantity/maximum/count must be string
   - /quote/breakup/item/quantity/available/count must be string
   - @ondc/org/TAT (O2D) in /on_select can't be equal to @ondc/org/time_ship (O2S) in /on_search in /fulfillments[1]/
   - delivery line item must be present in quote/breakup

4. **/on_init**

   - items/fulfillment_id mismatches in /on_select and /on_init
   - email missing in billing object

5. **/on_confirm**

   - /payment/params must have required property 'transaction_id'
   - order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)
   - billing object should remain same as in /init
   - discrepancies between the quote object /on_select and /on_confirm
   - invalid attribute items/quantity/measure
   - Quoted Price in /on_confirm 45.6 does not match with the quoted price in /on_select undefined
   - payment object mismatches in /confirm & /on_confirm
   - fulfillments start and end time ranges should be in RFC3339 UTC format

6. **/on_status**

   - order states and fulfillment states update should be provided through unsolicited /on_status

7. **/on_update**

   - must have required property 'payment'
   - must have required property 'created_at'
   - must have required property 'updated_at'
   - return flow should be as mentioned in test case scenario document

8. **/on_support**

   - context/message_id for /support and /on_support api should be same
   - context/timestamp can't be before /support API

## Flow 2

- Not as per the API Contract (Non-serviceable flow and seller cancellation is missing)

## Flow 3, 4, 5

- Entire transaction flow should be submitted as mentioned in the test case scenario document

**Comment by bluecypher** [comment]
Please re-run the utility as mentioned in the [README.md](https://github.com/ONDC-Official/reference-implementations/blob/main/utilities/log-validation-utility/README.md) and resolve the issues as identified by the utility reports.

**Comment by oogashop** [comment]
Hi @bluecypher we have re-ran the utility as mention in the above file and made the necessary changes accordingly. Please have a look once again and suggest accordingly.

**Comment by bluecypher** [comment]
**/on_search**

#### Catalog Issues:

- Why "Fruits and Vegetables" category_id is used for ghee and biscuit products?
- items/descriptor/code is optional attribute (if not available)
- contact no should be of 10 or 11 digits in @ondc/org/contact_details_consumer_care
- invalid attributes id,type,category,provider_id,provider_name in /bpp/providers/fulfillments

**/select**

- use a different delivery location for realistic use case; can't be the same as store location

**/on_select**

- Immediate delivery should only be used where TAT <= 60 mins; use appropriate delivery type
- "Delivery and Self-Pickup" is not a valid fulfillment type as per the catalog shared in /on_search

**/on_confirm**

- Why estimated pickup and drop timestamps same?
- milliseconds values should be of 3 digits in time ranges (pickup and drop)
- invalid attribute "measure" in /items/quantity (in /on_confirm and thereafter)

**/on_status**

- How can order state be "In-progress" when fulfillment state is still "pending"

**/on_update (Return_Delivered)**

- entire settlement trail should be maintained in "@ondc/org/settlement_details" (missing refund details)

@oogashop

**Comment by oogashop** [comment]
Hi @bluecypher , we have submitted logs as per above suggestions at https://github.com/ONDC-Official/verification-logs/pull/968 . Please have a look.

**Comment by bluecypher** [comment]
**/select**

- use a different delivery location for realistic use case; can't be the same as store location

**/on_confirm**

- PCC/pickup details are provided in /start/instructions

**/on_status**

- valid URL of invoice should be provided in /documents/url

@oogashop, Please resubmit for Flow 1

**Comment by oogashop** [comment]
Hi @bluecypher ,
We have taken care of these too and submitted flow 1 again at https://github.com/ONDC-Official/verification-logs/pull/976 . Please review them.

**Comment by bluecypher** [comment]
**/on_status**
- invalid pickup instructions (attribute is optional)

@oogashop

**Comment by oogashop** [comment]
Hi @bluecypher ,
We have taken care of these suggestions too. Please have a look on https://github.com/ONDC-Official/verification-logs/pull/1012

**Comment by bluecypher** [comment]
@BLR-0118, the Oogashop seller app logs (v1.1.0) seem fine. Please proceed with your review.

@oogashop team, the store address and GPS mapping should be precise in Flow 1.

**Comment by oogashop** [comment]
Hi, we have taken care of that and will not happen any more. Last time the error was only because we mistakenly entered wrong shop coordinates manually for testing. But for real case scenarios, we never put shop coordinates manually.
