### ISSUE TITLE
Xpressbees - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#745]
## Flow 1

- time difference between /action and /on_action apis should be less than 5 sec

**/on_search**

- support for child categories of standard delivery such as 'next day', 'same day' should be supported.
- additional attribute timestamp is not required in /categories
- descriptor should consist of 'RTO quote' as a part of name

**/on_init**

- @ondc/org/settlement_details is an optional property
- @ondc/org/settlement_details (if present) should have required property 'beneficiary_name'
- As the payment is collected by BAP, 'settlement-counterparty' will be seller-app 
- 'settlement_type' should be 'neft' (in lower case)

**/on_confirm**

- auto RTS should be supported in /on_confirm
- pickup and delivery time (range) should be provided once the order is ready to ship
- how is consignment getting created without RTS in /confirm or /update call?

**/update**
- RTS missing

**/on_status**
- unsolicited calls for fulfillment state 'Order-picked-up' and 'Order-delivered' should be provided

## Flow 2

- similar issues as Flow 1

**/on_status (after cancel)**

- is RTO initiated before order cancellation?

@ashwinkumarkuntla

**Comment by ashwinkumarkuntla** [comment]
@tanya-ondc 

As discussed, resolved on_confirm created_at issue.

Kindly review

**Comment by bluecypher** [comment]
## Forward Flow

**/on_search**

- Time over 24Hrs should be converted into days and hrs
- item level duration can't be 32 hrs, should be according to the timestamp provided.

**/on_update**

- shipping label should be provided for P2H2P orders
- estimated delivery time ranges should also be provided when rts call is received

**/on_status (unsolicited calls)**

- delivery time ranges can't be earlier than pickup time ranges
- on_status (order-picked-up): invalid pickup timestamp (start/time/timestamp), can't be before order confirmation time
- on_status (order-delivered): invalid capture of delivery timestamp (end/time/timestamp)

Why are there differences in order timestamps in solicited and unsolicited calls?

## RTO Flow

- similar issues as Forward Flow
- /on_status_cancelled: RTO initiated pickup time range can't be earlier than /on_cancel timestamps


@ashwinkumarkuntla

**Comment by bluecypher** [comment]
- order state can't change from "Accepted" in /on_confirm to "Created" in /on_status later

## RTO Flow

**/on_status (Order-picked-up)**

- pickup timestamp should match context timestamp and can't be future dated


@ashwinkumarkuntla

**Comment by ashwinkumarkuntla** [comment]
Resolved reported issues and resubmitted logs.

Kindly review.

@bluecypher

**Comment by bluecypher** [comment]
- email is optional in fulfillment/start and fulfillment /end (should not be considered as a required field during schema validation)
-  Does the system support other states of RTO such as "RTO-Delivered" and "RTO-Disposed"?


@ashwinkumarkuntla

**Comment by ashwinkumarkuntla** [comment]
- Email: Yes, email is optional in fulfillment/start and fulfillment /end. (As per schema validation it is optional field.)
- RTO states: Yes, we do support "RTO-Delivered" state. In near feature we are planning to support "RTO-Disposed".

@bluecypher

**Comment by bluecypher** [comment]
@ashwinkumarkuntla, supporting all the states of RTO is a mandatory requirement.

**Comment by ashwinkumarkuntla** [comment]
- We are working on 'RTO-Disposed' flow, will submit the 'RTO-Disposed' logs in couple of days.
- Submitted IGM logs, Kindly review it.

@bluecypher

**Comment by ashwinkumarkuntla** [comment]
- Submitted RTO-Disposed and RTO-Delivered logs, Kindly review it.

@bluecypher

**Comment by bluecypher** [comment]
@BLR-0118, the Xpressbees LSP (v1.1.0) logs seem fine. Please proceed with your review.

@ashwinkumarkuntla
