### ISSUE TITLE
Xpressbazaar (Shikhar) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/verification-logs#761]
## Flow 1

**/on_search**

- /message/catalog/bpp/providers/locations/time/schedule/holidays must match format "date"
- /message/catalog/bpp/providers/items veg/non-veg categorization is mandatory for F&B categories or packaged foods in /tags
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'imported_product_country_of_origin' (must be in ISO 3166-1 alpha-3 code format)
- store enable/disable timestamp (/bpp/providers/time/timestamp) must match context.timestamp
- fulfillment_id in /bpp/providers/items should map to one of the fulfillments id in bpp/fulfillments
- @ondc/org/contact_details_consumer_care should be in the format "name,email,contactno" in /bpp/providers/items
- serviceability construct should be correctly defined (currently hyperlocal(5km) but delivering at 1000km, it can cause the catalog not being shown)

**/on_status (Packed)**

- pickup(/fulfillments/start/time/timestamp) and delivery(/fulfillments/end/time/timestamp) timestamps cannot be provided when the order is packed

**/on_status (Order picked up)**

- pickup time should be after the order has been packed
- delivery timestamp cannot be provided

**/on_status (Delivered)**

- why is it taking time (> 3 sec) to call on_status after the order has been delivered?

**/on_update (return approved and liquidated)**

- Either return can be approved or liquidated (both cannot be done simultaneously)
- Message Ids for /update and all /on_update apis (unsolicited) should be same (temporarily)
- invalid attribute 'start' inside /fulfillments/start
- why is fulfillment state 'Pending' as the order has been already delivered
- quote.breakup should not be changed for 'Return Approved'
- Reverse QC fulfillment should be created for the returned item in case of 'Return Approved'
- pickup time should not change in /on_update

## Flow 2

- similar issues as Flow 1

**/on_select (non-serviceable)**

- delivery line item not required in case of non-serviceability
- fulfillments/state/descriptor/code should be 'Non-serviceable' as the location is not serviceable

**/on_init**

- Billing object mismatches in /init and /on_init
 (deprecated attribute door is added in /on_init)

 **/on_cancel**

 - approproate cancellation code to be used (refer [cancellation codes](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit#))

## Flow 3

- similar issues as Flow 1

## Flow 4

- similar issues as Flow 1

**/on_select**

- '@ondc/org/item_quantity' should be updated as the quantity.available.count (only for the item whose selected quantity is not available) and quote price should be updated accordingly

## Flow 5

- similar issues as Flow 1

**/on_select**

- In /items, available and maximum quantity missing
- quote price does not match the breakup price

@Rajnishekhawat

**Comment by Rajnishekhawat** [comment]
Hi @abhinavv245  we have submitted Shikhar App logs pls Review that PR link :- https://github.com/ONDC-Official/verification-logs/pull/798

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**
- incorrect mapping of gps and address of store location. (reverse geocding shows different pincode)

**/on_select**
- /fulfillments/@ondc/org/TAT (O2D) in /on_select can't be equal to @ondc/org/time_ship (O2S) in /on_search 
- quote.price.value does not match with the price breakup

**/on_init**
- Discrepancies between the quote object in /on_select and /on_init
(packing charges are not there in /on_select)
- @ondc/org/item_id for 'Packing charges' should match with the fulfillments/id

**/on_status_out_for_delivery**

- delivery timestamp cannot be provided as the order has not been delivered yet

**/on_update**

- pickup timestamp (/fulfillments/start/time/timestamp) cannot change in /on_update

**/on_update_liquidate**

- start timestamp missing in fulfillments/end/time/range
- delivery timestamp (fulfillments/end/time/timestamp) is missing
- Message Ids for /update and all /on_update apis should be same (temporarily)

## Flow 2

- similar issues as Flow 1

## Flow 3

- similar issues as Flow 1

**/on_status_picked**

-  end timestamp (/fulfillments/end/time/range/end) is not accurately recorded

## Flow 4

- similar issues as Flow 1

**/on_select**

- item with id: d9ba4a31-edb2-4e7e-b23c-6031d2723ed9 is not present in /on_search
- available count can't be greater than maximum count for item id: 2e630e85-4ae4-4fab-92cf-5dee1341101e
- @ondc/org/item_quantity/count should be updated as per the available count (for the item whose selected quantity is not available)

**/on_init**

- /billing/address must have required property 'building' (if it is not sent by buyer app, seller app should send NACK)

## Flow 5

- similar issues as Flow 1 and Flow 4

**/on_select**

- /quote/breakup/1/price/value must be string
- fulfillment_id for item 782281a1-59c4-4171-b154-f6852a57082a cannot be an empty string
- Item's unit and total price mismatch for id: 782281a1-59c4-4171-b154-f6852a57082a

@Rajnishekhawat

**Comment by abhinavv245** [comment]
## All Flows

**/on_select**

- time to ship is 1 Day and TAT is 7 Days, why is ship to delivery taking 6 days to deliver in the same city?

**/on_confirm**

- Discrepancies between the quote object /on_select and /on_confirm (@ondc/org/item_id for 'packing charges' has changed in /on_confirm)

**/on_status (Order-picked-up)**

- invoice must be provided in /documents for fulfillment state 'Order-picked-up' and thereafter

**/on_update (Return Initiated)**

- order/created_at timestamp can't change (should remain same as in /confirm)

@Rajnishekhawat

**Comment by Rajnishekhawat** [comment]
Hi @abhinavv245 and @BLR-0118 we have submitted the shikhar_App logs kindly review that PR link here:- https://github.com/ONDC-Official/verification-logs/pull/813

**Comment by abhinavv245** [comment]
## Flow 1

**/on_update (liquidated)**

- billing object is optional (inconsistency in on_update initiated and liquidated)

## Flow 2

**/on_select (non serviceable)**

- How are packing charges calculated? (as per logs, they are charged when location is serviceable but not charged when non-serviceable) 

## Flow 4

**/on_status (Order delivered)**

- incorrect payload

## Please resolve similar issues in other flows as well

@Rajnishekhawat

**Comment by Rajnishekhawat** [comment]
Hii, @abhinavv245 and @BLR-0118 we have submitted Shikhar_App logs.
Kindly review the PR link https://github.com/ONDC-Official/verification-logs/pull/820

**Comment by abhinavv245** [comment]
## Flow 1

**/on_update**

- message_id of all unsolicited /on_update calls should be same for a particular /update request

## Flow 3

**/on_update (Rejected)**

- item quantity should not change in quote/breakup when state is Return_Rejected
- quote price should not change for return state Return_Rejected
- item can't be returned when order is not delivered (fulfillment state should be Order-delivered)

## Flow 4

**/on_select**

- Count of item with id: 3720b41c-a3a7-4be8-bfb7-bc08f248132f does not match in select & on_select (suitable domain error should be provided)

@Rajnishekhawat

**Comment by bluecypher** [comment]
**/on_search**

- Despite being disabled, how is the store able to handle order fulfillment?
- Inaccurate geocoding of store location. Reverse geocoding shows different area_code.
- Are both the providers situated at the same location?
- serviceability construct should be defined for all the existing item categories
- "multiple_products_name_number_or_qty" is invalid property in statutory requirements

**/on_select**

- fulfillment/end/location is out of range as defined in the serviceability construct and yet fulfillment state is "Serviceable" (Some buyer apps won't be processing this at their end)
- fulfillments/id is same as provider/id. What happens in case of multiple fulfillments?

**/confirm**

- How can buyer app send pickup and delivery time ranges which match exactly with /on_confirm timestamps. How is this possible?


@Rajnishekhawat

**Comment by Rajnishekhawat** [comment]
@bluecypher Please merge https://github.com/ONDC-Official/verification-logs/pull/834 as it has the correct structure as you have suggested.
For fulfillments/id is same as provider/id. What happens in case of multiple fulfillment? In case of multiple fulfillment new fulfillment id will be generated.

How can buyer app send pickup and delivery time ranges which match exactly with /on_confirm timestamps. How is this possible? : we checked the incoming request was different then what we have submitted, the correct file is now in the logs.

Rest of the points we have fixed.

Please check and let us know your feedback. Happy to answer your queries.

Thanks,
