### ISSUE TITLE
Channelier - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/verification-logs#766]
- Logs have many issues, please refer to [API contract v1.1.0](https://docs.google.com/document/d/1fefHfMoYIouN-QJTDJFFZm46dqHmFvwY-6ICoISJcUY/edit#heading=h.90znb27iapdt).  Some of the issues are mentioned below:

## Flow 1

- context.key is an invalid attribute
- context/timestamp difference between /on_select and /select should be smaller than 5 sec

**/on_search**

- /message/catalog/bpp/providers/time must have required property 'label' and 'timestamp'
- /message/catalog/bpp/providers/locations must have required property 'time'
- /message/catalog/bpp/providers/locations/time/schedule/holidays must not be past dated
- /message/catalog/bpp/providers/items/quantity is not required
- /message/catalog/bpp/providers/items/category_id must be equal to one of the non deprecated categories [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'imported_product_country_of_origin' (must be in ISO 3166-1 alpha-3 code format)
- store enable/disable timestamp (/bpp/providers/time/timestamp) must match context.timestamp
- serviceability construct is missing in /catalog/tags and should be defined as per [API contract v1.1.0](https://docs.google.com/document/d/1fefHfMoYIouN-QJTDJFFZm46dqHmFvwY-6ICoISJcUY/edit#heading=h.1hw5yj27czv3)
-  veg/non-veg categorization is mandatory for F&B categories or packaged foods in /message/catalog/bpp/providers/items/tags (should be removed from /bpp/providers)
- 'categories', 'payments', 'offers' objects should be removed from /bpp/providers

**/on_select**
- /quote/breakup/item/quantity maximum and available count must be string
- /fulfillments[0]/@ondc/org/TAT (O2D) in /on_select can't be equal to @ondc/org/time_ship (O2S) in /on_search
- item with id: CU0I1 is not from the same provider in /on_search (only one provider is supported in one select call)

**/on_init**

- /fulfillments must have required property 'type'
- multiple required attributes (like buyer app finder fee, amount, etc) are missing in /payment object (refer API contract)
- provider_location object is missing in /on_init
- multiple invalid objects in /order like 'add-ons','offers','documents',etc

**/on_confirm**
- order must have required property 'created_at', 'updated_at'
- default fulfillment state should be 'Pending' in /on_confirm (instead of 'Serviceable')
- additional attributes '@ondc/org/category', '@ondc/org/TAT' not required in /fulfillments
- /fulfillments/type is missing

**/on_status**
- order must have required property 'created_at', 'updated_at'
- /fulfillments/start must have required property 'time'
- /fulfillments/end must have required property 'time'

**/on_update**
- order.updated at should be updated as context.timestamp for all unsolicited /on_update calls
- /fulfillments/state/descriptor/code must be equal to constant "Order-delivered" (instead of 'Order Delivered')
- /fulfillments/start must have required property 'time'
- /fulfillments/end must have required property 'time'
- /payment/@ondc/org/settlement_details/ must have required property 'bank_name', 'branch_name', 'settlement_phase'
- Message Ids for /update and /on_update (unsolicited as well) apis should be same (temporarily)
- fulfillment state should be Order-delivered in case of Return Approved

## Flow 2

- similar issues as Flow 1

**/on_select**

- additional attribute 'state' should be removed from /order (refer API contract v1.1.0)

**/on_confirm**

- order.updated_at should be updated as per context.timestamp (as default fulfillment state is added)

**/on_cancel**

- appropriate 'cancellation_reason_id' should be used (refer [cancellation codes](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit#))

**/on_init**
- order must have required property 'provider_location'
- /fulfillments must have required property 'type'
- @ondc/org/title_type in quote.breakup must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)
- provider_location object is missing in /on_init
- Buyer app finder fee missing in /on_init

## Flow 3

- similar issues as Flow 1

## Flow 4, Flow 5

- similar issues as Flow 1

**/on_select**

- Error object missing in case of item quantity not available/out of stock

@ravinderTechpvec18

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- catalog/tags (serviceability) is not required
- providerId is an invalid attribute in /bpp/providers/items
- reverse geocoding for the store gps cordinates shows different area code. What logic is used here?
- @ondc/org/contact_details_consumer_care should be in the format "name,email,contactno" in /bpp/providers/items
- item/quantity is should be provided

**/on_select**

- order/state is not required
- quantity is not required in /items

**/on_init**

- /billing/address must have required property 'building' (seller app should send NACK in case not provided by buyer app)
- context/timestamp difference between /on_init and /init should be smaller than 5 sec
- order/state is not required

**/on_update (Initiated)**

- item/quantity is not required in quote.breakup
- /documents is not required in /on_update

**/on_update (Return_Approved)**

- updation_id is an invalid attribute in /items
- subsequent on_update calls should be provided (return_picked, return_delivered)

## Flow 2

- similar issues as Flow 1

## Flow 3

- similar issues as Flow 1

**/on_init**

- context/timestamp difference between /on_init and /init should be smaller than 5 sec

**/on_status (Order-picked-up)**

- /fulfillments/end must have required property 'time'

**/on_status (Order-Delivered)**

- why is there a delay to trigger on_status after delivery (context/timestamp should match delivery timestamp) 

**/on_update (Rejected)**

- order updated_at timestamp should be updated as per context/timestamp

## Flow 4

- similar issues as above flows

**/on_select**

- error object is missing for item quantity not available

## Flow 5

- similar issues as above flows

**/on_cancel**

- transaction_id for cancel and /on_cancel do not match

@ravinderTechpvec18

**Comment by bluecypher** [comment]
**/on_search**

- many unwanted attributes in /bpp/providers/locations (door, name, ward, building, country)
- /message/catalog/bpp/providers/0/items/0 veg/non-veg categorization is mandatory for F&B categories or packaged foods in /tags

**/on_select**

- Standard Delivery from Delhi to Mumbai (P2H2P) is not possible in 25 Hrs
- O2S is 24 hours. How is it possible for delivery (S2D) to occur within just one hour?

**/on_init**

- category, TAT, provider name, state and images are optional attributes in /fulfillments
- invalid attributes "@ondc/org/collected_by_status"

**/on_confirm**

- pickup and drop time ranges should be in accordance with O2S (time_to_ship) and O2D (TAT) timings

**/on_status**

- /fulfillments/start/person is invalid key

#### Ques: How does the seller app handle the settlement to the buyer after refund triggering states?


@ravinderTechpvec18

**Comment by bluecypher** [comment]
## Flow 4

**/on_init**

- context/timestamp difference between /on_init and /init should be smaller than 5 sec

**/on_update (Liquidated)**

- context/timestamp can't be the same as in /on_update (initiated)


@ravinderTechpvec18

**Comment by bluecypher** [comment]
**/on_update (Approved)**

- reverse qc fulfillment pickup time range can't be earlier than context/timestamp


@ravinderTechpvec18

**Comment by bluecypher** [comment]
@BLR-0118, the Channelier Seller App logs (v1.1.0) seem fine. Please proceed with your review.

@ravinderTechpvec18
