### ISSUE TITLE
Shopalyst (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#775]
Flow 1
on_issue_status
- resolution_provider.resolution_support.'respondentContact' should be 'contact'
- gro_type is required in the gros object

Flow 2
on_issue_status
- resolution_provider.resolution_support.'respondentContact' should be 'contact'
- gro_type is required in the gros object
@kishorgandham

**Comment by kishorgandham** [comment]
Feedback has been incorporated. Kindly merge this PR and review https://github.com/ONDC-Official/verification-logs/pull/776

**Comment by Rishabh-ondc** [comment]
Logs cleared, keeping in consideration that the seller app is not taking on-network logistics at the moment, therefore hasn't illustrated the cascading flow yet.
@kishorgandham
