### ISSUE TITLE
Shipyaari (IGM) - Compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#792]
on_issue_status
resolution_support.chat_link attribute is optional, need not be sent if empty

unsolicited_on_issue_status
updated_at timestamp should not change as there is no change in the payload after having already shared the resolution

@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@Rishabh-ondc 
PR: [LINK](https://github.com/ONDC-Official/verification-logs/pull/796)

Resolved the Issues kindly review!

**Comment by Rishabh-ondc** [comment]
Logs cleared
@prashantpdwivedi
