### ISSUE TITLE
Xpressbazaar (LSP BAP) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/verification-logs#800]
**/search**

- category Beauty & Hygiene is not a valid category (should be one of the [allowed categories](https://docs.google.com/spreadsheets/d/1Rj7Hqdvmzup5kAvzbW15NgX5dV4U8c7DtvFopCW_9cc/edit#gid=0))
- why does /on_search response take one hour, Logistics buyer app should retry sending search requests
- Either one of fixed timings (range) or split timings (both frequency and times) should be provided in /provider/time

**/init**

- Incorrect mapping of gps and address of store location. (reverse geocding shows different pincode)
- billing/address must have required property 'building'
- why has 'area_code' in /end/address changed in billing/address, though the address is same

**/confirm**

- category_id "as" invalid in @ondc/org/linked_order/items
- /items/quantity/count in @ondc/org/linked_order/items must be an integer
- @ondc/org/order_ready_to_ship should be 'yes' (y in lower case)
- provide proper url in /instructions/images

**/update**

- @ondc/org/ewaybillno and @ondc/org/ebnexpirydate should be provided in case of intercity shipments
- @ondc/org/ebnexpirydate cannot be past dated
- how is @ondc/org/linked_order changing in /update and how is it handled

@HarishMaurya6393

**Comment by tanya-ondc** [comment]
**/on_confirm**
  {
    instancePath: '/on_confirm/message/order/created_at',
    message: 'created_at does not match confirm context timestamp - "2023-06-09T08:28:35.347Z"'
  },

**/update**
  {
    instancePath: '/update/message/order/fulfillments/0/end/instructions',
    message: "must have required property 'additional_desc'"
  },
  {
    instancePath: '/update/message/order/fulfillments/',
    message: 'Fulfillment object should include start and end instructions if ready_to_ship is Yes'
  }

@HarishMaurya6393

**Comment by NJ-Nitank** [comment]
Hi Tanya, As I have checked in docs.
'{
instancePath: '/update/message/order/fulfillments/',
message: 'Fulfillment object should include start and end instructions if ready_to_ship is Yes'
}'

This field is the optional as stated at  in update on 84{Optional, required for providing delivery instructions}. Please check it once.

**Comment by ensenterprises** [comment]
@tanya-ondc Any feedback for us?

**Comment by abhinavv245** [comment]
## Flow 1

- Message Id cannot be same for different sets of APIs

**/search**
- /message/intent/@ondc/org/payload_details/weight/value must be number
- /message/intent/@ondc/org/payload_details/dimensions/length/value must be number
- /message/intent/@ondc/org/payload_details/dimensions/breadth/value must be number
- /message/intent/@ondc/org/payload_details/dimensions/height/value must be number
- reverse geocoding of store gps cordinates shows a different pincode

**/on_search**
- /message/catalog/bpp/providers/items/parent_item_id must be string (In case of schema issues, buyer app should send NACK)

**/init**

- billing.created_at should match context.timestamp
- billing.updated_at should match context.timestamp

**/confirm**

- why was RTO Charge added in quote (if added by LSP, buyer app should send NACK)
- /message/order/@ondc/org/linked_order/items/quantity/count must be integer
- /message/order/@ondc/org/linked_order/order/weight/value must be number
- Default order state should be used in /confirm ('Created')
- order.created_at timestamp should match context.timestamp

**/update**

- updated_at timestamp should match the context timestamp in update

## Flow 2

- cancellation flow needs to be provided

@NJ-Nitank

**Comment by tanya-ondc** [comment]
Addition to above issues:

/confirm:

* payment object mandatory in /confirm

**Comment by abhinavv245** [comment]
## Flow 1

**/init**

- why have fulfillment start and end gps cordinates changed in /init

**/confirm**

- /message/order/@ondc/org/linked_order/items/quantity/count must be integer
- @ondc/org/settlement_details should remain same as provided by LSP in /on_init

**/update**

- /message/order/@ondc/org/linked_order/items/quantity/count must be integer
- why has order state changed to 'In-progress'

## Flow 2

- cancellation flow needs to be provided

**provder.json is an invalid file**

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@abhinavv245, I have submitted updated log for Logistics for both Flow, As per previous discussion about express delivery. Please mark those approved as LSP is not supporting express delivery.

**Comment by abhinavv245** [comment]
## Flow 1

**search**

- gps cordinates precision should be upto 6 decimal places

**/init**

- why is buyer app sending settlement details (payment is collected by BAP only)

## Flow 2

- similar issues

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
In /search,  in end "gps": "12.9088400000001, 77.549113", these details are from the buyer side and same thing i am using.
In /init, i am sending that which is mentioned in API contract  "settlement_counterparty":"buyer-app".

Please provide me the clarification about this.
 
@abhinavv245 @tanya-ondc

**Comment by abhinavv245** [comment]
## Flow 1

**/init**

- fulfillments/id should be one of the ids returned in bpp/fulfillments in /on_search catalog
- category_id is not matching with the one returned in /on_search for item id: 18

**/confirm**

- Is Auto-RTS supported in /confirm ?

## Flow 2

- similar issues as above

**/init**

- /billing/created_at and /billing/updated_at does not match context/timestamp

**/update**

- fulfillments/type is incorrect

**/on_cancel**

- invalid attribute 'awB_no', BAP should send NACK

@NJ-Nitank

**Comment by abhinavv245** [comment]
## Flow 1 and Flow 2

**/on_search**

- invalid LSP location gps (bpp/providers/locations/gps) ",", how is Buyer app handling it? As if LSP sends its location, buyer app needs to drop the package to LSP's location.

**/init**

- why is building = locality?

### Is Auto-RTS supported in /confirm ?

### Is RTO flow handled at logistics buyer app side ?

@NJ-Nitank

**Comment by abhinavv245** [comment]
## Flow 1

**/on_confirm**

- 'Serviceable' is not a valid fulfillment state in /on_confirm (How is BAP handling it)

**/on_update**

- why has order state changed back to 'Created' after 'Accepted' in /on_confirm (how is buyer app handling this descripancy)

## Flow 2
- separate flow should be initiated for cancellation (transaction_id cannot be same as Flow 1)

similar issues as Flow 1

**/on_cancel**

- order/id should be same as /on_confirm (buyer app should send NACK)

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@abhinavv245 @tanya-ondc, I have submitted revised logs, Please review the logs.

**Comment by abhinavv245** [comment]
## Flow 1

**/on_status**

- how is BAP handling when only  unsolicited /on_status for Order-delivered is provided 

## Flow 2

- Is RTO flow handled at logistics buyer app side ?

@NJ-Nitank

**Comment by abhinavv245** [comment]
## Flow 2

**/on_cancel**

- invalid schema (Buyer app should send NACK)

### Note: Kindly test with a verified LSP

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@abhinavv245, I have submitted the logs for LSP, Please check.

**Comment by abhinavv245** [comment]
## Flow 1

- LSP with P2P fulfillments is recommended to be procured for hyperlocal deliveries

**/init**

- /init/0/message/order/billing/address/building cannot be equal to locality (same for start location)

**/confirm**

- /confirm/0/message/order/payment/type mismatches in /payment in /on_init and /confirm

**/update**

- Pickup code is not required for P2H2P shipments as shipping label is provided by LSP

## Flow 2

- similar issues as above

**/on_status**

- /on_status call for Fulfillment state - 'Order-picked-up' missing

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@abhinavv245, Here is the updated PR [LSP](https://github.com/ONDC-Official/verification-logs/pull/1277),
Please check this, checked with validation tool, there was no error.

**Comment by bluecypher** [comment]
Logs cleared for v1.1.0

@NJ-Nitank
