### ISSUE TITLE
Delcapper (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#817]
- context.core_version should be 1.0.0
- respondent_actions.contact.email is changing from "processing" action to "resolved" action
- on_issue_status; updated_at timestamp should not change if there was no change in the provided information

@vomayank

**Comment by vomayank** [comment]
@Rishabh-ondc we have fixed All above Issue and Raise PR please merge the PR and Verify.

**Comment by Rishabh-ondc** [comment]
Clarification
- Do ensure actual GRO info is captured and also the same when deployed in production. As of now the info provided is provided as mentioned in the API contract itself.

@vomayank

**Comment by vomayank** [comment]
@Rishabh-ondc GRO Details as of now its a dummy record. we will update it for pre production and production both.

**Comment by Rishabh-ondc** [comment]
Logs cleared
@vomayank
