### ISSUE TITLE
XpressBazaar (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#833]
on_issue
- ttl should not be provided 

on_issue_status
- message_id is changing over the calls (issue_status and on_issue_status)

General issues
- Closure API call missing
- Second flow missing based on the test case scenarios defined (for fulfilment category being cascaded to lsp)

Clarification
- Do ensure actual GRO info is captured when deployed in production. As of now the info provided is provided as mentioned in the API contract

@HarishMaurya6393

**Comment by ensenterprises** [comment]
@Rishabh-ondc We have submitted the updated logs, Please have a look.
Thanks,

**Comment by NJ-Nitank** [comment]
@Rishabh-ondc 
Please close this, Logs are approved for IGM for Xpressbazar.

**Comment by Rishabh-ondc** [comment]
Logs cleared
