### ISSUE TITLE
Loadshare (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#857]
Loadshare - Gofrugal
on_issue_status; 
- resolution has not been shared

Clarification
- Hope issue_status call is not waited for providing updates on the on_issue_status call

@dagapurva3

**Comment by dagapurva3** [comment]
We have updated the logs, please check, and yes the unsolicited on_issue_status call is sent when the ticket is updated

**Comment by Rishabh-ondc** [comment]
Logs cleared
@dagapurva3
