### ISSUE TITLE
XpressBazaar (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#863]
Flow 1
on_issue
- context.city is changing in request and responses

on_issue_status
- context.ttl should not be there
- resolution_provider.respondent_info.type should be TRANSACTION-COUNTERPARTY-NP

escalate_issue
- emulating escalations flows not required as of now

Clarifications
- Hope issue_status API call is not being waited for providing the resolution action on_issue_status
- Please share logs of Flow 2 as well (for fulfilment category)

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
Hope issue_status API call is not being waited for providing the resolution action on_issue_status => Its working as per the flow.

Please share logs of Flow 2 as well (for fulfilment category) => Working on this share it shortly.

**Comment by NJ-Nitank** [comment]
@Rishabh-ondc, We have submitted updated logs for IGM, please review those logs.

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_status
- Avoid using placeholder values for chat_link attribute. It is optional and may not be sent if not available

Flow 2
on_issue_status
- Avoid using placeholder values for chat_link attribute. It is optional and may not be sent if not available

@NJ-Nitank

**Comment by Rishabh-ondc** [comment]
Logs cleared

@NJ-Nitank

**Comment by NJ-Nitank** [comment]
Thanks @Rishabh-ondc
