### ISSUE TITLE
Nearshop (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#872]
on_issue
- context.version should be 1.0.0
- context.ttl should not be there
- created_at has changed

on_issue_status
- context.version should be 1.0.0
- context.ttl should not be there
- created_at has changed
- on_issue_status should only capture the respondent.actions trail, no other object is required

on_issue_status_after_resolved
- context.version should be 1.0.0
- context.ttl should not be there
- created_at has changed
- on_issue_status should only capture the respondent.actions trail, no other object is required
- resolution_provider.respondent_info.type should TRANSACTION-COUNTERPARTY-NP

General comments
- Please include the API call for closing the issue as well
- Please include API calls for flow 2 (fulfillment category) as well 

Clarification 
- Hope issue_status API request is not being waited for providing the resolution

@RonitKumarSinha

**Comment by RonitKumarSinha** [comment]
General comments
Please include API calls for flow 2 (fulfillment category) as well.
**Answer - Flow 2 is not applicable as we are supporting off network delivery/logistics currently**

Clarification
Hope issue_status API request is not being waited for providing the resolution.
**Answer - Its not being waited**

@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
For flow 2, please illustrate one flow for fulfillment category as well to signify that logistics related issues are also being handled.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@RonitKumarSinha
