### ISSUE TITLE
DTDC (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#873]
on_issue
- context.version should be 1.0.0
- there is a change in context.bap_uri
- Please use actual (near actual) name and contact info in the updated_by object

on_issue_status
- context.version should be 1.0.0
- there is a change in context.bap_uri
- Please use actual (near actual) name and contact info in the updated_by object
- updated_at has changed with no change to the action trails

on_issue_status
- context.version should be 1.0.0
- there is a change in context.bap_uri
- Please use actual (near actual) name and contact info in the updated_by object
- updated_at has not changed with no change to the action trails
- Please use actual (near actual) name and contact info in the gro object

@aditya-sharma2-shipsy

**Comment by aditya-sharma2-shipsy** [comment]
@Rishabh-ondc we have made the changes as per the above issues and have fixed the issues, attaching the below PR
https://github.com/ONDC-Official/verification-logs/pull/877/files

**Comment by Rishabh-ondc** [comment]
issue
- context.signature should not be there

on_issue
- created_at has changed

issue_status
- context.signature should not be there

on_issue_status
- updated_at has changed

issue_close
- context.signature should not be there

@aditya-sharma2-shipsy

**Comment by aditya-sharma2-shipsy** [comment]
@Rishabh-ondc have attached the PR below with fix, request you to please consider new logs provided in the below PR
https://github.com/ONDC-Official/verification-logs/pull/896

**Comment by Rishabh-ondc** [comment]
Logs cleared

@aditya-sharma2-shipsy
