### ISSUE TITLE
Plotch (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#901]
on-issue
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP

on-issue-status
- respondent_actions should comprise all the actions Processing as well as resolved
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- issue.created_at changed slightly
- respondent_info.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.type should TRANSACTION-COUNTERPARTY-NP
- resolution_support.gro.gro_typ should be TRANSACTION-COUNTERPARTY-NP-GRO

on-issue-status -resolved
- has different issue.id
- has date different timestamps
- If the it is the same complaint, then resolution should not change
- respondent_actions should comprise all the actions Processing as well as resolved
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.type should TRANSACTION-COUNTERPARTY-NP
- resolution_support.gro.gro_typ should be TRANSACTION-COUNTERPARTY-NP-GRO

issue-closed
- same issue.created_at and issue.updated_at

Clarifications
- Please share a flow for a complaint for fulfillment category as well

**Comment by vikramacharya** [comment]
@Rishabh-ondc : We have tested the IGM flow with Gofrugal. Please review the latest PR
https://github.com/ONDC-Official/v1.1.0-logs/pull/396

**Comment by vikramacharya** [comment]
@Rishabh-ondc - Have tested the flow of IGM for fulfilment category as well. 
https://github.com/ONDC-Official/v1.1.0-logs/pull/408

**Comment by Rishabh-ondc** [comment]
BAP
issue
- Please illustrate for category ITEM or FULFILLMENT for MVP implementation logs

issue(close)
- issue.created_at should not change

Clarifications
- Provide logs for two flows, one for item category and one for fulfillment category
- Empty attributes need not be sent if optional

BPP
on_issue
- context.ttl should not be there
- expected_response_time and expected_resolution_time should not be sent
- resolution and resolution_provider object should be sent only if resolution not provided
- selected_odrs_info and additional_info_required need not be sent for MVP flows
- issue.created_at has changed

on_issue_status
- context.ttl should not be there
- context.domain has changed
- issue.created_at has changed
- resolution_actions should contain actions trail of both PROCESSING and RESOLVED
- respondent_info.contact.name should not be there
- gros object should be within resolution_support object

on_issue(closed)
- on_issue call not required for complaint close API call

Clarifications
- Empty attributes need not be sent if optional
- Provide logs for buyer app API calls as well
- Provide logs for two flows, one for item category and one for fulfillment category

@vikramacharya

**Comment by vikramacharya** [comment]
@Rishabh-ondc - feedback implemented. PR submitted for both the flow Item and fulfilment category.
https://github.com/ONDC-Official/v1.1.0-logs/pull/427

**Comment by dileswarp** [comment]
@Rishabh-ondc  Feedback Implemented for BPP on_issue/on_issue_satus.
https://github.com/ONDC-Official/v1.1.0-logs/pull/436

**Comment by Rishabh-ondc** [comment]
BAP
Item-flow
issue
- provider_id should be string
- fulfillments.id should be string
- issue.source.network_participant_id should be the subscriber_id not the subscriber_url

issue(closed)
- context.message_id has not changed

fulfillment-flow
issue
- provider_id should be string
- fulfillments.id should be string
- issue.source.network_participant_id should be the subscriber_id not the subscriber_url

issue(closed)
- context.message_id has not changed


BPP
on_issue_status
- provide cascaded_level attribute in resolved action as well if provided in processing acrtion

Clarifications
- Empty attributes need not be sent if optional
- Provide log for complaint "close" API call as well
- Provide logs for two flows, one for item category and one for fulfillment category

@vikramacharya @dileswarp

**Comment by dileswarp** [comment]
@Rishabh-ondc Feedback Implemented. PR submitted for both the flow Item and fulfilment category. Please review
https://github.com/ONDC-Official/v1.1.0-logs/pull/443

**Comment by dileswarp** [comment]
@Rishabh-ondc https://github.com/ONDC-Official/v1.1.0-logs/pull/443 , Buyer app logs provided . Please review asap

**Comment by Rishabh-ondc** [comment]
BPP
item_flow
on_issue
- context.timestamp should be equal or greater than the issue.updated_at timestamp

on_issue_status
- context.timestamp should be equal or greater than the issue.updated_at timestamp

fulfillment_flow
on_issue
- context.timestamp should be equal or greater than the issue.updated_at timestamp

on_issue_status
- context.timestamp should be equal or greater than the issue.updated_at timestamp

@dileswarp

**Comment by dileswarp** [comment]
@Rishabh-ondc https://github.com/ONDC-Official/v1.1.0-logs/pull/459 bpp/item_flow/fullfillment_flow context.timestamp feedback fixed, Please review

**Comment by Rishabh-ondc** [comment]
Logs cleared

@dileswarp

**Comment by dileswarp** [comment]
Thanks
