### ISSUE TITLE
Marico (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#902]
Flow 1
on_issue
- context.ttl should not be there
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP

issue_status
- context.city has changed

on_issue_unsolicited
- the resolution should be provided in an unsolicited on_issue_status call and not on_issue call
- context.ttl should not be there
- respondent_actions should comprise all the actions Processing as well as resolved
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.organization.org.name should have the subscriber_id of the NP along with the domain of the NP

issue_status
- context.city has changed

on_issue_status_after_resolved
- context.ttl should not be there
- issue.updated_at should not change as there is no new update to the actions
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.organization.org.name should have the subscriber_id of the NP along with the domain of the NP
- resolution_support.chat_link wasn't provided previously and looks same as the API contract

Flow 2
on_issue
- context.ttl should not be there
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP

issue_status
- context.city has changed

on_issue_unsolicited
- need_more_info flow is not being handled at the moment

on_issue_unsolicited_resolved
- the resolution should be provided in an unsolicited on_issue_status call and not on_issue call
- context.ttl should not be there
- respondent_actions should comprise all the actions Processing as well as resolved
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.organization.org.name should have the subscriber_id of the NP along with the domain of the NP

issue_status
- context.city has changed

on_issue_status_after_resolved
- context.ttl should not be there
- respondent_actions.org.name should have the subscriber_id of the NP along with the domain of the NP
- respondent_info.organization.org.name should have the subscriber_id of the NP along with the domain of the NP
- resolution_support.chat_link wasn't provided previously and looks same as the API contract

@sharva

**Comment by sharva** [comment]
@Rishabh-ondc 

New PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/375

Note:
- We have worked on feedback where we are sending requests as seller (respondent)
- Feedbacks like issue_status city change is feedback for buyer reference app

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue
- issue.created_at and updated_at has changed
- respondent_actions.updated_at and issue.updated_at should be same; respondent_actions.updated_at is same as context.timestamp of issue call
- respondent_actions.updated_by.org should include the domain code as well ("subscriber_id"+"::"+domain_code)

on_issue_status 
- issue.created_at has changed
- respondent_actions.updated_by.org should include the domain code as well ("subscriber_id"+"::"+domain_code)
- respondent_info.organization.org.name should include the domain code as well ("subscriber_id"+"::"+domain_code)

Flow 2
on_issue
- issue.created_at and updated_at has changed
- respondent_actions.updated_at and issue.updated_at should be same; respondent_actions.updated_at is same as context.timestamp of issue call
- respondent_actions.updated_by.org should include the domain code as well ("subscriber_id"+"::"+domain_code)

on_issue_status_unsolicited
- Need more info flows are not required as of MVP implementation

 on_issue_status_unsolicited_resolved
- issue.created_at has changed
- respondent_actions.updated_by.org should include the domain code as well ("subscriber_id"+"::"+domain_code)
- respondent_info.organization.org.name should include the domain code as well ("subscriber_id"+"::"+domain_code)

@sharva

**Comment by jbjetbro** [comment]
@Rishabh-ondc

New PR: [
](https://github.com/ONDC-Official/v1.1.0-logs/pull/779)

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue
- core_version should be 1.0.0
- issue.updated_at has not changed
- respondent_actions.updated_at same as issue.created_at 

on_issue_status
- core_version should be 1.0.0

Flow 2
- If the NP hasn't taken on-network logistics transactions, "cascaded" action is not required. The logs flow similar to the retail complaint flow. 

Clarifications
- resolution_provider.respondent_info.organization.org.name should not a dummy value; please check

@jbjetbro

**Comment by jbjetbro** [comment]
@Rishabh-ondc

New PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/779

**Comment by Rishabh-ondc** [comment]
Logs cleared

@jbjetbro
