### ISSUE TITLE
Pepstores (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#903]
Flow 1
on_issue_status
- resolution.refund_amount need not be shared if resolve action is not refund

Flow 2 
on_issue_status
- resolution.refund_amount need not be shared if resolve action is not refund

Flow 3
on_issue_status_need_more_info
- need_more_info action is not covered as part of MVP need not be shared
- respondent_actions.updated_at timestamp seems incomplete

on_issue_status_Resolved
- respondent_actions.updated_at timestamps seems incomplete for resolved action
- resolution.refund_amount need not be shared if resolve action is not refund

Clarification
- all the buyer app API calls seem to be timed 4 minutes ahead with respect to respective actions timestamps, please check
- hope issue_status call is not being waited for providing updates on the issue like resolution
- respondent_actions.person.name changes across actions, please check

@quantummach14

**Comment by quantummach14** [comment]
@Rishabh-ondc Uploaded revised logs. 
Removed resolution.refund_amount where resolve action is not "Refund".

As mentioned, we are still getting 1-2mins difference in context.timestamp and created_at/updated_at timestamps.
respondent_actions.person.name changes across actions : As discussed, we are fetching agent id who gave the solution. Hence its changing.

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_status
- respondent_actions.updated_at and issue.updated_at are different, they should be same
- respondent_actions.updated_by.org.name should be the same as bpp_id
- resolution_provider.respondent_info.organization.org.name should be the same as bpp_id

Flow 2
on_issue_status
- respondent_actions.updated_at and issue.updated_at are different, they should be same
- respondent_actions.updated_by.org.name should be the same as bpp_id
- resolution_provider.respondent_info.organization.org.name should be the same as bpp_id

Flow 3
on_issue_status
- respondent_actions.updated_at and issue.updated_at are different, they should be same
- respondent_actions.updated_by.org.name should be the same as bpp_id
- resolution_provider.respondent_info.organization.org.name should be the same as bpp_id

@quantummach14

**Comment by Rishabh-ondc** [comment]
Logs cleared

@quantummach14
