### ISSUE TITLE
eSamudaay (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#910]
on_issue
- context.ttl should not be there
- respondent_actions.updated_by.org.name should be "subscriber_id"+"::"+"domain "

on_issue_status
- context.ttl should not be there
- respondent_actions.updated_by.org.name should be "subscriber_id"+"::"+"domain "

Clarification
- Please share flow for fulfillment category as well. In case on-network logistics will be taken, please illustrate the cascaded flows as well which flow 2 and flow 3

@skmrSharma

**Comment by skmrSharma** [comment]
@Rishabh-ondc we do not have ONDC logistics integration yet, hence we have not included the fulfillment logs. We only support self ship for now.
We'll be re submitting logs for those flows once logistics integration is complete.

**Comment by Rishabh-ondc** [comment]
@skmrSharma Sure, in that case please submit logs for two flows, one for item category and one for fulfillment category.

**Comment by Rishabh-ondc** [comment]
issue_item
on_issue_status_after_resolve
- resolution_support.respondentEmail is an invalid attribute
- resolution_support.respondentContact is invalid attribute

issue_fulfillment
on_issue_status_after_resolve
- resolution_support.respondentEmail is an invalid attribute
- resolution_support.respondentContact is invalid attribute

@skmrSharma

**Comment by Rishabh-ondc** [comment]
Logs cleared

@skmrSharma
