### ISSUE TITLE
Dunzo Seller App (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#935]
on_issue_after_ticket_creation
- "PROCESSING" action is to be provided in the on_issue call itself
- updated_at timestamp should not change if there is no change in the actions

on_issue_status
- "PROCESSING" action should be sent in the on_issue call and not on on_issue_status
- context.timestamp is much before the action timestamp
- context.version should be 1.0.0
- cascaded_level should be 1 for seller app if not cascaded to a logistics provider
- resolution_provider object is required only when a resolution is provided
- issue.created_at has changed

on_issue_status_after_is_resolved
- context.timestamp is much before the action timestamp
- context.version should be 1.0.0
- cascaded_level should be 1 for seller app if not cascaded to a logistics provider
- resolution_provider object is required only when a resolution is provided
- respondent_info.type should be TRANSACTION-COUNTERPARTY-NP for seller app
- respondent_info.contact.phone is empty
- respondent_info.resolution_support.contact phone and email is empty
- respondent_info.resolution_support.gros.gro_type should be TRANSACTION-COUNTERPARTY-NP-GRO for seller app
- issue.created_at has changed

on_issue_closed_from_buyer
- on_issue response call not required for complaint closing call

Clarifications
- Please follow the API contract for the flows and the test case scenarios laid out for sharing logs
- Not clear of the complaint resolution trail based on the context.timestamps and the actions taken

@anandyukta

**Comment by Rishabh-ondc** [comment]
2_send_on_issue
- issue.updated_at should be same as last respondent_actions.updated_at

4_send_on_issue_status
- context.bpp_id and bpp_uri is empty

Clarifications
- Please share logs as per the test case scenarios mentioned for IGM. One log flow for item category, one log flow for fulfillment category (two log flows in case on-network logistics is procured).
- need_more_info may not be illustrated as of now
- Empty attributes need not be shared if optional (resolution_support.chat_link) 

@Ankush @anandyukta

**Comment by ankush1106** [comment]
Please find the fresh logs for same: https://github.com/ONDC-Official/v1.1.0-logs/pull/660
@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
on_issue_status_resolved
- issue.created_at has changed

@ankush1106

**Comment by ankush1106** [comment]
its been fixed now, the milliseconds were rounded off. I have updated the logs: PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/688
@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
Logs cleared

@ankush1106
