### ISSUE TITLE
Ninjacart - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#969]
### Multiple issues across the Flows

**/on_search**

- tracking and contact are optional attributes in bpp/fulfillments
- category_id is optional attribute in /bpp/providers/ (should be present at items level)
- old serviceability construct (/locations/circle) should be provided for hyperlocal serviceability

**/on_update (Initiated)**

- /tags attribute is not required in /items/2/
- "start" and "end" in /fulfillments/ must have required property 'time'
- context/timestamp and /updated_at must be in valid "date-time" format
- context/message_id of all unsolicited /on_update calls should be same for a particular /update request
- order/created_at timestamp can't change (should remain same as in /confirm)

## Flow 2 (Several issues within the flow)

**/on_search**

- inaccurate geocoding of GPS and address of store locations
- quantity can't have a value <= 0 in "@ondc/org/mandatory_reqs_veggies_fruits"
- invalid serviceability of 0 km in /tags

**/select (Non-serviceable)**

- Invalid flow; Why is this /select called after the entire txn of Flow 2

**/on_select (Non-serviceable)**

- delivery charges should not be present in quote/breakup if location is not serviceable
- Why is this location not serviceable even though it falls in the serviceability radius?

**/on_status**

- Several missing attributes and numerous invalid attributes in the payload
- how can order be delivered even before the order is confirmed? (check timestamps)

**/on_cancel**

- Why is the order cancelled after delivery?

## Flow 3,4,5

- Despite previous discussions, multiple issues persist.

**Comment by bluecypher** [comment]
## Common Issues

**/on_select**

- items/quantity is not required

**/on_init**

- provider/locations is an invalid attribute

**/on_confirm**

- fulfillments/start/location/address is not required
- How are estimated pickup and delivery timestamps calculated? (not in alignment with shipping time and TAT)

**/on_status**

- estimated timestamps should not change without reasons

## Flow 2

**/on_select (Non-serviceable)**

- mandatory attributes "@ondc/org/category", "@ondc/org/TAT", "@ondc/org/provider_name" must be present in /fulfillments (Schema should not change)

## Flow 5

- complete out-of-stock scenario should be tested as per Flow 5

**Comment by subhendu17620** [comment]
Updated logs
please review https://github.com/ONDC-Official/verification-logs/pull/1051

**Comment by bluecypher** [comment]
## Common Issues:

**/on_search**

- old serviceability construct should be defined in /locations/circle until deprecated

**/on_confirm**

- estimated pickup and delivery timestamps should be realistic and feasible


@subhendu17620

**Comment by subhendu17620** [comment]
updated logs 
please review https://github.com/ONDC-Official/verification-logs/pull/1079

**Comment by bluecypher** [comment]
@BLR-0118, the Ninjacart BPP (v1.1.0) logs seem fine. Please proceed with your review.

@subhendu17620
