### ISSUE TITLE
Bizom BPP (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#973]
Flow 2
issue (cascading)
- context.domain should be "nic2004:60232"
- issue_actions.complainant_actions object has changed completely
- issue_actions.respondent_actions for Processing has changed completely
- issue_actions.respondent_actions.updated_by.org.name; domain code has changed between on_issue call and issue (cascading) call

on_issue (unsolicited Cascaded-Response)
- context.domain should be "nic2004:60232"
- context.transaction_id has changed
- respondent_actions.updated_by.org should have the nic2004:60232 (logistics) as the domain code for the "cascaded" action

on_issue_status (solicited resolution)
- context.bap_id and bap_uri does not match
- context.domain signifies retail but the bpp is loadshare
- context.actions says "on_issue" but payload name says on_issue_status
- context.transaction_id and message_id does not match with the respective issue_status call
- on_issue/ on_issue_status call should not have the issue.status and issue.category attributes

issue_status (cascaded to NP)
- payload same as issue_status with change in domain code and timestamp only
- context.domain should be "nic2004:60232"

issue (close complaint)
- context.domain should be "nic2004:52110"

issue (Cascaded close complaint)
- context.domain should be "nic2004:60232"
- context.transaction_id and message_id are same as issue (close complaint)

Flow 3
on_issue (processing)
- the context object contains details of the logistics domain call but the issue object is of the actions of the retail seller app 

issue (cascading)
- context.action should be "issue"
- respondent_actions.updated_by.org should have the nic2004:60232 (logistics) as the domain code for the "cascaded" action

on_issue_status_logistic (unsolicited resolution)
- context.message_id and transaction_id are the same
- issue.created_at has changed
- issue.updated_at and respondent_actions.updated_at for resolution object are different

on_issue_status_retail (unsolicited resolution)
- the context object contains details of the logistics domain call but the issue object is of the actions of the retail seller app
- If this is the payload intended for the retail buyer app, it should not be sent. The seller app should only send on resolution whether it is cascaded as received from LSP or they are providing a different resolution themselves

on_issue_status_retail (Sellerapp Providing Resolution)
- respondent_info.resolution_support.gros should contain gro info of both seller app and LSP

issue (close complaint)
- payload shared seems incorrect

issue (Cascaded close complaint)
- issue.rating attribute not sent

@Akhil-873

**Comment by Rishabh-ondc** [comment]
Flow 2
on_issue (unsolicted cascaded response)
- Seller app's subscriber id should be bap_id in context when on_issue comes from logistics provider

on_issue_status from lsp
- payload not provided

on_issue_status (solicited response)
- resolution received from lsp is missing
- context.transaction_id has changed
- issue.resolution_provider.respondent_info.organization must have required property 'org'

Flow 3
issue (cascading)
- context.ttl missing

on_issue_status_retail (Sellerapp Providing Resolution)
- /message/issue/resolution/action_triggered must be equal to one of the allowed values
- if this is a solicited call, context.message_id mismatch
- issue.created_at has changed

on_issue_status_logistic (Sellerapp Providing Resolution)
- This should be an /issue call not /on_issue_status, for providing updated info (if any) on the complaint

issue (close complaint)
- issue object not provided

@Akhil-873

**Comment by RupalSingla** [comment]
##Flow 1 :-
on_issue_status (unsolicited)
-  context timestamp should be greater than or equal to updated_at in on_issue_status

##Flow 2 :-
on_issue_status
- Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context.  (Remove space between bap_id+ domain)

lsp_on_issue_status
- Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context (Remove space between bap_id+ domain)

##Flow 3
issue_logistic (Sellerapp Providing Resolution).txt 
extra call added

on_issue_status
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BAP ID

on_issue_status(unsolicited)
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BAP ID

**Comment by Akhil-873** [comment]
@RupalSingla , could you clarify what the comment on Flow 3 BAP ID mismatch is about? the [3] item of respondent_actions seems to imply its from lsp , and not logistic buyer or buyer app.

**Comment by Akhil-873** [comment]
@RupalSingla , could you clarify what the comment on Flow 3 BAP ID mismatch is about? the [3] item of respondent_actions seems to imply its from lsp , and not logistic buyer or buyer app.

**Comment by Akhil-873** [comment]
@Rishabh-ondc , have raised a PR #1265
for the above

@samarthpatel-bizom

**Comment by Rishabh-ondc** [comment]
Flow 1
ret_on_issue_status
- issue.updated_at should not change if there is no change in the action trail

ret_on_issue_status_unsolicited
- resolution_support.chat_link has dummy values provided, need not be shared if there is no chat support option available

Flow 2
ret_on_issue_status
- The payload should only capture the action trail; other details of the issue are not required
- same PROCESSING action by lsp is repeated twice
- issue.updated_at should not change if the resolution provided by lsp is cascaded as provided

lsp_issue_close
- payload provided for a different issue.id; please check

Flow 3
lsp_on_issue
- payload provided for a different issue.id; please check

ret_on_issue_status
- The payload should only capture the action trail; other details of the issue are not required
- resolve action timestamp for seller app is less than resolve action timestamp of lsp

lsp_issue_close
- payload provided for a different issue.id; please check

@Akhil-873

**Comment by Rishabh-ondc** [comment]
Flow 1
ret_on_issue_status
- context.timestamp hasn't changed between on_issue and on_issue_status

Flow 2
lsp_issue
- context.timestamp should be greater than equal to issue.updated_at

lsp_issue_status
- context.message_id is same as ret_issue_status.context.message_id

Flow 3
lsp_issue
- context.timestamp should be greater than equal to issue.updated_at

ret_on_issue_status
- context.domain is incorrect
- context.bap_id, bap_uri, bpp_id, bpp_uri is incorrect 

@Akhil-873

**Comment by Rishabh-ondc** [comment]
Flow 3
ret_on_issue_status
- RESOLVED action for LSP missing in the action trail

@Akhil-873

**Comment by Rishabh-ondc** [comment]
Logs cleared

@Akhil-873
