### ISSUE TITLE
Ninjacart (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#975]
Issue 1
on_issue
- context.timestamp has not changed
- issue.updated_at has not changed
- respondent_actions.updated_at should have 3 decimal points for milliseconds of the timestamp

on_issue_status
- context.timestamp is of the first issue API call
- on_issue_status should not have the complainant_actions trail, only the respondent_actions trail should be provided
- resolution_provider object should only be provided if a resolution is provided by the seller app

Issue 2
- same as above

Clarification
- Domain added with subscriber_id of NP as part of the "org" attribute should ideally match the domain code in the context object
- Resolution has not been provided in the illustrated logs
- Provide two logs, one for "ITEM" category and one for "FULFILLMENT" category
- Provide log for complaint "close" API call from buyer app as well
- Empty objects should not be sent if optional, tags in various objects are not required

@subhendu-ninjacart

**Comment by subhendu17620** [comment]
@Rishabh-ondc Raised new PR with updated logs
https://github.com/ONDC-Official/verification-logs/pull/1009

please review

**Comment by Rishabh-ondc** [comment]
item flow
on_issue_status
- on_issue_status for resolved action doesn't have a resolution_support ojbect

fulfillment flow
on_issue_status to buyer unsolicited
- context.timstamp has not chaged from previous API call

on_issue_status to buyer  
- context.timstamp has not chaged from previous API call

issue to logisctics
- context.time same as isssue from buyer

Clarification
- if on-network logistics are being leveraged, please share logs for scenario 3 as well

@subhendu17620

**Comment by subhendu17620** [comment]
Flow 1 & 2 updated:  https://github.com/ONDC-Official/verification-logs/pull/1043

**Comment by subhendu17620** [comment]
Updated logs https://github.com/ONDC-Official/verification-logs/pull/1051
please review

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue
- context.ttl is not required

on_issue_status_unsolicited
- context.ttl is not required

Flow 2
2_on_issue
- context.ttl is not required

5_on_issue_status
- context.ttl is not required

7_on_issue_status
- context.ttl is not required

Flow 3
2_on_issue
- context.ttl is not required

5_on_issue_status
- context.ttl is not required

7_on_issue_status
- context.ttl is not required

8_on_issue_status_to_logistics_unsolicited
- the update on the resolution done by the seller app should be provided to the lsp using the "issue" API call and not on the "on_issue_status" API call

@subhendu17620

**Comment by subhendu17620** [comment]
@Rishabh-ondc we have resolved all the issues.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@subhendu17620
