### ISSUE TITLE
Oogashop (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/verification-logs#985]
Please illustrate the logs with an NP or with the reference buyer app.

@ShashiKant

**Comment by Rishabh-ondc** [comment]
Flow 1 
on_issue
- respondent_actions.updated_by.org.name should be of the format - "subscriber_id::domain_code"

on_issue_status_unsolicited
- context.message_id should ne unique for unsolicited API calls
- respondent_info.orgnization.org.name should be of the format - "subscriber_id::domain_code"
- respondent_actions.updated_by.org.name should be of the format - "subscriber_id::domain_code"
- contact.phone and person.name has changed across respondent_actions, please check
- Please provide actual/ near actual values for contact.phone 

on_issue_rating
- API response to complaint close call is not required

Flow 2
- same as above

Flow 3
- same as above

@Shashikant

**Comment by oogashop** [comment]
Hi @Rishabh-ondc , Sorry for the late reply as we got to know about these suggestions today only, We have corrected these issues and resubmitted at https://github.com/ONDC-Official/v1.1.0-logs/pull/641 . Please have a look and review the logs.

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_status_unsolicited
- context.message_id is same as on_issue_status; should be unique
- resolution.resolution_action attribute is not required

Flow 2
- same as above

Flow 3
- same as above

@oogashop

**Comment by oogashop** [comment]
Hi @Rishabh-ondc we have corrected the above issues and re submitted at https://github.com/ONDC-Official/v1.1.0-logs/pull/680 please review them.

**Comment by Rishabh-ondc** [comment]
Logs cleared

@oogashop
